### ISSUE TITLE
Timeout Performing SCAN Crashes Entire ASPNet Core Process

### ISSUE THREAD

**Issue by toddca** [StackExchange/StackExchange.Redis#1055]
This is issue is consistent. I have updated and restarted my redis server running on Ubuntu within a docker container. Does anyone see anything on this error that might indicate the problem or where to look next? This has been working for a couple of months now without an issue.

```
Application: dotnet.exe
CoreCLR Version: 4.6.26919.2
Description: The process was terminated due to an unhandled exception.
Exception Info: StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 2, queue: 8, qu: 0, qs: 8, qc: 0, wr: 0, wq: 0, in: 83, ar: 0, clientName: APP01, serverEndpoint: Unspecified/dock02.dmz.lt.net:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 564
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.GetNextPageSync(IScanningCursor obj, Int64 cursor) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 204
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 295
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Nop.Core.Caching.RedisCacheManager.RemoveByPatternAsync(String pattern) in C:\Agent\_work\2\s\src\NopCommerce\Libraries\Nop.Core\Caching\RedisCacheManager.cs:line 144
   at Nop.Core.Caching.RedisCacheManager.RemoveByPattern(String pattern) in C:\Agent\_work\2\s\src\NopCommerce\Libraries\Nop.Core\Caching\RedisCacheManager.cs:line 236
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by NickCraver** [comment]
It *seems* like something is pushing out a background thread to do a pattern-based cleanup (this is bad, btw - the performance is not good for patterns in redis server). But that doesn't address the direct issue, exceptions! When an exception is thrown from this context, no one owns it. So .NET defaults to a global boom, which is what you're seeing. To capture and deal with such exceptions, you'll need to (at startup) rig up a handler like this:

```c#
TaskScheduler.UnobservedTaskException += (s, args) =>
{
    foreach (var ex in args.Exception.InnerExceptions)
    {
        // do something with exception, e.g. log it
    }
    args.SetObserved();
};
```
...without that, you're always going to see the app crash :)

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Comment by manilkumar** [comment]
I am still facing timeout issues while getting cache keys.Can you please me with this?

Exception:
Timeout performing SCAN (5000ms), next: SCAN, inst: 217, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: uatmims-cache.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available,  IOCP: (Busy=1,Free=999,Min=200,Max=1000), WORKER: (Busy=1,Free=32766,Min=200,Max=32767), v: 2.1.30.38891

**Comment by reslea** [comment]
Same issue here, it is consistent and nothing helps:
Timeout performing SCAN (5000ms), next: SCAN, inst: 2, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, mc: 1/1/0, mgr: 10 of 10 available, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), v: 2.1.58.34321

**Comment by mgravell** [comment]
(on the recent report) The fact that TLS is invited loved makes it a
*little* awkward (we can't trust "in"), but it *looks* like the server
really did fail to respond in a timely manner. You could try checking the
SLOWLOG to see if anything was hogging the server, but unfortunately it is
really hard for us to investigate timeout issues in other people's
environments, for obvious reasons.
