### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by protossyk** [StackExchange/StackExchange.Redis#1065]
hi:  
I met the follow errors,when i use stackExchange.redis to connect the codis server.
environment: netcore runtime 2.2,stackExchange.redis 2.0.519.qps:2000+.
```
Pipelines.Sockets.Unofficial.ConnectionResetException: Connection reset by peer ---> System.Net.Sockets.SocketException: Connection reset by peer
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 85
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 73
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 59
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe()
```
thx for reply.

**Comment by NickCraver** [comment]
Are you getting this _on connect_ or randomly? We have a lot of things we didn't realize were the same issue until recently, but if this is on-connect we mistakenly thought this was in the duplicate bucket.
