### ISSUE TITLE
redis timeout using with .netcore

### ISSUE THREAD

**Issue by gouhan** [StackExchange/StackExchange.Redis#1068]
Redis Version is:StackExchange.Redis.StrongName 1.2.7-alpha-00002
I used redis client as singleton pattern.

StackExchange.Redis.RedisTimeoutException: Timeout performing GET AppUser_Driver_iOS_App_13814725839, inst: 1, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 287, ar: 0, clientName: 172_17_16_7, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 13597 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647

**Comment by mgravell** [comment]
The short version here is: the fixes for some performance and stability
problems in v1 required major architectural changes. Those fixes exist (and
continue to evolve, currently working on a thread pool starvation under
high load scenario): we call those fixes "v2". So for things like this, the
guidance is "where possible, move to v2".

**Comment by NickCraver** [comment]
Closing this out since the advice is: please upgrade, we changed the world to make a lot of connection issues go away and behave much better :)
