### ISSUE TITLE
Got NullReferenceException by chance on reconnect

### ISSUE THREAD

**Issue by zackliu** [StackExchange/StackExchange.Redis#1174]
We're using SDK 2.0.601 and got some `NullReferenceException` by chance when reconnecting or after `RedisTimeoutException`

Here's the stack trace.

> System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Redis.ServerEndPoint.GetOutstandingCount(RedisCommand command, Int32& inst, Int32& qs, Int32& in) in E:\StackExchange.Redis\src\StackExchange.Redis\ServerEndPoint.cs:line 380
   at StackExchange.Redis.ExceptionFactory.Timeout(ConnectionMultiplexer mutiplexer, String baseErrorMessage, Message message, ServerEndPoint server) in E:\StackExchange.Redis\src\StackExchange.Redis\ExceptionFactory.cs:line 204
   at StackExchange.Redis.ConnectionMultiplexer.GetException(WriteResult result, Message message, ServerEndPoint server) in E:\StackExchange.Redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2151
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in E:\StackExchange.Redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2124

Another stack trace
> StackExchange.Redis.RedisConnectionException: Failed to write ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Redis.PhysicalBridge.WriteMessageInsideLock(PhysicalConnection physical, Message message) in C:\projects\stackexchange-redis\src\StackExchange.Redis\PhysicalBridge.cs:line 702
   at StackExchange.Redis.PhysicalBridge.ProcessBacklog() in C:\projects\stackexchange-redis\src\StackExchange.Redis\PhysicalBridge.cs:line 879

Please have a look.

**Comment by NickCraver** [comment]
We fixed the null ref here for the latest release, thanks for the heads up!
