### ISSUE TITLE
Error Reader is not allowed after reader is completed with StackExchange.Redis 2.0.519

### ISSUE THREAD

**Issue by JanakiDeviKantamneni** [StackExchange/StackExchange.Redis#1200]
We have 4 Geo specific Redis Caches. On All Redis Caches we are having this error "**Reader is not allowed after reader is completed**" very frequently .Please see below error image
![image](https://user-images.githubusercontent.com/53536313/62485077-49e63a80-b781-11e9-8217-2432e3c24ccc.png)

The Nuget we are using is StackExchange.Redis 2.0.519.

We opened a technical Microsoft ticket. They gave us few suggestions(like to use Threadpool.setminthreads(100,100),removing ConnectionMultiplexer.IsConnected ..... etc) to improve performance. After implementing those changes the redis cache performance has increased a lot but this error is still occuring but not in high frequency. I have asked Microsoft  team regarding this error, the response i got was " _I have checked your case with the Product Group, they suspect this issue is with the client library version you’re running (StackExchange.Redis 2.x) so they’re suggesting to open a GitHub issue for the team to look into_: https://github.com/StackExchange/StackExchange.Redis/issues " .

To Reproduce this issue, you can performance any CRUD operation on Redis Cache with 4000 records or 5000 records or more. You will get this error. We have reproduced this issue with Console Application, Azure Functions. 

Sample Code 1 
With 4 different geo Redis Cache
`
            foreach (var connectionString in GeoconnectionStrings)
            {
                RedisCacheHelper redisHelper = new RedisCacheHelper(connectionString);          
 bool isTokenDeleted = await redisHelper.DeleteKeyAsync(keyToDelete + "--" + "Token");            
bool isKeydeleted = await redisHelper.DeleteKeyAsync("Key2013" + keyToDelete);             
await redisHelper.DisposeConnectionAsync();
            }`

Sample Code 2 -
Without creating and disposing connection

` bool isTokenDeleted = await brazilredisHelper.DeleteKeyAsync(req.RedisKey + "--" + "Token");                       
 bool isKeydeleted = await brazilredisHelper.DeleteKeyAsync("Key2013" + req.RedisKey);`

Full Stack Trace -
_Error occured in Brazil Redis Function. Exception - System.Exception: An Unknown error occured While trying to Delete data from RedisCache. ErrorCode: [15434109] ---> **System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in C:\projects\stackexchange-redis\src\StackExchange.Redis\PhysicalConnection.cs:line 1328**
   at xxxxxx.Common.Helpers.RedisCacheHelper.DeleteKeyAsync(String rediskey) in C:\RandD\VSTS\xxxxxxx\_Common\Helpers\RedisCacheHelper.cs:line 113
   --- End of inner exception stack trace ---
   at xxxxxxxxx.Common.Helpers.RedisCacheHelper.DeleteKeyAsync(String rediskey) in C:\RandD\VSTS\xxxxxxxx\_Common\Helpers\RedisCacheHelper.cs:line 121
   at xxxxxxxxxxxxx.BrazilRedis.RunAsync(String myQueueItem, ILogger log) in C:\RandD\VSTS\xxxxxxxx\BrazilRedis.cs:line 30_

Could anyone please help us in fixing this issue.

>

**Comment by Sam09m** [comment]
Any update on this? I have also come across this same error while leveraging Redis cache from an Azure Function.

**Comment by MatanShabtay** [comment]
Same here

**Comment by NickCraver** [comment]
This was resolved in later versions of the library, please update your NuGet reference to latest for a fix here :)

**Comment by zvolkov** [comment]
Please reopen, we just got one of these on 8/26, when calling IDatabaseAsync.HashGetLeaseAsync. We're on Redis SE 2.1.30 running under .net core 3.1.x

>System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1495

**Comment by ashuthinks** [comment]
Im also facing the same issue is there any solution for this?

**Comment by lookingcloudy** [comment]
Yep - same error here.  Seems pretty common.
