### ISSUE TITLE
Cannot access a disposed object. Object name: 'xxx-web'.

### ISSUE THREAD

**Issue by myokok** [StackExchange/StackExchange.Redis#1235]
.netcore+linux 
is Sentinel

Error message: **Cannot access a disposed object. Object name: 'xxx-web'.**

exception.stack_trace:

at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2214
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ListRange(RedisKey key, Int64 start, Int64 stop, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 955
   at Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)

**Comment by NickCraver** [comment]
Which version of the library were you on? This should be fixed in newer releases but I'd like to confirm.

**Comment by christiankohl-CV** [comment]
We seem to be getting a similar issue. Can I tag this on to this one or should I add a new issue?

We are using a site hosted in Azure Web Apps with Azure REDIS
Version 2.0.601 of StackExchange.Redis

Getting the following error randomly - generally have to kill one of the web instances to "fix" it
Any ideas, is this fix in a new version?

Key was: GBHCVTWO-PC:CASHWEB:900:PCP-1033346:0606:1.00:636821095169080876 System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RD0003FF6F2022'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at BusinessObjects.Caching.RedisCacheProvider.StringSet(String key, String value, Nullable`1 expiry)
   at BusinessObjects.Caching.RedisCacheProvider.SetWithExpiry[T](String key, T value, TimeSpan expiration)

Exception: Cannot access a disposed object.
Object name: 'RD0003FF6F2022'.
Source: StackExchange.Redis
Stack Trace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at BusinessObjects.Caching.RedisCacheProvider.StringSet(String key, String value, Nullable`1 expiry)
   at BusinessObjects.Caching.RedisCacheProvider.SetWithExpiry[T](String key, T value, TimeSpan expiration)
Target Site: T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint)

**Comment by danielHalan** [comment]
We have had similar issue, also in Azure Web App, but has happened in a regular Console Process too.

When this happens, what is the correct way to re-create a new connection/instance, i.e. noticed that in one case, even if we call "ConnectionMultiplexer.Connect()" to get a new connection we kept getting the same error (Cannot access a disposed object...), assume it is re-using pooled instances, is there a way to clear the pool?

**Comment by rakker91** [comment]
We also seem to be getting this.  Seems to happen in a high volume situation against AWS Elasticache redis.

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'obfuscated'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2707
   at StackExchange.Redis.RedisDatabase.StringGetAsync(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2394
  ....
`

here's the version information:
`<PackageReference Include="StackExchange.Redis" Version="2.1.58" />`

**Comment by rakker91** [comment]
We found our issue!  See https://github.com/StackExchange/StackExchange.Redis/issues/1579 for more details, but basically, what happened was a race condition on shutdown of a container.  We called close on one thread while another thread was still trying to use the redis client.

If you see this, you may want to check for something similar first.

**Comment by NickCraver** [comment]
Glad this got sorted! Closing out issue here to cleanup :)
