### ISSUE TITLE
null Ref in StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log)

### ISSUE THREAD

**Issue by BoyangCheng** [StackExchange/StackExchange.Redis#1260]
version: 1.2.1
After checking the known issues and pull requests, still not sure whether this null ref has been fixed in newer version.
Paste stack flow here to share:
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log)
   at StackExchange.Redis.PhysicalBridge.OnDisconnected(ConnectionFailureType failureType, PhysicalConnection connection, Boolean& isCurrent, State& oldState)
   at StackExchange.Redis.PhysicalConnection.RecordConnectionFailed(ConnectionFailureType failureType, ManagerState& managerState, Exception innerException, String origin)
   at StackExchange.Redis.PhysicalBridge.ResetNonConnected()
   at StackExchange.Redis.ServerEndPoint.ResetNonConnected()
   at StackExchange.Redis.ConnectionMultiplexer.ResetAllNonConnected()
   at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__125.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by NickCraver** [comment]
This was corrected in later versions (1.2.6 is latest in the 1.x line), but 1.x will also have no further releases - upgrading to 2.x where possible is recommended :)
