### ISSUE TITLE
No connection is available to service this operation: EXISTS 7efb5327-0ba9-4b3c-b9ca-32a78ba7e713 : WorkSpaceSession; An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), Local-CPU: n/a

### ISSUE THREAD

**Issue by edevasimjaved** [StackExchange/StackExchange.Redis#1280]
Hi,
As per your suggestion we have upgraded StackExchange.Redis to 2.* and after update not able to get the error in most of the cases. (refer to https://github.com/StackExchange/StackExchange.Redis/issues/929)

However, even in StackExchange.Redis 2.* we have encounter this issue few times.
can you suggest what should we can look in order to handle.?

the error stack trace is as following.

No connection is available to service this operation: EXISTS 7efb5327-0ba9-4b3c-b9ca-32a78ba7e713 : WorkSpaceSession; An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), Local-CPU: n/a
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2194 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 649
at inteGREAT.Web.Common.RedisHelper.KeyExist(String key)

SocketFailure (ReadSocketError/ConnectionReset, last-recv: 49) on localhost:6379/Subscription, Idle, last: UNSUBSCRIBE, origin: ReadFromPipe, outstanding: 1, last-read: 2715s ago, last-write: 0s ago, unanswered-write: 2715s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 8 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.519.65453

An existing connection was forcibly closed by the remote host
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
at System.IO.Pipelines.Pipe.GetReadAsyncResult()
at StackExchange.Redis.PhysicalConnection.d__104.MoveNext()

An existing connection was forcibly closed by the remote host
at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.g__ThrowSocketException|10_0(SocketError e) in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 85
at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 73
at Pipelines.Sockets.Unofficial.SocketConnection.d__65.MoveNext() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 59

**Comment by NickCraver** [comment]
This happens because the client can get in a bad state with a severed connection - please see #1120 which has a fix in queue of #1374. Closing this out just to consolidate the same issue down to 1 spot :)

**Comment by msx752** [comment]
this issue totally related with **Network Issue** on the Azure Cache, I don't know what is the reason(something should be trigger this) but we moved all services in the same network with the redis then that issue gone. redis client v1.2.6
