### ISSUE TITLE
No connection is available to service this operation: GET

### ISSUE THREAD

**Issue by prachibansal01** [StackExchange/StackExchange.Redis#1281]
Suddenly we started getting "No Connection available" exception while accessing redis. Following is the exception -
"No connection is available to service this operation: GET xxxxx; SocketClosed on xxxxx/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 69s ago, last-write: 69s ago, unanswered-write: 2630s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago: RedisConnectionException
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2027
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647
at CachingFramework.Redis.Providers.RedisCacheProvider.GetObject[T](String key)
at NetCoreUtilities.CachedUserObjectRedis.Get() in /codebuild/output/src803013914/src/NetCoreUtilities/CachedObjects/CachedUserObject.cs:line 63
at NetCoreUtilities.CachedUserObject.GetCachedUserObject(ElasticacheHelper elasticacheHelper, Int64 userID) in /codebuild/output/src803013914/src/NetCoreUtilities/CachedObjects/CachedUserObject.cs:line 82
at GetChildCategoriesAndAssets.Function.FunctionHandler(JObject input, ILambdaContext context) in /codebuild/output/src803013914/src/DIT Framework/users/GetChildCategoriesAndAssets.cs:line 54
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"

We are using .Net framework 4.5 and stackexchange.redis 1.2.1, we tried using latest version of stackexchange.redis, but its seems it does not support .Net framework 4.5. It would be good if you help us in fixing this.

**Comment by deanro** [comment]
There's a bunch of info in this thread which may help if you haven't already come across it.

https://github.com/StackExchange/StackExchange.Redis/issues/1120

Good luck

**Comment by NickCraver** [comment]
Closing this out to consolidate - overall I'd move to the latest 1.x release (1.2.6) for .NET Framework 4.5, but really recommend upgrading your target framework if at all possible. An additional fix for this will land in the 2.1.x line shortly from #1374.
