### ISSUE TITLE
Unable to connect to Cluster

### ISSUE THREAD

**Issue by Boskim0n0** [StackExchange/StackExchange.Redis#1337]
I created a cluster with 6 docker containers (3 masters, 3 slaves) and the command "cluster nodes" return this info

> 04b478416418c98af1766caffe9ee81594793f8f 127.0.0.1:7002@17002 master - 0 1580220503000 3 connected 10923-16383
> 93fde24d2c364bbe32a823a01debc324d13589d3 127.0.0.1:7003@17003 slave f7d949f78b89203373791add92d3a78c7de4e4b8 0 1580220503000 4 connected
> 42ffbe1dca17e0d7aba69118021e258ef6ace3ec 127.0.0.1:7001@17001 master - 0 1580220503000 2 connected 5461-10922
> b699c3bef06024b832bc63100596dd225b86a131 127.0.0.1:7005@17005 slave 04b478416418c98af1766caffe9ee81594793f8f 0 1580220503868 6 connected
> f7d949f78b89203373791add92d3a78c7de4e4b8 127.0.0.1:7000@17000 myself,master - 0 1580220501000 1 connected 0-5460
> 48029e886473c6dc302d85e73eef8c0a9beb58a6 127.0.0.1:7004@17004 slave 42ffbe1dca17e0d7aba69118021e258ef6ace3ec 0 1580220503365 5 connected

Im writting a .NET CORE 3.1 small app that tries to connect to the cluster and write a key and after that, get the same key from it. When i perform the connection i cant conntect to the cluster and the exception/log is this

> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 7s ago, v: 2.0.601.3402
>    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 963
>    at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 933
>    at RedisTest.Program.Main(String[] args) in C:\Users\fernando.vera\source\repos\RedisTest\RedisTest\Program.cs:line 27
> 

```
127.0.0.1:7000,keepAlive=0,allowAdmin=False

Connecting 127.0.0.1:7000/Interactive...
BeginConnect: 127.0.0.1:7000
1 unique nodes specified
Requesting tie-break from 127.0.0.1:7000 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767)
Finished awaiting tasks, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767)
127.0.0.1:7000 faulted: UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Waiting for tiebreakers...
All tasks are already complete
127.0.0.1:7000 failed to nominate (Faulted)
> UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
No masters detected
127.0.0.1:7000: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
127.0.0.1:7000: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:7000 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767)
connection failed: 127.0.0.1:7000 (Interactive, UnableToConnect): UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
connection failed: 127.0.0.1:7000 (Subscription, UnableToConnect): UnableToConnect on 127.0.0.1:7000/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Not all tasks completed cleanly (from ReconfigureAsync#1524, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)
127.0.0.1:7000 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)
Not all tasks completed cleanly (from NominatePreferredMaster#1761, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)
127.0.0.1:7000 failed to nominate (WaitingForActivation)
No masters detected
127.0.0.1:7000: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
127.0.0.1:7000: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:7000 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)
Finished awaiting tasks, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)
127.0.0.1:7000 faulted: UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 7s ago, v: 2.0.601.3402
Waiting for tiebreakers...
All tasks are already complete
127.0.0.1:7000 failed to nominate (Faulted)
> UnableToConnect on 127.0.0.1:7000/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 7s ago, v: 2.0.601.3402
No masters detected
127.0.0.1:7000: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
127.0.0.1:7000: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
```
If dont use a cluster, the program works correctly.

the program code is

```
var config = new ConfigurationOptions()
            {
                KeepAlive = 0,                
                AllowAdmin = false,
                EndPoints = { { "127.0.0.1", 7000 }}
            };

            var sr = new System.IO.StringWriter();
            try
            {
                ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(config, sr);
                IDatabase db = redis.GetDatabase();

                string value = "abcdefg";
                db.StringSet("mykey", value);

                string stored = db.StringGet("mykey");
                Console.WriteLine(stored); // writes: "abcdefg"
            }
            catch(Exception e){
                Console.WriteLine(sr.ToString());
            }
            Console.ReadKey();
```

**Comment by Boskim0n0** [comment]
The probem was my docker cluster configuration. Network type host is not supported in windows and i had to reconfig all nodes to portmapping.
