### ISSUE TITLE
BITFIELD SET command is not working

### ISSUE THREAD

**Issue by robinabganpat** [StackExchange/StackExchange.Redis#1369]
I'm currently trying to execute the following Redis command:
`BITFIELD c SET u4 #1222 15`

The code I'm using looks as follows:

>  int offset = 1222;
            int value = 15;
            db.Execute($"BITFIELD c SET u4 #{offset} {value}");

But I then receive the error:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Command 'BITFIELD c SET u4 #1020 5' exceeds library limit of 23 bytes')
   at StackExchange.Redis.CommandBytes..ctor(String value) in C:\projects\stackexchange-redis\src\StackExchange.Redis\CommandBytes.cs:line 109
   at StackExchange.Redis.CommandMap.GetBytes(String command) in C:\projects\stackexchange-redis\src\StackExchange.Redis\CommandMap.cs:line 181

When reducing the offset to a lower number it still does not work.
For example when running the following:
`BITFIELD c SET u4 #30 15`

I receive the error:

> StackExchange.Redis.RedisServerException: ERR unknown command 'BITFIELD C SET U4 #30 5'
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2258
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54

The thing that worries me about this, is that the command in the error message is all in uppercase, instead of the way I sent it.

Anyone has an idea about what I could be doing wrong?

**Comment by mgravell** [comment]
The parameters are all separate:

``` c#
db.Execute("BITFIELD", "c", "SET", "u4", $"#{offset}", value);
```

That said, there's two things we should do here:

- `BITFIELD` looks like it should have native support in the library
- we should remove the usage of `CommandBytes` when (if) we switch in RESPite - the RESPite layer already deals with this efficiently without imposing a length limit (although the *inlined* limit is a little smaller than `CommandBytes` allows)

**Comment by NickCraver** [comment]
@robinabganpat did the above help get you sorted?

**Comment by robinabganpat** [comment]
> @robinabganpat did the above help get you sorted?

Sorry for not getting back to you. Yes, that was what I was looking for.
