### ISSUE TITLE
GetSubscriber throwing exception when multiple ConnectionMultiplexers are used

### ISSUE THREAD

**Issue by AachoLoya** [StackExchange/StackExchange.Redis#1465]
I'm writing code so that we can distribute our data on different Redis servers e.g. Session Keys vs Pub/Sub vs Temp Caching.

Used Marc's Lazy initialization code for ConnectionMultiplexer and customized it as below:

```
public class RedisConn {
        private Lazy<ConnectionMultiplexer> LazyConn1 { get; set; }
        private Lazy<ConnectionMultiplexer> LazyConn2 { get; set; }
        private Lazy<ConnectionMultiplexer> LazyConn3 { get; set; }

        public RedisConn()
        {
            //Create Redis Connections
            LazyConn1 = new Lazy<ConnectionMultiplexer>(() => { return ConnectionMultiplexer.Connect(settings.RedisConn1Uri);  });
            LazyConn2 = new Lazy<ConnectionMultiplexer>(() => { return ConnectionMultiplexer.Connect(settings.RedisConn2Uri); });
            LazyConn3 = new Lazy<ConnectionMultiplexer>(() => { return ConnectionMultiplexer.Connect(settings.RedisConn3Uri); });
        }
}

```
**Currently, in dev environment, all Uri's point to same Redis server i.e. its same string**

The issue is when I call GetSubscriber() on Conn3. It throws excepton: _system.threading.threadabortexception_ with message _system error_

However: 
- When I call StringSet on Conn3, it works perfectly fine (even checked it using redis-cli). 
- When I call  GetSubscriber() on Conn1 that works perfectly fine as well. 

The code is identical, connection strings are identical, so what gives?

Environment: Asp.net core 3.1 on Windows using Redis for Windows (MSOpenTech release)

**Comment by AachoLoya** [comment]
![image](https://user-images.githubusercontent.com/20761070/118993009-958dc680-b99e-11eb-925c-62a2aed64daa.png)

`   at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__162.MoveNext() in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1948
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder~1.Start[TStateMachine](TStateMachine& stateMachine)
   at StackExchange.Redis.ConnectionMultiplexer.ReconfigureAsync(Boolean first, Boolean reconfigureAll, LogProxy log, EndPoint blame, String cause, Boolean publishReconfigure, CommandFlags publishReconfigureFlags)
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1148
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1032
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1015
   at MyProject.RedisDb.<.ctor>b__16_2() in C:\MyProject\Messaging\Redis\RedisDb.cs:line 31
   at System.Lazy~1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy~1.CreateValue()
   at System.Lazy~1.get_Value()`

**Comment by NickCraver** [comment]
I'm not sure what `LazyPubSubConn` is here, but it _appears_ to be an instance and I'm not sure of the lifetime of the class. If it's for the lifetime of the app, that's good - if many are created that's bad (multiplexers are meant to be re-used).

The thread abort exception is very odd...we wouldn't throw that (and it's deprecated in .NET Core+ - won't even compile in `net6.0` these days). The callstack doesn't seem complete though - either we're waiting in ReconfigureAsync _when somethine above us aborted_, or there's more to the stack. The way you'd look at this is in the `.Connect()` method pass a text writer and see what's happening in that connection. Is it possible there's a configuration issue there not allowing that connection to connect successfully? Stranger things like port exhaustion can be in play but in general: it looks like we're stuck waiting to connect for some reason.

**Comment by NickCraver** [comment]
Since explained above, going to close out to tidy up here.

**Comment by DanielStout5** [comment]
For anyone else arriving from Google: I wasn't actually seeing this with Redis at all, but I was seeing it in a different situation with `Lazy` and only in debug mode, and only when certain breakpoints are set. Seems like Lazy will throw ThreadAbortException when attempting to access the Value in debug mode sometimes.
