### ISSUE TITLE
Timeout on Azure web roles

### ISSUE THREAD

**Issue by jessieli-ad** [StackExchange/StackExchange.Redis#1466]
We are running in Azure as an Azure Web Role. We are seeing the timeout issue when we just upgraded to the latest version: 2.1.30. The timeout always happens when a new machine is added or a machine is restarted. When the timeout happens, it stays and doesn't go away. Sever load is smooth. The key size is less than 1KB. Could you help us to understand how to mitigate the timeout issue?

[StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 28000ms elapsed, timeout is 20000ms), command=GET, next: PTTL 1::Qjc5QTJBNDEtNUIzNS00QUJDLTk1Q0ItNzUyNUZFODAxRkI3Xzk2REM4NDU3LUNFNjEtNDFBMy04QzUxLTBENTdFRTI5OTM4MQ==, inst: 0, qu: 0, qs: 256, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: pub-prod-wcus.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: PublisherWebRole_IN_5, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=65,Free=32702,Min=4,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts);   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Online.Notifications.Azure.Cache.RedisCache.<>c__DisplayClass31_0.<<GetAsync>b__0>d.MoveNext() in X:\bt\1032313\repo\src\Dev\Notifications\Notifications.Azure\Cache\RedisCache.cs:line 1007
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Online.Notifications.Azure.Cache.RedisCache.<ExecuteRedisOperationAsync>d__39.MoveNext() in X:\bt\1032313\repo\src\Dev\Notifications\Notifications.Azure\Cache\RedisCache.cs:line 1339;Redis-Message PTTL+GET 1::MTA3RDA2RTAtRDMyOC00OTU1LTk2MEYtODYyRDE2OUMxMDNDXzlCNzQ4NTZGLUFFNEYtNDU0My05RUQ5LTE0OTk4MUUxQUYyQw==; Redis-Message-Next PTTL 1::Qjc5QTJBNDEtNUIzNS00QUJDLTk1Q0ItNzUyNUZFODAxRkI3Xzk2REM4NDU3LUNFNjEtNDFBMy04QzUxLTBENTdFRTI5OTM4MQ==; Redis-OpsSinceLastHeartbeat 0; Redis-Queue-Awaiting-Write 0; Redis-Queue-Awaiting-Response 256; Redis-Active-Writer False; Redis-Read-State ReadAsync; Redis-Write-State Idle; Redis-Inbound-Bytes 0; Redis-Server-Endpoint pub-prod-wcus.redis.cache.windows.net:6380; Redis-Multiplexer-Connects 1/1/0; Redis-Manager 10 of 10 available; Redis-Client-Name PublisherWebRole_IN_5; Redis-ThreadPool-IO-Completion (Busy=0,Free=1000,Min=4,Max=1000); Redis-ThreadPool-Workers (Busy=65,Free=32702,Min=4,Max=32767); Redis-Busy-Workers 65; Redis-Version 2.1.30.38891; redis-command PTTL+GET 1::MTA3RDA2RTAtRDMyOC00OTU1LTk2MEYtODYyRDE2OUMxMDNDXzlCNzQ4NTZGLUFFNEYtNDU0My05RUQ5LTE0OTk4MUUxQUYyQw==; request-sent-status Sent; redis-server pub-prod-wcus.redis.cache.windows.net:6380; ]

**Comment by DarthSonic** [comment]
Can confirm this. Everytime we restart our Azure App Service instance or auto scaling will start a new instance, we get Redis timeouts. Sometimes these exceptions lead to a further restart of the App Service.

> Timeout awaiting response (outbound=0KiB, inbound=2KiB, 1172ms elapsed, timeout is 1000ms), command=GET, next: GET ServiceProvider:GetDefaultServiceProviderAsync_0c919cce1e25eb3b82b24ca0ffb2c80d1358a7868edec4dfa4e27e97e76efb7d, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: linux-01.clevermatch.com:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: CM_WebApp, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=6,Free=32761,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by NickCraver** [comment]
Trying to get to all old issues here (sorry we have limited time since this is after-hours):

On the initial report: `(Busy=65,Free=32702,Min=4,Max=32767)` tells me the app thread pool is overloaded, likely synchronous tasks waiting. So what happens is all workers are occupied, commands can't complete, and exceed the timeout from not being handled in time. To investigate why this is happening, you'll want to grab a process dump when it happens to see what all those threads in the app are busy doing, locked on, waiting for, etc. - often it's 1 or 2 hot paths and very apparent once you get eyes on it. The real fix for this is going async, but until you're able to do that you'll probably want to up the timeout.

@DarthSonic On yours - there can be spikes for all cloud services and it looks like you've lowered the default 5 second timeout (remember: the _maximum_ upper bound) down to 1 second - seeing it exceeded due to a stall or overload anywhere between the worker and Redis isn't uncommon in complicated scenarios (bandwidth exhaustion, someone running a crazy script on Redis, etc.) - we recommend leaving the timeout higher than 1 second if more variable environments.

**Comment by NickCraver** [comment]
Main advice is above - going to close out to tidy up!
