### ISSUE TITLE
Session State fails using Redis in Net Core 2.2

### ISSUE THREAD

**Issue by ronaldo-o-reis** [StackExchange/StackExchange.Redis#1480]
A little context:

.Net Core 2.2 application
Deployed at AWS

Redis works well for caching data and Session State at development machine but when deployed to AWS serfver Redis works well for regular cached items however fail to store Session State.

The Exception:
```
Session cache read exception, Key:d506a408-7c45-2c06-064b-678e3122b932
System.TypeLoadException: Could not load type 'DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory' from assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1052
   at Microsoft.Extensions.Caching.Redis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(String key, Boolean getData)
   at Microsoft.AspNetCore.Session.DistributedSession.Load()`
```

The code at StartUp class:

```cs
	 public void ConfigureServices(IServiceCollection services)
		{

	...
            services.AddDistributedRedisCache(options =>
            {
                options.ConfigurationOptions = new StackExchange.Redis.ConfigurationOptions();
                options.ConfigurationOptions.EndPoints.Add(Configuration.GetValue<string>("RedisConnection:endPoint"), Convert.ToInt32(Configuration.GetValue<string>("RedisConnection:port")));
                options.InstanceName = $"{_env.EnvironmentName}:";
                options.ConfigurationOptions.Password = "";
                options.ConfigurationOptions.ClientName = "SafeRedisConnection";
                options.ConfigurationOptions.ConnectTimeout = 100000;
                options.ConfigurationOptions.KeepAlive = 4;
                options.ConfigurationOptions.AbortOnConnectFail = false;
                options.ConfigurationOptions.AllowAdmin = false;
                options.ConfigurationOptions.DefaultDatabase = Convert.ToInt32(Configuration.GetValue<string>("RedisConnection:defaultDb"));
            });


            services.AddSession(options =>
            {
			....
```

Any ideas?

**Comment by NickCraver** [comment]
The `DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory` is not related to this library, that's something external trying to inject. It may be a binding redirect issue (see https://nickcraver.com/blog/2020/02/11/binding-redirects/), or an incompatibility based on their assumptions, or something else. But overall, that's not an error we can possibly throw - it's in a library we do not control. I can't seem to find their code on GitHub, or I could offer some better advice. Definitely recommend filing this with whichever vendor that library is from...whatever they're doing to attach isn't compatible.

Sorry that's not a solution, but trying to get you to the right place!
