### ISSUE TITLE
StackExchangeRedis fails on Net Core 2.2

### ISSUE THREAD

**Issue by ronaldo-o-reis** [StackExchange/StackExchange.Redis#1523]
The application uses Net Core 2.2 and throws the following error at Test server. Notice that everything works at local machine.

Couldn't find any information regarding the package 'DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory'  over the  internet.

**Session cache read exception, Key:9619c27b-3f93-0e09-b921-613b5047243c Could not load type 'DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory' from assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'.**

**at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1134
at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefresh(String key, Boolean getData)
at Microsoft.AspNetCore.Session.DistributedSession.Load()**

Any ideas

**Comment by NickCraver** [comment]
This seems to be related to #1480 - I have no idea what that package is, but it's not us...something else is plugging into your pipe in a weird way and breaking. I'm sorry I don't have any advice here since I don't know _what it is_ - need to track down where it comes from and poke those authors.

**Comment by NickCraver** [comment]
Closing this out since it's an external issue :)
