### ISSUE TITLE
Object Disposed Exceptions

### ISSUE THREAD

**Issue by rakker91** [StackExchange/StackExchange.Redis#1579]
Version 2.1.58 running in Alpine Linux.  Dotnetcore 3.1.  AWS Elasticache redis.  Docker container on EKS.  We've received it both with reads and writes.  Here are some stack traces with identifying information obfuscated:

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'obfuscated-d4cf78d89-2ddbk'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor``1 processor, Object state, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2707
   at StackExchange.Redis.RedisDatabase.KeyExpireAsync(RedisKey key, Nullable``1 expiry, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 704
   at Obfuscated.EventHandling.Writers.Redis.RedisWriter.WriteEventAsync(IMessage message, Event event) in /src/Obfuscated/EventHandling/Writers/Redis/RedisWriter.cs:line 107
   at Obfuscated.EventHandling.EventHandler.HandleMessage(IMessage message, Event event) in /src/Obfuscated/EventHandling/EventHandler.cs:line 113`

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'obfuscated-6c6dffb4ff-jchwz'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor``1 processor, Object state, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2707
   at StackExchange.Redis.RedisDatabase.StringGetAsync(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2394
   at Obfuscated.Data.DataProvider.GetCurrentObfuscatedAsync(Obfuscated info) in /src/Obfuscated/Data/DataProvider.cs:line 115
   at Obfuscated.EventHandling.EventHandler.HandleMessage(IMessage message, Event event) in /src/Obfuscated/EventHandling/EventHandler.cs:line 133
   at Obfuscated.EventSource.OnEvent(Event event) in /builds/agent2/_work/205/s/Obfuscated/EventSource.cs:line 241
   at Obfuscated.Channels.Clients.ClientBase.OnEventReceived(Event event) in /builds/agent2/_work/205/s/Obfuscated/Channels/Clients/ClientBase.cs:line 79
   at Obfuscated.Channels.Clients.Kafka.KafkaPoller.NotifyClientsAsync(Event event) in /builds/agent2/_work/205/s/Obfuscated/Channels/Clients/Kafka/KafkaPoller.cs:line 359
   at Obfuscated.Channels.Clients.Kafka.KafkaPoller.Poll(CancellationToken token) in /builds/agent2/_work/205/s/Obfuscated/Channels/Clients/Kafka/KafkaPoller.cs:line 221
   at Obfuscated.Channels.Clients.Kafka.KafkaPoller.Run(CancellationToken token) in /builds/agent2/_work/205/s/Obfuscated/Channels/Clients/Kafka/KafkaPoller.cs:line 379`

**Comment by rakker91** [comment]
Note that the read operations are happening at a rate of about 200 to 1000 per second in this particular service.  I'm not sure how the ConnectionMultiplexer is getting disposed.

We're using Redlock.net as well (2.2.0) and we were initializing the RedLockFactory using the same ConnectionMultiPlexer that we're using for regular redis.  I wonder if Redlock has something to do with it.

I've changed our code to have Redlock.net configure itself with endpoints instead of reusing the connectionmultiplexer.  We'll see if that makes these go away.

**Comment by rakker91** [comment]
Didn't seem to help.  ConnectionMultiPlexer is still ending up disposed, even though we're not closing it.

**Comment by rakker91** [comment]
We found it!

Here's what's going on:  We are running multiple replicas in k8s with autoscaling (HPA).  What we discovered is that we were having autoscale events.

We're also using Kafka.  The kafka implementation forces multi-threading.  Nothing you can do about it.  What was going on is that on app shutdown, we were calling "CloseAsync" on our redis connections, which disposes the ConnectionMultiPlexer BEFORE we were shutting down the kafka client.

Because of this, we'd still have the kafka message pump happening which would result in attempts to use the redis client after we had called close.  And because we're handling very high volumes of data per instance, we were getting messages in between calling close on redis and close on the kafka client.  Classic race condition.

By shutting down the kafka message pump first and then calling close on the redis client, the object disposed exceptions went away.

Hopefully this will help anyone else who runs into this.

We looked at the code and the ONLY way you can get a disposed exception on ConnectionMultiplexor is if you call Close/CloseAsync or Dispose is called, so if you're running into this, look at race conditions first.
