### ISSUE TITLE
Unhandled Exception during Put / ScriptEvaluate method IOCP callback

### ISSUE THREAD

**Issue by yuvalpeled** [StackExchange/StackExchange.Redis#158]
We are using version 1.0.371 in our production environment.

We saw this exception in roles that perform sync 'Put' operations or run the following command:
m_redisDatabase.ScriptEvaluate("return redis.call('INFO', 'all')");

We got an unhandled exception which crashed our application:

Exception Type: Microsoft.Experience.CloudFx.Framework.CloudApplicationException
Additional Information:
--> Role Name: FrontEndWatchdog
--> Role Instance ID: FrontEndWatchdog_IN_1
Message: An unhandled exception has been detected in the current application domain RdRuntime. See below for details.
Target Site: 
Help Link: 
Source: 
HResult: -2146232832
# Exception Information Details:

Exception Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Target Site: Void BeginReading()
Help Link: 
Source: StackExchange.Redis
HResult: -2147467261
# Stack Trace Information Details: 

   at StackExchange.Redis.PhysicalConnection.BeginReading()
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* pOVERLAP); TraceSource 'WorkerRoleComponent' event

**Comment by sharaaU7** [comment]
Was there any fix proposed for this? we are facing the same issue.

**Comment by NickCraver** [comment]
There were some changes here lately, are you still seeing this on the current version?

**Comment by Malediction** [comment]
I'm encountering this also in 1.1.603, .NET 4.6.2:

NullReferenceException
Stack trace:
```
StackExchange.Redis.dll!StackExchange.Redis.PhysicalConnection.BeginReading() Line 705	C#
StackExchange.Redis.dll!StackExchange.Redis.PhysicalConnection.StackExchange.Redis.ISocketCallback.StartReading() Line 1105	C#
StackExchange.Redis.dll!StackExchange.Redis.SocketManager.EndConnectImpl(System.IAsyncResult ar, StackExchange.Redis.ConnectionMultiplexer multiplexer, System.IO.TextWriter log, System.Tuple<System.Net.Sockets.Socket, StackExchange.Redis.ISocketCallback> tuple) Line 333	C#
StackExchange.Redis.dll!StackExchange.Redis.SocketManager.BeginConnect.AnonymousMethod__1(System.IAsyncResult ar) Line 209	C#
StackExchange.Redis.dll!StackExchange.Redis.CompletionTypeHelper.RunWithCompletionType.AnonymousMethod__0(System.IAsyncResult ar) Line 361	C#
System.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken)	Unknown
```

Locals at deepest stack frame:
```
$exception	{"Object reference not set to an instance of an object."} System.NullReferenceException
this	{Interactive#1@removed-from-public-bug-report.redis.cache.windows.net:6380}	StackExchange.Redis.PhysicalConnection
keepReading	false	bool
space	512	int
result	null	System.IAsyncResult
```

**Comment by NickCraver** [comment]
This should be fixed in later releases, @Malediction are you still seeing this?

**Comment by Malediction** [comment]
No longer repros for me, thanks for following up! :)
