### ISSUE TITLE
No connection is active/available to service this operation: EXEC

### ISSUE THREAD

**Issue by jessieli-ad** [StackExchange/StackExchange.Redis#1583]
We are on the latest version: 2.1.58. We are seeing this error consistently in our low volume traffic region (canary). We don't see this in our PROD. This canary region has C3 Standard scale (6 GB Cache). Are you able to tell us what is wrong in this Canary region from the below stack?

> [RedisCache::ExecuteRedisOperation] Redis operation failed: ErrorId=Connection Exception: [StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: EXEC; UnableToConnect on pub-cny-cuseuap.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 10s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.1.58.34321, mc: 1/1/0, mgr: 10 of 10 available, clientName: CD1PEPF00000518, IOCP: (Busy=0,Free=1000,Min=400,Max=1000), WORKER: (Busy=2,Free=32765,Min=200,Max=32767), v: 2.1.58.34321;
```
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2769
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Online.Notifications.Azure.Cache.RedisCache.<>c__DisplayClass24_0.<<SetIfKeyNotExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Online.Notifications.Azure.Cache.RedisCache.<ExecuteRedisOperationAsync>d__39.MoveNext();Redis-Multiplexer-Connects 1/1/0; Redis-Manager 10 of 10 available; Redis-Client-Name CD1PEPF00000518; Redis-ThreadPool-IO-Completion (Busy=0,Free=1000,Min=400,Max=1000); Redis-ThreadPool-Workers (Busy=2,Free=32765,Min=200,Max=32767); Redis-Busy-Workers 2; Redis-Version 2.1.58.34321; redis-command EXEC; request-sent-status WaitingToBeSent; [StackExchange.Redis.RedisConnectionException: UnableToConnect on pub-cny-cuseuap.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 10s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.1.58.34321;;Redis-FailureType UnableToConnect; Redis-EndPoint pub-cny-cuseuap.cache.windows.net:6380; Redis-Origin BeginConnectAsync; Redis-Outstanding-Responses 0; Redis-Last-Read 0s ago; Redis-Last-Write 0s ago; Redis-Keep-Alive 10s; Redis-Previous-Physical-State Connecting; Redis-Manager 10 of 10 available; Redis-Last-Heartbeat never; Redis-Last-Global-Heartbeat 0s ago; Redis-Version 2.1.58.34321; ]][X:\bt\1028203\repo\src\dev\Notifications\Notifications.Azure\Cache\RedisCache.cs(1390)]
```

**Comment by NickCraver** [comment]
What does "consistently" mean here? How often? And can you provide your connection string, sans secrets? Azure does maintenance and swaps instances when patching for instance, so some amount of them isn't necessarily abnormal.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
