### ISSUE TITLE
NRedissearch issue with the search for "bond"

### ISSUE THREAD

**Issue by elan-echambon** [StackExchange/StackExchange.Redis#1617]
Hi,

I see a very weird behaviour with the C# client when creating a suggestion and then looking for it. Here is the code : 

                
` // Creating the client
var client = new NRediSearch.Client("redisearch:error", /* IDatabase */);
// Adding the suggestion
                var nameBuilder = new Suggestion.SuggestionBuilder();
                nameBuilder.String("bond");
                nameBuilder.Score(0.5);
                nameBuilder.Payload("test");
                client.AddSuggestion(nameBuilder.Build());
// Querying it
var optionsBuilder = new SuggestionOptions.SuggestionOptionsBuilder();
                optionsBuilder.With(SuggestionOptions.WithOptions.PayloadsAndScores);
                optionsBuilder.Max(10);
                optionsBuilder.Fuzzy();
                var suggestionsOptions = optionsBuilder.Build();
                var res = client.GetSuggestions("bond", suggestionsOptions);
`

Am i missing something obvious or is it a bug ? Also if you replace "bond" by something else, it does work sometimes and sometimes doesn't.

Thanks

StackTrace:
StackExchange.Redis.RedisCommandException: Missing required fields:  score not within range: 2147483648
   at NRediSearch.Suggestion.SuggestionBuilder.Build() in /_/src/NRediSearch/Suggestion.cs:line 102
   at NRediSearch.Client.GetSuggestionsWithPayloadAndScores(RedisResult[] results) in /_/src/NRediSearch/Client.cs:line 1271
   at NRediSearch.Client.GetSuggestions(String prefix, SuggestionOptions options) in /_/src/NRediSearch/Client.cs:line 813
   at Cobra.Timeseries.TestClient.RedisSearchError.Run() in C:\repositories\cobra\Cobra\Cobra.Timeseries.TestClient\RedisSearchError.cs:line 30

**Comment by mgravell** [comment]
I observed something similar when testing the RediSearch 2 changes (are you using RediSearch 2 by any chance?) - see [this fix here](https://github.com/StackExchange/StackExchange.Redis/pull/1544/files#diff-76ce148d17f641b61da7ab28467732ff69e4f0306ac6b9f0e22a47b368f95470L92-L95). I had been hoping for some feedback from @gkorland on some (unrelated) questions, but I may have to just give up on that and review for final merge

**Comment by elan-echambon** [comment]
Hi Marc,

Thanks a lot for your quick answer. I'm using RediSearch version 2.0.1 (running on Redis 6.0.9) on the server and the C# client is version 2.1.30 (latest available).
Looking at the fix, it does look like it would fix the issue - I'm happy to test this usecase once merged and released.

Thanks

**Comment by elan-echambon** [comment]
Hi @mgravell @gkorland , did you have the time to look into this? Would be good to merge if everyone is happy
