### ISSUE TITLE
Having a Redis Timeout/Replica issue

### ISSUE THREAD

**Issue by Kevman95** [StackExchange/StackExchange.Redis#1642]
We are currently having a few issues with our program with Redis that happen and occur randomly. We do not understand what is going on.

The code is open source as well if anyone wants to tag in and help on these two repos:

https://github.com/pythonology/BeatTogether.Core

https://github.com/pythonology/BeatTogether.MasterServer/tree/feature/dedicated-servers (using the branch at the moment for dev purposes)

```
2020-12-10 03:22:17.829 +00:00 [ERR] An error occurred while handling message (MessageType='BroadcastServerStatusRequest').
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_dce2ce9e149bc775618a47cd07eca24d80a33664): @user_script:4: @user_script: 4: -READONLY You can't write against a read only replica.
   at BeatTogether.MasterServer.Data.Implementations.Repositories.ServerRepository.AddServer(Server server) in /app/BeatTogether.MasterServer.Data/Implementations/Repositories/ServerRepository.cs:line 80
   at BeatTogether.MasterServer.Kernel.Implementations.UserService.BroadcastServerStatus(MasterServerSession session, BroadcastServerStatusRequest request) in /app/BeatTogether.MasterServer.Kernel/Implementations/UserService.cs:line 156
   at BeatTogether.Core.Messaging.Implementations.BaseMessageHandler.<>c__DisplayClass6_0`2.<<Register>b__0>d.MoveNext()
--- End of stack trace from previous location --
```

and

```
2020-12-10 06:20:23.198 +00:00 [ERR] An error occurred while handling message (MessageType='BroadcastServerStatusRequest').
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: EVAL, mc: 1/1/0, mgr: 10 of 10 available, clientName: master-server, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1024,Max=32767), v: 2.2.4.27433   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2760
--- End of stack trace from previous location ---
   at BeatTogether.MasterServer.Data.Implementations.Repositories.ServerRepository.AddServer(Server server) in /app/BeatTogether.MasterServer.Data/Implementations/Repositories/ServerRepository.cs:line 80
   at BeatTogether.MasterServer.Kernel.Implementations.UserService.BroadcastServerStatus(MasterServerSession session, BroadcastServerStatusRequest request) in /app/BeatTogether.MasterServer.Kernel/Implementations/UserService.cs:line 156
   at BeatTogether.Core.Messaging.Implementations.BaseMessageHandler.<>c__DisplayClass6_0`2.<<Register>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at BeatTogether.Core.Messaging.Implementations.BaseMessageSource.<>c__DisplayClass15_0.<<Signal>b__0>d.MoveNext()
```

Our redis instance doesn't have slaves, only a master and its one instance on the same machine.

Any help is greatly appreciated. Thanks.

**Comment by NickCraver** [comment]
What is the environment here? Is it a cloud install/cache, or are you managing it yourself? It seems like we're getting confusing _thinking_ it's a replica, so trying to understand the topology here.

**Comment by NickCraver** [comment]
Going to close this out to tidy up - for anyone hitting this: @mgravell and I are taking a look at READONLY responses in general soon as a traffic to re-evaluate server state potentially proactively (when topology changes and we haven't realized it yet). In this case it may _appear_ as a single server but we did get a READONLY response back from it (so maybe it's more under the covers of that endpoint). Regardless, we're looking at this as a reconfigure trigger in general.
