### ISSUE TITLE
Frequent - "Reader is not allowed after reader is completed" errors and timeout errors after migrating to StackExchange.Redis v2.0.601 from v1.2.6

### ISSUE THREAD

**Issue by Kdeenada** [StackExchange/StackExchange.Redis#1651]
We are getting frequent - "Reader is not allowed after reader is completed" errors and timeout errors after migrating to StackExchange.Redis v2.0.601 from v1.2.6.
We are using 2 Azure Redis Cache services both on P5 tier. Below are the usage stats for them when issue occurs,

![image](https://user-images.githubusercontent.com/76518070/102988940-cb876580-453a-11eb-82ac-a55bb3e8eee4.png)

We reached out to Microsoft support team and they are suggesting to create in this forum for StackExchange.Redis - https://github.com/StackExchange/StackExchange.Redis/issues. 

This is error which we are getting,
System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at StackExchange.Redis.PhysicalConnection.<ReadFromPipe>d__110.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ....RedisCache`1.<>c__DisplayClass13_0.<<GetAsync>b__0>d.MoveNext() 
   in C:\....\RedisCache.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ....<ExecuteAzureRedisCacheRetryAsync>d__2.MoveNext
   in C:\....\RetryExtensions.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ....RedisCache`1.<GetAsync>d__13.MoveNext()
   in C:\....\RedisCache.cs:line 109

Could someone help us in addressing the issue.,

**Comment by NickCraver** [comment]
There have been several fixes here - have you tried a more recent version? e.g. can you reproduce this with 2.2.4?

**Comment by Kdeenada** [comment]
No not tried yet. We are planning to do it.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
