### ISSUE TITLE
Intermittent timeouts: Timeout performing GET <key>

### ISSUE THREAD

**Issue by svantreeck** [StackExchange/StackExchange.Redis#168]
We are using StackExchange.Redis 1.0.394, and occasionally out ConnectionMultiplexer will get things stuck and start queueing a bunch of requests and they don't seem to recover unless we recycle the app that is consuming Redis.  Any help would be appreciated.

Our ConnectionMultiplexer is initialized with this: ConnectionMultiplexer.Connect("server:6379,server:6380");

System.TimeoutException: Timeout performing MGET, inst: 11, mgr: ExecuteSelect, queue: 109990, qu=0, qs=109990, qc=0, wr=0/0, in=8192/0
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)

**Comment by svantreeck** [comment]
Also, oddly enough, when I look at SLOWLOG on the server, I see the longest running command is 15600 (I think micro seconds), which should be underneath the default timeout.  The Redis server and MT servers are located in the same data center, so I don't expect much in terms of latency between the two.

**Comment by svantreeck** [comment]
In looking at a memory dump of the scenario, I can see that the failureMessage is set to "UnableToResolvePhysicalConnection on PING", so it looks like at some point there must have been a network problem preventing communication.  I'm not calling Ping from code, so my best guess is this is somehow related to the heartbeat activity, and then something is basically not restoring itself.

  So I guess from there, I've got two questions...
   * Is there anything that would help from a debugging standpoint that I could find in a memory dump of this scenario to help diagnose further?
   * If this reoccurred, is there anything I can call on the ConnectionMultiplexer to reset itself, or is the best solution recycling the application to have it start with a fresh state?

Thanks

**Comment by smithkl42** [comment]
I'm having a similar problem. I've got thousands of these error messages showing up in my logs:

`Payboard.Common.Cache.SimpleCacheBase|Experienced 93000 connection errors with Redis cache; last error = No connection is available to service this operation: GET IList<AtsOrganizationEventSummaryByCookie>.4306.www-DETAIL-night-sky-photos-may-DETAIL-GET.2/20/2015 12:00:00 AM.2/28/2015 12:00:00 AM `

They continue until the app in question is recycled. 

I'm using 1.0.316.0.

I haven't been able to debug this very well yet, as it only seems to happen in prod, often only after the app in question has been running for several hours.

Any suggestions about how to best handle this?

**Comment by shb98** [comment]
Same issue, +1. Some times it recovered automatically but sometimes it'll never recover.

**Comment by mickdelaney** [comment]
+1 Having this error today. Had to recycle our app domain to get rid of it.

**Comment by smithkl42** [comment]
See also my answer on SO: http://stackoverflow.com/questions/24922782/recovering-from-redis-connectivity-loss/25146711#25146711. I had to implement my own wrapper around the StackExchange.Redis client's connection methods, because there were simply too many times that the SE.R client would disconnect and then never reconnect. I don't know what's going on under the hood: I know that it's supposed to handle the sort of thing cleanly. But at least the last time I tried under a heavy load in production, it most certainly did not. And the wrapper I reference in that question *does* fix it.
