### ISSUE TITLE
Stackexchange Redis Client causes threadpool starvation / IO issues at scale

### ISSUE THREAD

**Issue by alanwales** [StackExchange/StackExchange.Redis#1694]
We have been profiling idiomatic usage of StackExchange Redis Client and have encountered a number of thread starvation issues with it when running at scale. We have since switched to ServiceStack.Redis and have no more issues, however it may be beneficial to investigate these issues to prevent others from encountering very difficult to debug network latency issues that are actually coming from IO / thread starvation. We believe in particular that the RedisDatabse class is eliding the async keyword or is somehow less than optimal when doing async/await operations.

Attached is a minimal reproduction:

[redis.zip](https://github.com/StackExchange/StackExchange.Redis/files/6012952/redis.zip)

When calling the home endpoint we see the following in the debugger:

Ben.Diagnostics.BlockingMonitor: Warning: Blocking method has been invoked and blocked, this can lead to threadpool starvation.
   at System.Threading.Tasks.TplEventSource.TaskWaitBegin(Int32 OriginatingTaskSchedulerID, Int32 OriginatingTaskID, Int32 TaskID, TaskWaitBehavior Behavior, Int32 ContinueWithTaskID)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log)
   at StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager.<EmitConnection>b__7_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager.GetConnection()
   at StackExchange.Redis.Extensions.Core.Implementations.RedisDatabase.get_Database()
   at StackExchange.Redis.Extensions.Core.Implementations.RedisDatabase.AddAsync[T](String key, T value, When when, CommandFlags flag)
   at Redistest.Controllers.HomeController.Home()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Redistest.Controllers.HomeController.Home()
   at lambda_method7(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAwaitedAsync()
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Ben.Diagnostics.BlockingDetectionMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Ben.Diagnostics.BlockingDetectionMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.OnConnectionAsync(ConnectionContext connectionContext)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by xaclincoln** [comment]
Hi. The StackExchange.Redis.Extensions.AspNetCore library wrap the StackExchange.Redis for a connection polling purpose, there should not be serious starvation problems after the very first several times connection (since the connection will be reused).  You can start a dedicated a thread to initialize several ready to use connections on application startup to avoid the problem, but that would require modify source of  the StackExchange.Redis.Extensions.AspNetCore library.  So in my view, this should be the problem of StackExchange.Redis.

**Comment by NickCraver** [comment]
Do you have more info on what you think is improperly blocking here? If the wrapper library is calling `.Connect()` and not `.ConnectAsync()`...they're getting, intentionally, the blocking version.

**Comment by yapaxi** [comment]
I am investigating similar issue with some [public best practices code](https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f). 

The problem in this discussion looks similar and from the history of [RedisCacheConnectionPoolManager](https://github.com/imperugo/StackExchange.Redis.Extensions/blob/master/src/core/StackExchange.Redis.Extensions.Core/Implementations/RedisCacheConnectionPoolManager.cs) I see that Lazy with blocking IO is now replaced with constructor using static lock but still with blocking IO inside. 

Using constructor which is inevitably called synchronousely in DI asks for as many troubles as does Lazy<T>-based implementation. Both implementations are dangerous and should be avoided.

**Comment by mgravell** [comment]
Note that RedisCacheConnectionPoolManager is nothing to do with us, and we
offer no comment or guidance on it.

**Comment by NickCraver** [comment]
I'm going to close this one out since answers above are the current state: if you want async and non-blocking, call the async path :)

**Comment by sudoskyza** [comment]
> Do you have more info on what you think is improperly blocking here? If the wrapper library is calling `.Connect()` and not `.ConnectAsync()`...they're getting, intentionally, the blocking version.

@NickCraver we are using the below class as our centralized connection manager and simply using RedisConnManager.Connection all over in our API in async methods for get/set of key/value pairs. The question I have is will the fact that we are using "Connect()" instead of "ConnectAsync()" really have an impact on threading/performance? It seems that when our API is idle in Azure with 0 requests coming in, our handle count is increasing gradually until a request comes in and GC runs. not sure if that would be related to using Connect instead of ConnectAsync?

` public static class RedisConnManager
    {
        private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            ConnectionMultiplexer.SetFeatureFlag("preventthreadtheft", true);
            var connectionMultiplexer = ConnectionMultiplexer.Connect(ConfigurationManager.ConnectionStrings["GeoRedisConnection"].ConnectionString);

            return connectionMultiplexer;
        });



        private static Lazy<IDistributedLockFactory> lockFactory = new Lazy<IDistributedLockFactory>(() =>
        {
            var multiplexers = new List<RedLockMultiplexer>
            {
                Connection
            };
            var redlockFactory = RedLockFactory.Create(multiplexers);

            return redlockFactory;
        });

        public static ConnectionMultiplexer Connection
        {
            get
            {
                return lazyConnection.Value;
            }
        }

        public static IRedLock GetLockByCount(string resource, int counter, System.TimeSpan expiryTime, CancellationToken? cancellationToken = null)
        {
            for (int i = 1; i <= counter; i++)
            {
                var redLock = LockFactory.CreateLock($"{resource}:{i}", expiryTime);

                if (redLock.IsAcquired)
                {
                    return redLock;
                }
            }

            return null;
        }

        public static IRedLock GetLockByCount(string resource, int counter, System.TimeSpan expiryTime, System.TimeSpan waitTime, System.TimeSpan retryTime, CancellationToken? cancellationToken = null)
        {
            for (int i = 1; i <= counter; i++)
            {
                var redLock = LockFactory.CreateLock($"{resource}:{i}", expiryTime, waitTime, retryTime);

                if (redLock.IsAcquired)
                {
                    return redLock;
                }
            }

            return null;
        }

        public static IDistributedLockFactory LockFactory
        {
            get
            {
                return lockFactory.Value;
            }
        }
    }`

**Comment by sudoskyza** [comment]
> > Do you have more info on what you think is improperly blocking here? If the wrapper library is calling `.Connect()` and not `.ConnectAsync()`...they're getting, intentionally, the blocking version.
> 
> @NickCraver we are using the below class as our centralized connection manager and simply using RedisConnManager.Connection all over in our API in async methods for get/set of key/value pairs. The question I have is will the fact that we are using "Connect()" instead of "ConnectAsync()" really have an impact on threading/performance? It seems that when our API is idle in Azure with 0 requests coming in, our handle count is increasing gradually until a request comes in and GC runs. not sure if that would be related to using Connect instead of ConnectAsync?
> 
> ` public static class RedisConnManager { private static Lazy lazyConnection = new Lazy(() => { ConnectionMultiplexer.SetFeatureFlag("preventthreadtheft", true); var connectionMultiplexer = ConnectionMultiplexer.Connect(ConfigurationManager.ConnectionStrings["GeoRedisConnection"].ConnectionString);
> 
> ```
>         return connectionMultiplexer;
>     });
> 
> 
> 
>     private static Lazy<IDistributedLockFactory> lockFactory = new Lazy<IDistributedLockFactory>(() =>
>     {
>         var multiplexers = new List<RedLockMultiplexer>
>         {
>             Connection
>         };
>         var redlockFactory = RedLockFactory.Create(multiplexers);
> 
>         return redlockFactory;
>     });
> 
>     public static ConnectionMultiplexer Connection
>     {
>         get
>         {
>             return lazyConnection.Value;
>         }
>     }
> 
>     public static IRedLock GetLockByCount(string resource, int counter, System.TimeSpan expiryTime, CancellationToken? cancellationToken = null)
>     {
>         for (int i = 1; i <= counter; i++)
>         {
>             var redLock = LockFactory.CreateLock($"{resource}:{i}", expiryTime);
> 
>             if (redLock.IsAcquired)
>             {
>                 return redLock;
>             }
>         }
> 
>         return null;
>     }
> 
>     public static IRedLock GetLockByCount(string resource, int counter, System.TimeSpan expiryTime, System.TimeSpan waitTime, System.TimeSpan retryTime, CancellationToken? cancellationToken = null)
>     {
>         for (int i = 1; i <= counter; i++)
>         {
>             var redLock = LockFactory.CreateLock($"{resource}:{i}", expiryTime, waitTime, retryTime);
> 
>             if (redLock.IsAcquired)
>             {
>                 return redLock;
>             }
>         }
> 
>         return null;
>     }
> 
>     public static IDistributedLockFactory LockFactory
>     {
>         get
>         {
>             return lockFactory.Value;
>         }
>     }
> }`
> ```

Just for reference: 
![image](https://github.com/StackExchange/StackExchange.Redis/assets/71274713/4a2ac757-6906-4bea-a1ce-d1c8bf62ff1c)
