### ISSUE TITLE
CollectionMultiplexer.servers - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Vikakuma** [StackExchange/StackExchange.Redis#1727]
I m seeing this exception (below) for ConnectionMultiplexer.servers on very few app nodes.
Probably there is some condition where MarkServerEndpointsForReplicationRoleRefresh() is called while the collection (servers) was modified.

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Hashtable.HashtableEnumerator.MoveNext()
   at StackExchange.Redis.ConnectionMultiplexer.MarkServerEndpointsForReplicationRoleRefresh()
   at StackExchange.Redis.PhysicalBridge.OnDisconnected(ConnectionFailureType failureType, PhysicalConnection connection, Boolean& isCurrent, State& oldState)
   at StackExchange.Redis.PhysicalConnection.RecordConnectionFailed(ConnectionFailureType failureType, Exception innerException, String origin, Boolean isInitialConnect, IDuplexPipe connectingPipe)
   at StackExchange.Redis.PhysicalBridge.ResetNonConnected()
   at StackExchange.Redis.ServerEndPoint.ResetNonConnected()
   at StackExchange.Redis.ConnectionMultiplexer.ResetAllNonConnected()
   at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__162.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log)
   at Microsoft.Online.CacheService.Client.Redis.RedisConnection.InitializeMultiplexer(ConfigurationOptions configurationOptions)

**Comment by mgravell** [comment]
Sounds like an interesting concurrency bug - needs fixing, thanks.

**Comment by deepakverma** [comment]
#1735 should potentially fix this.

**Comment by Vikakuma** [comment]
Thanks you @deepakverma for the fix.
@NickCraver can we have a new NuGet release for this fix. Thanks.
