### ISSUE TITLE
System.InvalidProgramException 

### ISSUE THREAD

**Issue by ashwaniverma** [StackExchange/StackExchange.Redis#1737]
We have constantly getting an issue where Application get stuck in the state with the Invalid Program Exception.

We get this issue while deleting something from redis or getting a key.

Stack trace looks like this:
```
Exception:
  Type:    System.InvalidProgramException
  Message: Common Language Runtime detected an invalid program.
  Source:  StackExchange.Redis
  Stack Trace: 
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.KeyDeleteAsync(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 628
   at Syncplicity.Common.Server.Infrastructure.Caching.Redis.RedisCache.<KeyDeleteAsync>d__7.MoveNext() in C:\Jenkins\workspace\platform\platform.deploy\server\syncp-common-server\Infrastructure\Caching\Redis\RedisCache.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```
   
```
   Exception:
     Type:    System.InvalidProgramException
     Message: Common Language Runtime detected an invalid program.
     Source:  StackExchange.Redis
     Stack Trace: 
      at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
      at StackExchange.Redis.RedisDatabase.HashGetAsync(RedisKey key, RedisValue hashField, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 342
      at Syncplicity.Common.Server.Infrastructure.Caching.Redis.RedisCache.<HashGetAsync>d__16.MoveNext() in C:\Jenkins\workspace\platform\platform.deploy\server\syncp-common-server\Infrastructure\Caching\Redis\RedisCache.cs:line 204
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

Once Application is into this state the error remains consistent unless we restart the iis/app pool.

I can't see any obvious precursor in our application logs before the exception starts, and it stops when the instance is terminated and the log stream from the affected instance ends. Digging around for reasons for this kind of exception seemed suggest dynamic IL generation. Internal investigation revealed that the issue happens during startup time only. Something goes wrong in startup which causes service to be this state,

The application runs under .NET Framework 4.7.2  in IIS on Windows Server 2012 R2 and we're using StackExchange.Redis using the StackExchange.Redis NuGet package at version 2.2.4.

Let me know if you need any more details.

**Comment by mgravell** [comment]
Well that is very odd! I'll need to dig :/

**Comment by NickCraver** [comment]
Is it possible you are running the app in 32-bit mode in IIS, but a 64-bit-only DLL is present?

**Comment by mgravell** [comment]
I've done a quick check, and we don't have any ref-emit code in the library; there is a *tiny* bit of ref-emit in one of the libs we use for IO, but that looks legit; can you clarify your environment more? you say net472, but Nick has a point: is this 32-bit mode by any chance? (just so I can try to repro)

**Comment by mgravell** [comment]
In a minimal test, this works fine on .NET Framework 4.7.2 in both x86 and x64 mode, using library version 2.2.4:

``` c#
using System;

Console.WriteLine(IntPtr.Size);

using var mux = StackExchange.Redis.ConnectionMultiplexer.Connect("127.0.0.1:6379");
var db = mux.GetDatabase();
await db.KeyDeleteAsync("foo");
await db.StringIncrementAsync("foo");
await db.StringIncrementAsync("foo", 4);
var val = (int)await db.StringGetAsync("foo");
Console.WriteLine(val);
```

with csproj:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>9</LangVersion>
        <!-- or x64 -->
        <PlatformTarget>x86</PlatformTarget>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" Version="2.2.4" />
    </ItemGroup>
</Project>
```

Fundamentally, the first thing we need here is some kind of repro, and: I'm struggling to do that; it seems to "just work". If there's anything you can do to help us isolate that, it would help

**Comment by mgravell** [comment]
Note: I have *not* specifically run the above test on 2012 r2

**Comment by ashwaniverma** [comment]
We are using 64 bit mode. Only other thing we can think of is that this is some how related to using AppDynamics agent on our server.

**Comment by NickCraver** [comment]
I'm not sure how to help further here - this isn't us since we're just not specific, but an injected DLL that is trying to load on first connection: yes absolutely possible. An agent like AppDynamic, Application Insights, etc. that is sometimes there (or sometimes loaded, importantly) and is platform specific is exactly the type of thing I'd be looking for here.

I'm going to close this out to tidy up but very happy to reopen and advise further if we can help based on any more info.
