### ISSUE TITLE
GetSentinelMasterConnection (Flakey test because of race bug)

### ISSUE THREAD

**Issue by TimLovellSmith** [StackExchange/StackExchange.Redis#1742]
While running tests locally it seems like they uncovered a race condition between the calls to GetSentinelMasterConnection() and InitializeSentinel():

>[xUnit.net 00:00:22.95]     Sentinel.SentinelMastersTest [FAIL]
  Failed Sentinel.SentinelMastersTest [1 ms]
  Error Message:
   System.ArgumentNullException : Value cannot be null.
  Stack Trace:
     at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Microsoft.Caching.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2565
   at Microsoft.Caching.Redis.Tests.Sentinel..ctor(ITestOutputHelper output) in C:\repo\AzureStackExchange.Redis\tests\StackExchange.Redis.Tests\Sentinel.cs:line 41
  Standard Output Messages:
 Running under .NET Framework 4.8.4300.0 (4.0.30319.42000)

**Comment by TimLovellSmith** [comment]
...or perhaps it is just that the ConnectionMultiplexer never gets its server type setup correctly in some failure codepath.?

>if (muxer.ServerSelectionStrategy.ServerType == ServerType.Sentinel)
                    {
                        // Initialize the Sentinel handlers
                        muxer.InitializeSentinel(logProxy);
                    }

**Comment by NickCraver** [comment]
I think I resolved this in #1762 FWIW, noticed the same independently when running tests :)
