### ISSUE TITLE
Logical bug related to the reordering issue - SendTracer PING in tiebreak happens before AUTH

### ISSUE THREAD

**Issue by TimLovellSmith** [StackExchange/StackExchange.Redis#1759]
From the call today, Nick and I feel this code has a logical problem that it doesn't actually wait to send the tracer (` available[i] = server.SendTracer(log);`) until after the connection is authenticated, which was why the ordering bugfix broke tests.

Repro branch:
repro1759

Test scenario:
C:\repo\StackExchange.Redis>dotnet test ".\Build.csproj" -c Release --no-build --logger trx --filter TestMultiWithTiebreak

`ConnectionMultiplexer.ReconfigureAsync`
```
                        for (int i = 0; i < available.Length; i++)
                        {
                            Trace("Testing: " + Format.ToString(endpoints[i]));
                            var server = GetServerEndPoint(endpoints[i]);
                            //server.ReportNextFailure();
                            servers[i] = server;
                            if (reconfigureAll && server.IsConnected)
                            {
                                log?.WriteLine($"Refreshing {Format.ToString(server.EndPoint)}...");
                                // note that these will be processed synchronously *BEFORE* the tracer is processed,
                                // so we know that the configuration will be up to date if we see the tracer
                                server.AutoConfigure(null);
                            }
                            log?.WriteLine($"Server endpoint {server.EndPoint} is in {server.ConnectionState}");
                            available[i] = server.SendTracer(log);
                            if (useTieBreakers)
                            {
                                log?.WriteLine($"Requesting tie-break from {Format.ToString(server.EndPoint)} > {RawConfig.TieBreaker}...");
                                Message msg = Message.Create(0, flags, RedisCommand.GET, tieBreakerKey);
                                msg.SetInternalCall();
                                msg = LoggingMessage.Create(log, msg);
                                tieBreakers[i] = server.WriteDirectAsync(msg, ResultProcessor.String);
                            }
                        }
```

 Failed MultiMaster.TestMultiWithTiebreak(a: null, b: "127.0.0.1:6381", elected: "127.0.0.1:6381") [51 ms]
  Error Message:
   failed to nominate
Expected: False
Actual:   True
  Stack Trace:
     at StackExchange.Redis.Tests.MultiMaster.TestMultiWithTiebreak(String a, String b, String elected) in C:\repo\StackExchange.Redis\tests\StackExchange.Redis.Tests\MultiMaster.cs:line 77
  Standard Output Messages:
 Running under .NET Core 3.1.15 (3.1.15)
   Running on: Microsoft Windows 10.0.19043
 17:01:26.485: 17:01:26.485: Connect took: 14ms
 17:01:26.487: 127.0.0.1:6379,127.0.0.1:6381,name=TestMultiWithTiebreak,password=*****,tiebreaker=__tie__
 Connecting 127.0.0.1:6379/Interactive...
 BeginConnect: 127.0.0.1:6379
 Connected Interactive/127.0.0.1:6379
 Server handshake
 Authenticating (password) to endpoint 127.0.0.1:6379
 Setting client name: TestMultiWithTiebreak
 Auto-configure...
 Connecting 127.0.0.1:6381/Interactive...
 BeginConnect: 127.0.0.1:6381
 Sending critical tracer message ECHO: Interactive/127.0.0.1:6379
 Writing to Interactive/127.0.0.1:6379: ECHO
 Flushing outbound buffer
 Starting read
 Connected Interactive/127.0.0.1:6381
 Server handshake
 Authenticating (password) to endpoint 127.0.0.1:6381
 Setting client name: TestMultiWithTiebreak
 Auto-configure...
 Sending critical tracer message ECHO: Interactive/127.0.0.1:6381
 Writing to Interactive/127.0.0.1:6381: ECHO
 Flushing outbound buffer
 Starting read
 2 unique nodes specified
 Server endpoint 127.0.0.1:6379 is in ConnectedEstablishing
 Requesting tie-break from 127.0.0.1:6379 > __tie__...
 Server endpoint 127.0.0.1:6381 is in Connecting
 Requesting tie-break from 127.0.0.1:6381 > __tie__...
 Allowing endpoints 00:00:05 to respond...
 Awaiting task completion, IOCP: (Busy=2,Free=998,Min=8,Max=1000), WORKER: (Busy=4,Free=32763,Min=8,Max=32767)
 Writing to Interactive/127.0.0.1:6381: PING
 Writing to Interactive/127.0.0.1:6381: GET __tie__
 Response from Interactive/127.0.0.1:6381 / ECHO: BulkString: 16 bytes
 Response from Interactive/127.0.0.1:6379 / ECHO: BulkString: 16 bytes
 Writing to Interactive/127.0.0.1:6379: PING
 Writing to Interactive/127.0.0.1:6379: GET __tie__
 Response from Interactive/127.0.0.1:6379 / PING: SimpleString: PONG
 Response from Interactive/127.0.0.1:6379 / GET __tie__: (null)
 Finished awaiting tasks, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767)
 127.0.0.1:6379 returned with success
 127.0.0.1:6381 faulted: AuthenticationFailure (None, last-recv: 690) on 127.0.0.1:6381/Interactive, Idle/ComputeResult, last: ECHO, origin: SetResult, outstanding: 13, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.44.26105

**Comment by NickCraver** [comment]
I spent a chunk of time on this today and it's not a straightforward refactor, though we have significant progress on recognizing the issue. I'm going to sync with @mgravell tomorrow on this one and see if we have ideas around it. There's not a decent hook I could find to continue based on the `ServerEndPoint` finishing connection before the tracer is sent in the `AUTH` case. This is mainly because tangential to the initial connection case as exhibited by tests, the same path will be hit on _reconnects_ as well upon further reconfigures.

It seems like we should either expose a task we could continue after in the connection case (if it hasn't completed?), or we go the priority queue route and the tracer and tie breaker fetches are ordered after. Even doing a clean split here (only needed in the tie breaker case) on a secondary for loop after the `await WaitAllIgnoreErrorsAsync(available, remaining, log).ForAwait();` doesn't work, because _we don't have anything to await_. We're leaning on that mis-placed tracer today. So either we need to expose something we _can_ await (e.g. wait until everything finishes connecting, and then get tiebreakers), or we queue. It's also worth noting that on the initial connection we're sending a tracer as part of the bridge creation and then _again_ in this `ReconfigureAsync` code path (really only intended for sanity checks later). We need not send that additional tracer for initial connections, but we don't currently expose a way to await the initial one. It's not an isolated fix because removing the tracer would only move the problem down slight to the `GET` on the tiebreaker.

We need a "on connect, run these...or if you are connected, run these now", and that set needs to be awaitable. We need to make some larger changes here but a clean approach wasn't something I found today - will poke it more tomorrow as time allows.

**Comment by TimLovellSmith** [comment]
Fixed by #1762 right?

**Comment by NickCraver** [comment]
@TimLovellSmith It should be - I'm intermittently seeing an issue with possibly already-connected servers in the MultiMaster tests potentially caused by the recent changes, where the multiplexer waits for 5 seconds and even though we completed, the task coming back did not (one of the `tiebreaker` tasks we're waiting on). I believe there may be one bug yet in there, holding off on release while I chase this down.

If you're able to pull and repro (it'll fail intermittently in CI), I'd appreciate extra eyes - after that we should be set for a test and release iteration.

**Comment by NickCraver** [comment]
@TimLovellSmith example run: https://github.com/StackExchange/StackExchange.Redis/runs/2876912910?check_suite_focus=true

```
 Running under .NET Core 3.1.16 (3.1.16)
    Running on: Linux 5.8.0-1033-azure #35~20.04.1-Ubuntu SMP Wed May 19 06:46:04 UTC 2021
 15:57:00.329: 127.0.0.1:6379,127.0.0.1:6381,name=TestMultiWithTiebreak,***
 15:57:00.329: 127.0.0.1:6379/Interactive: Connecting...
 15:57:00.329: 127.0.0.1:6379: BeginConnectAsync
 15:57:00.329: 127.0.0.1:6379/Interactive: Connected 
 15:57:00.329: 127.0.0.1:6379: Server handshake
 15:57:00.329: 127.0.0.1:6379: Authenticating (password)
 15:57:00.329: 127.0.0.1:6379: Setting client name: TestMultiWithTiebreak
 15:57:00.329: 127.0.0.1:6379: Auto-configuring...
 15:57:00.329: 127.0.0.1:6379: Sending critical tracer (handshake): ECHO
 15:57:00.329: 127.0.0.1:6379/Interactive: Writing: ECHO
 15:57:00.329: 127.0.0.1:6379: Flushing outbound buffer
 15:57:00.329: 127.0.0.1:6379: OnEstablishingAsync complete
 15:57:00.329: 127.0.0.1:6379: Starting read
 15:57:00.330: 127.0.0.1:6381/Interactive: Connecting...
 15:57:00.330: 127.0.0.1:6381: BeginConnectAsync
 15:57:00.330: 127.0.0.1:6379: Auto-configured (CONFIG) read-only replica: true
 15:57:00.330: 127.0.0.1:6379: Auto-configured (CONFIG) databases: 2000
 15:57:00.330: 127.0.0.1:6379: Auto-configured (INFO) version: 5.0.12
 15:57:00.330: 127.0.0.1:6379: Auto-configured (INFO) server-type: standalone
 15:57:00.330: 127.0.0.1:6381/Interactive: Connected 
 15:57:00.330: 127.0.0.1:6381: Server handshake
 15:57:00.330: 127.0.0.1:6381: Authenticating (password)
 15:57:00.330: 127.0.0.1:6381: Setting client name: TestMultiWithTiebreak
 15:57:00.331: 127.0.0.1:6381: Auto-configuring...
 15:57:00.331: 127.0.0.1:6379: Auto-configured (INFO) role: master
 15:57:00.331: Response from Interactive/127.0.0.1:6379 / ECHO: BulkString: 16 bytes
 15:57:00.332: 127.0.0.1:6381: Sending critical tracer (handshake): ECHO
 15:57:00.332: 127.0.0.1:6381/Interactive: Writing: ECHO
 15:57:00.332: 127.0.0.1:6381: Flushing outbound buffer
 15:57:00.332: 127.0.0.1:6381: OnEstablishingAsync complete
 15:57:00.332: 127.0.0.1:6381: Starting read
 15:57:00.332: 127.0.0.1:6381: Auto-configured (CONFIG) read-only replica: true
 15:57:00.332: 2 unique nodes specified
 15:57:00.332: 127.0.0.1:6379/Interactive: Writing: PING
 15:57:00.332: Allowing 2 endpoint(s) 00:00:05 to respond...
 15:57:00.332: Awaiting 2 available task completion(s), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=13,Free=32754,Min=2,Max=32767)
 15:57:00.333: Response from Interactive/127.0.0.1:6379 / PING: SimpleString: PONG
 15:57:00.333: 127.0.0.1:6381: Auto-configured (CONFIG) databases: 2000
 15:57:00.333: 127.0.0.1:6381: Auto-configured (INFO) version: 5.0.12
 15:57:00.333: 127.0.0.1:6381: Auto-configured (INFO) server-type: standalone
 15:57:00.333: 127.0.0.1:6381: Auto-configured (INFO) role: master
 15:57:00.333: Response from Interactive/127.0.0.1:6381 / ECHO: BulkString: 16 bytes
 15:57:00.333: 127.0.0.1:6381: OnConnectedAsync completed (From command: ECHO)
 15:57:00.362: 127.0.0.1:6379: OnConnectedAsync completed (already connected)
 15:57:00.945: All 2 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=5,Free=32762,Min=2,Max=32767)
 15:57:00.945: 127.0.0.1:6379: Endpoint is ConnectedEstablished
 15:57:00.945: 127.0.0.1:6381: Endpoint is ConnectedEstablished
 15:57:00.945: 127.0.0.1:6379: Requesting tie-break (Key="__tie__")...
 15:57:00.945: 127.0.0.1:6379/Interactive: Writing: GET __tie__
 15:57:00.945: 127.0.0.1:6381: Requesting tie-break (Key="__tie__")...
 15:57:00.945: 127.0.0.1:6381/Interactive: Writing: GET __tie__
 15:57:00.945: 127.0.0.1:6379: Returned with success as Standalone primary (Source: Already connected)
 15:57:00.945: 127.0.0.1:6381: Returned with success as Standalone primary (Source: From command: ECHO)
 15:57:00.945: Waiting for tiebreakers...
 15:57:00.945: Awaiting 2 tiebreaker task completion(s), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=5,Free=32762,Min=2,Max=32767)
 15:57:01.083: Not all tiebreaker tasks completed cleanly (from NominatePreferredMaster#2012, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=6,Free=32761,Min=2,Max=32767)
 15:57:01.083: Election: 127.0.0.1:6379 failed to nominate (WaitingForActivation)
 15:57:01.083: Election: 127.0.0.1:6381 failed to nominate (WaitingForActivation)
 15:57:01.083: Election: Multiple masters detected...
 15:57:01.083: Election: No nominations by tie-breaker
 15:57:01.083: Election: Choosing master arbitrarily: 127.0.0.1:6379
 15:57:01.083: 127.0.0.1:6379: Clearing as RedundantMaster
 15:57:01.083: 127.0.0.1:6381: Setting as RedundantMaster
 15:57:01.083: 127.0.0.1:6379: Standalone v5.0.12, master; 2000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
 15:57:01.083: 127.0.0.1:6379: int ops=12, qu=0, qs=1, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 15:57:01.083: 127.0.0.1:6379: Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
 15:57:01.083: 127.0.0.1:6381: Standalone v5.0.12, master; 2000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: RedundantMaster
 15:57:01.083: 127.0.0.1:6381: int ops=11, qu=0, qs=1, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 15:57:01.083: 127.0.0.1:6381: Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
 15:57:01.083: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
 15:57:01.083: Starting heartbeat...
 15:57:01.084: 15:57:01.083: Connect took: 754ms
 15:57:01.111: Service Counts: (Scheduler) Queue: 2285, Pool: 0
```

```
[xUnit.net 00:00:12.57]     MultiMaster.TestMultiWithTiebreak(a: null, b: "127.0.0.1:6381", elected: "127.0.0.1:6381") [FAIL]
  Skipped ConnectionFailedErrors.SSLCertificateValidationError(isCertValidationSucceeded: False) [1 ms]
  Skipped ConnectionFailedErrors.SSLCertificateValidationError(isCertValidationSucceeded: True) [1 ms]
  Skipped ConnectionFailedErrors.AuthenticationFailureError [1 ms]
  Failed MultiMaster.TestMultiWithTiebreak(a: null, b: "127.0.0.1:6381", elected: "127.0.0.1:6381") [5 s]
  Error Message:
   elected
Expected: True
Actual:   False
  Stack Trace:
     at StackExchange.Redis.Tests.MultiMaster.TestMultiWithTiebreak(String a, String b, String elected) in D:\a\StackExchange.Redis\StackExchange.Redis\tests\StackExchange.Redis.Tests\MultiMaster.cs:line 83
  Standard Output Messages:
 Running under .NET Core 3.1.16 (3.1.16)
   Running on: Microsoft Windows 10.0.17763
 15:59:13.794: 127.0.0.1:6379,127.0.0.1:6381,name=TestMultiWithTiebreak,***
 15:59:13.794: 127.0.0.1:6379/Interactive: Connecting...
 15:59:13.794: 127.0.0.1:6379: BeginConnectAsync
 15:59:13.794: 127.0.0.1:6379/Interactive: Connected 
 15:59:13.794: 127.0.0.1:6379: Server handshake
 15:59:13.794: 127.0.0.1:6379: Authenticating (password)
 15:59:13.794: 127.0.0.1:6379: Setting client name: TestMultiWithTiebreak
 15:59:13.794: 127.0.0.1:6379: Auto-configuring...
 15:59:13.795: 127.0.0.1:6379: Sending critical tracer (handshake): ECHO
 15:59:13.795: 127.0.0.1:6379/Interactive: Writing: ECHO
 15:59:13.795: 127.0.0.1:6379: Flushing outbound buffer
 15:59:13.795: 127.0.0.1:6379: OnEstablishingAsync complete
 15:59:13.795: 127.0.0.1:6379: Starting read
 15:59:13.795: 127.0.0.1:6379: Auto-configured (CONFIG) read-only replica: true
 15:59:13.795: 127.0.0.1:6379: Auto-configured (CONFIG) databases: 2000
 15:59:13.795: 127.0.0.1:6379: Auto-configured (INFO) version: 3.0.503
 15:59:13.795: 127.0.0.1:6379: Auto-configured (INFO) server-type: standalone
 15:59:13.795: 127.0.0.1:6379: Auto-configured (INFO) role: master
 15:59:13.795: Response from Interactive/127.0.0.1:6379 / ECHO: BulkString: 16 bytes
 15:59:13.795: 127.0.0.1:6381/Interactive: Connecting...
 15:59:13.795: 127.0.0.1:6381: BeginConnectAsync
 15:59:13.796: 127.0.0.1:6381/Interactive: Connected 
 15:59:13.796: 127.0.0.1:6381: Server handshake
 15:59:13.796: 127.0.0.1:6381: Authenticating (password)
 15:59:13.796: 127.0.0.1:6381: Setting client name: TestMultiWithTiebreak
 15:59:13.796: 127.0.0.1:6381: Auto-configuring...
 15:59:13.796: 127.0.0.1:6381: Sending critical tracer (handshake): ECHO
 15:59:13.796: 127.0.0.1:6381/Interactive: Writing: ECHO
 15:59:13.796: 127.0.0.1:6381: Flushing outbound buffer
 15:59:13.796: 127.0.0.1:6381: OnEstablishingAsync complete
 15:59:13.796: 127.0.0.1:6381: Starting read
 15:59:13.796: 127.0.0.1:6381: Auto-configured (CONFIG) read-only replica: true
 15:59:13.796: 127.0.0.1:6381: Auto-configured (CONFIG) databases: 2000
 15:59:13.796: 127.0.0.1:6381: Auto-configured (INFO) version: 3.0.503
 15:59:13.796: 127.0.0.1:6381: Auto-configured (INFO) server-type: standalone
 15:59:13.796: 127.0.0.1:6381: Auto-configured (INFO) role: master
 15:59:13.796: Response from Interactive/127.0.0.1:6381 / ECHO: BulkString: 16 bytes
 15:59:13.796: 2 unique nodes specified
 15:59:13.796: 127.0.0.1:6379/Interactive: Writing: PING
 15:59:13.796: 127.0.0.1:6381/Interactive: Writing: PING
 15:59:13.797: Response from Interactive/127.0.0.1:6379 / PING: SimpleString: PONG
 15:59:13.797: Response from Interactive/127.0.0.1:6381 / PING: SimpleString: PONG
 15:59:13.797: 127.0.0.1:6381: OnConnectedAsync completed (already connected)
 15:59:13.797: Allowing 2 endpoint(s) 00:00:05 to respond...
 15:59:13.797: Awaiting 2 available task completion(s), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=2,Free=32765,Min=2,Max=32767)
 15:59:18.801: Not all available tasks completed cleanly (from ReconfigureAsync#1739, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=4,Free=32763,Min=2,Max=32767)
 15:59:18.801: 127.0.0.1:6379: Endpoint is ConnectedEstablished
 15:59:18.801: 127.0.0.1:6381: Endpoint is ConnectedEstablished
 15:59:18.801: 127.0.0.1:6379: Requesting tie-break (Key="__tie__")...
 15:59:18.801: 127.0.0.1:6379/Interactive: Writing: GET __tie__
 15:59:18.801: 127.0.0.1:6381: Requesting tie-break (Key="__tie__")...
 15:59:18.801: 127.0.0.1:6381/Interactive: Writing: GET __tie__
 15:59:18.801: Response from Interactive/127.0.0.1:6379 / GET __tie__: (null)
 15:59:18.801: Response from Interactive/127.0.0.1:6381 / GET __tie__: BulkString: 14 bytes
 15:59:18.801: 127.0.0.1:6379: Did not respond
 15:59:18.801: 127.0.0.1:6381: Returned with success as Standalone primary (Source: Already connected)
 15:59:18.801: Waiting for tiebreakers...
 15:59:18.801: All tasks are already complete
 15:59:18.801: Election: 127.0.0.1:6379 had no tiebreaker set
 15:59:18.801: Election: 127.0.0.1:6381 nominates: 127.0.0.1:6381
 15:59:18.801: Election: Single master detected: 127.0.0.1:6381
 15:59:18.801: 127.0.0.1:6381: Clearing as RedundantMaster
 15:59:18.801: 127.0.0.1:6379: Standalone v3.0.503, master; 2000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: DidNotRespond
 15:59:18.801: 127.0.0.1:6379: int ops=12, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 15:59:18.801: 127.0.0.1:6379: Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
 15:59:18.801: 127.0.0.1:6381: Standalone v3.0.503, master; 2000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
 15:59:18.801: 127.0.0.1:6381: int ops=12, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 15:59:18.801: 127.0.0.1:6381: Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
 15:59:18.802: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
 15:59:18.802: Starting heartbeat...
 15:59:18.802: 15:59:18.802: Connect took: 5007ms
 15:59:18.804: Service Counts: (Scheduler) Queue: 3195, Pool: 0
```

Note that in the second example, `OnConnectedAsync` did not log for 6379, though ` 15:59:13.797: Response from Interactive/127.0.0.1:6379 / PING: SimpleString: PONG` came back promptly...for some reason the task didn't trigger and I'm not sure why just yet.

**Comment by NickCraver** [comment]
Got a repro locally (adding Task logging):
```
   Source: MultiMaster.cs line 58
   Duration: 5 sec

  Message: 
    arbitrarily
    Expected: True
    Actual:   False

  Stack Trace: 
    MultiMaster.TestMultiWithTiebreak(String a, String b, String elected) line 92

  Standard Output: 
Running under .NET Core 3.1.16 (3.1.16)
   Running on: Microsoft Windows 10.0.19043
17:15:05.779: 127.0.0.1:6379,127.0.0.1:6381,name=TestMultiWithTiebreak,password=*****,tiebreaker=__tie__
17:15:05.779: 127.0.0.1:6379/Interactive: Connecting...
17:15:05.779: 127.0.0.1:6379: BeginConnectAsync
17:15:05.779: 127.0.0.1:6379/Interactive: Connected 
17:15:05.779: 127.0.0.1:6379: Server handshake
17:15:05.779: 127.0.0.1:6379: Authenticating (password)
17:15:05.779: 127.0.0.1:6379: Setting client name: TestMultiWithTiebreak
17:15:05.779: 127.0.0.1:6379: Auto-configuring...
17:15:05.779: 127.0.0.1:6379: Sending critical tracer (handshake): ECHO
17:15:05.779: 127.0.0.1:6379/Interactive: Writing: ECHO
17:15:05.779: 127.0.0.1:6379: Flushing outbound buffer
17:15:05.779: 127.0.0.1:6379: OnEstablishingAsync complete
17:15:05.779: 127.0.0.1:6379: Starting read
17:15:05.779: 127.0.0.1:6381/Interactive: Connecting...
17:15:05.779: 127.0.0.1:6381: BeginConnectAsync
17:15:05.779: 127.0.0.1:6379: Auto-configured (CONFIG) read-only replica: true
17:15:05.779: 127.0.0.1:6379: Auto-configured (CONFIG) databases: 10000
17:15:05.779: 127.0.0.1:6379: Auto-configured (INFO) version: 3.0.503
17:15:05.780: 127.0.0.1:6379: Auto-configured (INFO) server-type: standalone
17:15:05.780: 127.0.0.1:6379: Auto-configured (INFO) role: master
17:15:05.780: Response from Interactive/127.0.0.1:6379 / ECHO: BulkString: 16 bytes
17:15:05.780: 127.0.0.1:6381/Interactive: Connected 
17:15:05.780: 127.0.0.1:6381: Server handshake
17:15:05.780: 127.0.0.1:6381: Authenticating (password)
17:15:05.780: 127.0.0.1:6381: Setting client name: TestMultiWithTiebreak
17:15:05.780: 127.0.0.1:6381: Auto-configuring...
17:15:05.780: 127.0.0.1:6381: Sending critical tracer (handshake): ECHO
17:15:05.780: 127.0.0.1:6381/Interactive: Writing: ECHO
17:15:05.780: 127.0.0.1:6381: Flushing outbound buffer
17:15:05.780: 127.0.0.1:6381: OnEstablishingAsync complete
17:15:05.780: 127.0.0.1:6381: Starting read
17:15:05.780: 2 unique nodes specified
17:15:05.780: 127.0.0.1:6379/Interactive: Writing: PING
17:15:05.780: Allowing 2 endpoint(s) 00:00:05 to respond...
17:15:05.780: Awaiting 2 available task completion(s), IOCP: (Busy=1,Free=999,Min=32,Max=1000), WORKER: (Busy=2,Free=32765,Min=32,Max=32767)
17:15:05.780: 127.0.0.1:6381: Auto-configured (CONFIG) read-only replica: true
17:15:05.780: Response from Interactive/127.0.0.1:6379 / PING: SimpleString: PONG
17:15:05.780: 127.0.0.1:6381: Auto-configured (CONFIG) databases: 10000
17:15:05.780: 127.0.0.1:6381: Auto-configured (INFO) version: 3.0.503
17:15:05.780: 127.0.0.1:6381: Auto-configured (INFO) server-type: standalone
17:15:05.780: 127.0.0.1:6381: Auto-configured (INFO) role: master
17:15:05.780: Response from Interactive/127.0.0.1:6381 / ECHO: BulkString: 16 bytes
17:15:05.780: 127.0.0.1:6381: OnConnectedAsync completed (From command: ECHO)
17:15:10.781: Not all available tasks completed cleanly (from ReconfigureAsync#1743, timeout 5000ms), IOCP: (Busy=1,Free=999,Min=32,Max=1000), WORKER: (Busy=3,Free=32764,Min=32,Max=32767)
17:15:10.781:   Task[0] Status: WaitingForActivation
17:15:10.781:   Task[1] Status: RanToCompletion
17:15:10.781: 127.0.0.1:6379: Endpoint is ConnectedEstablished
17:15:10.781: 127.0.0.1:6381: Endpoint is ConnectedEstablished
17:15:10.781: 127.0.0.1:6379: Requesting tie-break (Key="__tie__")...
17:15:10.781: 127.0.0.1:6379/Interactive: Writing: GET __tie__
17:15:10.781: 127.0.0.1:6381: Requesting tie-break (Key="__tie__")...
17:15:10.781: 127.0.0.1:6381/Interactive: Writing: GET __tie__
17:15:10.781: 127.0.0.1:6379: Did not respond
17:15:10.781: 127.0.0.1:6381: Returned with success as Standalone primary (Source: From command: ECHO)
17:15:10.781: Waiting for tiebreakers...
17:15:10.781: Awaiting 2 tiebreaker task completion(s), IOCP: (Busy=0,Free=1000,Min=32,Max=1000), WORKER: (Busy=3,Free=32764,Min=32,Max=32767)
17:15:10.781: Response from Interactive/127.0.0.1:6379 / GET __tie__: (null)
17:15:10.781: Response from Interactive/127.0.0.1:6381 / GET __tie__: (null)
17:15:10.781: All 2 tiebreaker tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=32,Max=1000), WORKER: (Busy=3,Free=32764,Min=32,Max=32767)
17:15:10.781:   Task[0] Status: RanToCompletion
17:15:10.781:   Task[1] Status: RanToCompletion
17:15:10.781: Election: 127.0.0.1:6379 had no tiebreaker set
17:15:10.781: Election: 127.0.0.1:6381 had no tiebreaker set
17:15:10.781: Election: Single master detected: 127.0.0.1:6381
17:15:10.781: 127.0.0.1:6381: Clearing as RedundantMaster
17:15:10.781: 127.0.0.1:6379: Standalone v3.0.503, master; 10000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: DidNotRespond
17:15:10.781: 127.0.0.1:6379: int ops=12, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
17:15:10.781: 127.0.0.1:6379: Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
17:15:10.781: 127.0.0.1:6381: Standalone v3.0.503, master; 10000 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
17:15:10.781: 127.0.0.1:6381: int ops=11, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
17:15:10.781: 127.0.0.1:6381: Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
17:15:10.781: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
17:15:10.781: Starting heartbeat...
17:15:10.781: 17:15:10.781: Connect took: 5002ms
17:15:10.786: Service Counts: (Scheduler) Queue: 3062, Pool: 0
```

**Comment by NickCraver** [comment]
Forgot to clean up this issue - we've improved all this and the handshake code now all goes in order and as of #1931, all happens in the same place as well. Tidying up!
