### ISSUE TITLE
SentinelFailover.ManagedMasterConnectionEndToEndWithFailoverTest test race

### ISSUE THREAD

**Issue by NickCraver** [StackExchange/StackExchange.Redis#1783]
I noticed an oddity in the logs after getting Sentinel a lot more stable in the 2.2.50 release. There seems to be a race still, but possibly in the test. Specifically, note that this is normal:
```lua
 22:25:05.739: Waiting for server (127.0.0.1:7011) role to be "master"...
 22:25:05.739: Done waiting for server (127.0.0.1:7011) role to be "master"
 22:25:05.739: Waiting for server (127.0.0.1:7010) role to be "slave"...
 22:25:05.739: Done waiting for server (127.0.0.1:7010) role to be "slave"
```
But the failure is waiting on the same server:
```lua
 22:25:06.833: Waiting for server (127.0.0.1:7010) role to be "master"...
 22:25:06.834: Done waiting for server (127.0.0.1:7010) role to be "master"
 22:25:06.834: Waiting for server (127.0.0.1:7010) role to be "slave"...
```

I believe we're just fetching the replicas too eagerly here, ahead of state change.

Full log:
```
  Failed SentinelFailover.ManagedMasterConnectionEndToEndWithFailoverTest [30 s]
  Error Message:
   StackExchange.Redis.RedisException : Timeout waiting for server (127.0.0.1:7010) to have expected role ("slave") assigned
  Stack Trace:
     at StackExchange.Redis.Tests.SentinelBase.WaitForRoleAsync(IServer server, String role, Nullable`1 duration) in C:\projects\stackexchange-redis\tests\StackExchange.Redis.Tests\SentinelBase.cs:line 0
   at StackExchange.Redis.Tests.SentinelBase.WaitForReadyAsync(EndPoint expectedMaster, Boolean waitForReplication, Nullable`1 duration) in C:\projects\stackexchange-redis\tests\StackExchange.Redis.Tests\SentinelBase.cs:line 121
   at StackExchange.Redis.Tests.SentinelBase.DoFailoverAsync() in C:\projects\stackexchange-redis\tests\StackExchange.Redis.Tests\SentinelBase.cs:line 80
   at StackExchange.Redis.Tests.SentinelFailover.ManagedMasterConnectionEndToEndWithFailoverTest() in C:\projects\stackexchange-redis\tests\StackExchange.Redis.Tests\SentinelFailover.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 Running under .NET Core 3.1.16 (3.1.16)
   Running on: Microsoft Windows 10.0.17763
 22:25:05.431: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381,serviceName=mymaster,allowAdmin=True,$NONE=,$APPEND=,$ASKING=,$BGREWRITEAOF=,$BGSAVE=,$BITCOUNT=,$BITOP=,$BITPOS=,$BLPOP=,$BRPOP=,$BRPOPLPUSH=,$CLIENT=,$CLUSTER=,$CONFIG=,$DBSIZE=,$DEBUG=,$DECR=,$DECRBY=,$DEL=,$DISCARD=,$DUMP=,$ECHO=,$EVAL=,$EVALSHA=,$EXEC=,$EXISTS=,$EXPIRE=,$EXPIREAT=,$FLUSHALL=,$FLUSHDB=,$GEOADD=,$GEODIST=,$GEOHASH=,$GEOPOS=,$GEORADIUS=,$GEORADIUSBYMEMBER=,$GET=,$GETBIT=,$GETRANGE=,$GETSET=,$HDEL=,$HEXISTS=,$HGET=,$HGETALL=,$HINCRBY=,$HINCRBYFLOAT=,$HKEYS=,$HLEN=,$HMGET=,$HMSET=,$HSCAN=,$HSET=,$HSETNX=,$HSTRLEN=,$HVALS=,$INCR=,$INCRBY=,$INCRBYFLOAT=,$KEYS=,$LASTSAVE=,$LATENCY=,$LINDEX=,$LINSERT=,$LLEN=,$LPOP=,$LPUSH=,$LPUSHX=,$LRANGE=,$LREM=,$LSET=,$LTRIM=,$MEMORY=,$MGET=,$MIGRATE=,$MONITOR=,$MOVE=,$MSET=,$MSETNX=,$MULTI=,$OBJECT=,$PERSIST=,$PEXPIRE=,$PEXPIREAT=,$PFADD=,$PFCOUNT=,$PFMERGE=,$PSETEX=,$PTTL=,$PUBLISH=,$PUBSUB=,$QUIT=,$RANDOMKEY=,$READONLY=,$READWRITE=,$RENAME=,$RENAMENX=,$REPLICAOF=,$RESTORE=,$RPOP=,$RPOPLPUSH=,$RPUSH=,$RPUSHX=,$SADD=,$SAVE=,$SCAN=,$SCARD=,$SCRIPT=,$SDIFF=,$SDIFFSTORE=,$SELECT=,$SET=,$SETBIT=,$SETEX=,$SETNX=,$SETRANGE=,$SINTER=,$SINTERSTORE=,$SISMEMBER=,$SLAVEOF=,$SLOWLOG=,$SMEMBERS=,$SMOVE=,$SORT=,$SPOP=,$SRANDMEMBER=,$SREM=,$STRLEN=,$SUNION=,$SUNIONSTORE=,$SSCAN=,$SWAPDB=,$SYNC=,$TIME=,$TOUCH=,$TTL=,$TYPE=,$UNLINK=,$UNWATCH=,$WATCH=,$XACK=,$XADD=,$XCLAIM=,$XDEL=,$XGROUP=,$XINFO=,$XLEN=,$XPENDING=,$XRANGE=,$XREAD=,$XREADGROUP=,$XREVRANGE=,$XTRIM=,$ZADD=,$ZCARD=,$ZCOUNT=,$ZINCRBY=,$ZINTERSTORE=,$ZLEXCOUNT=,$ZPOPMAX=,$ZPOPMIN=,$ZRANGE=,$ZRANGEBYLEX=,$ZRANGEBYSCORE=,$ZRANK=,$ZREM=,$ZREMRANGEBYLEX=,$ZREMRANGEBYRANK=,$ZREMRANGEBYSCORE=,$ZREVRANGE=,$ZREVRANGEBYLEX=,$ZREVRANGEBYSCORE=,$ZREVRANK=,$ZSCAN=,$ZSCORE=,$ZUNIONSTORE=,$UNKNOWN=
 22:25:05.431: 127.0.0.1:26379/Interactive: Connecting...
 22:25:05.431: 127.0.0.1:26379: BeginConnectAsync
 22:25:05.431: 127.0.0.1:26379/Interactive: Connected 
 22:25:05.431: 127.0.0.1:26379: Server handshake
 22:25:05.431: 127.0.0.1:26379: Auto-configuring...
 22:25:05.431: 127.0.0.1:26379: Sending critical tracer (handshake): PING
 22:25:05.431: 127.0.0.1:26379/Interactive: Writing: PING
 22:25:05.431: 127.0.0.1:26379: Flushing outbound buffer
 22:25:05.431: 127.0.0.1:26379: OnEstablishingAsync complete
 22:25:05.431: 127.0.0.1:26379: Starting read
 22:25:05.431: 127.0.0.1:26380/Interactive: Connecting...
 22:25:05.431: 127.0.0.1:26379: Auto-configured (SENTINEL) server-type: sentinel
 22:25:05.431: 127.0.0.1:26379: Auto-configured (INFO) version: 3.0.503
 22:25:05.431: 127.0.0.1:26379: Auto-configured (INFO) server-type: sentinel
 22:25:05.432: Response from Interactive/127.0.0.1:26379 / PING: SimpleString: PONG
 22:25:05.432: 127.0.0.1:26380: BeginConnectAsync
 22:25:05.432: 127.0.0.1:26380/Interactive: Connected 
 22:25:05.432: 127.0.0.1:26380: Server handshake
 22:25:05.432: 127.0.0.1:26380: Auto-configuring...
 22:25:05.432: 127.0.0.1:26380: Sending critical tracer (handshake): PING
 22:25:05.432: 127.0.0.1:26380/Interactive: Writing: PING
 22:25:05.432: 127.0.0.1:26380: Flushing outbound buffer
 22:25:05.432: 127.0.0.1:26380: OnEstablishingAsync complete
 22:25:05.432: 127.0.0.1:26380: Starting read
 22:25:05.432: 127.0.0.1:26380: Auto-configured (SENTINEL) server-type: sentinel
 22:25:05.432: 127.0.0.1:26380: Auto-configured (INFO) version: 3.0.503
 22:25:05.432: 127.0.0.1:26380: Auto-configured (INFO) server-type: sentinel
 22:25:05.432: Response from Interactive/127.0.0.1:26380 / PING: SimpleString: PONG
 22:25:05.432: 127.0.0.1:26381/Interactive: Connecting...
 22:25:05.433: 127.0.0.1:26381: BeginConnectAsync
 22:25:05.433: 127.0.0.1:26381/Interactive: Connected 
 22:25:05.433: 127.0.0.1:26381: Server handshake
 22:25:05.433: 127.0.0.1:26381: Auto-configuring...
 22:25:05.433: 127.0.0.1:26381: Sending critical tracer (handshake): PING
 22:25:05.433: 127.0.0.1:26381/Interactive: Writing: PING
 22:25:05.433: 127.0.0.1:26381: Flushing outbound buffer
 22:25:05.433: 127.0.0.1:26381: OnEstablishingAsync complete
 22:25:05.433: 127.0.0.1:26381: Starting read
 22:25:05.433: 127.0.0.1:26381: Auto-configured (SENTINEL) server-type: sentinel
 22:25:05.433: 127.0.0.1:26381: Auto-configured (INFO) version: 3.0.503
 22:25:05.433: 127.0.0.1:26381: Auto-configured (INFO) server-type: sentinel
 22:25:05.433: Response from Interactive/127.0.0.1:26381 / PING: SimpleString: PONG
 22:25:05.433: 3 unique nodes specified
 22:25:05.433: 127.0.0.1:26379: OnConnectedAsync init (State=ConnectedEstablished)
 22:25:05.434: 127.0.0.1:26379: OnConnectedAsync completed (already connected start)
 22:25:05.434: 127.0.0.1:26379/Interactive: Writing: PING
 22:25:05.434: 127.0.0.1:26380: OnConnectedAsync init (State=ConnectedEstablished)
 22:25:05.434: 127.0.0.1:26380: OnConnectedAsync completed (already connected start)
 22:25:05.434: 127.0.0.1:26380/Interactive: Writing: PING
 22:25:05.434: Response from Interactive/127.0.0.1:26379 / PING: SimpleString: PONG
 22:25:05.434: 127.0.0.1:26381: OnConnectedAsync init (State=ConnectedEstablished)
 22:25:05.434: 127.0.0.1:26379: OnConnectedAsync completed (already connected end)
 22:25:05.434: 127.0.0.1:26381: OnConnectedAsync completed (already connected start)
 22:25:05.434: 127.0.0.1:26381/Interactive: Writing: PING
 22:25:05.434: Allowing 3 endpoint(s) 00:00:05 to respond...
 22:25:05.434: Response from Interactive/127.0.0.1:26380 / PING: SimpleString: PONG
 22:25:05.434: Awaiting 3 available task completion(s) for 5000ms, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
 22:25:05.434: 127.0.0.1:26380: OnConnectedAsync completed (already connected end)
 22:25:05.434: Response from Interactive/127.0.0.1:26381 / PING: SimpleString: PONG
 22:25:05.434: 127.0.0.1:26381: OnConnectedAsync completed (already connected end)
 22:25:05.434: All 3 available tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=5,Free=32762,Min=4,Max=32767)
 22:25:05.434: 127.0.0.1:26379: Endpoint is ConnectedEstablished
 22:25:05.434: 127.0.0.1:26380: Endpoint is ConnectedEstablished
 22:25:05.434: 127.0.0.1:26381: Endpoint is ConnectedEstablished
 22:25:05.434: 127.0.0.1:26379: Returned with success as Sentinel primary (Source: Already connected)
 22:25:05.434: 127.0.0.1:26380: Returned with success as Sentinel primary (Source: Already connected)
 22:25:05.434: 127.0.0.1:26381: Returned with success as Sentinel primary (Source: Already connected)
 22:25:05.434: Election: Multiple masters detected...
 22:25:05.434: Election: Choosing master arbitrarily: 127.0.0.1:26379
 22:25:05.434: 127.0.0.1:26379: Clearing as RedundantMaster
 22:25:05.434: 127.0.0.1:26380: Setting as RedundantMaster
 22:25:05.434: 127.0.0.1:26381: Setting as RedundantMaster
 22:25:05.434: 127.0.0.1:26379: Sentinel v3.0.503, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
 22:25:05.434: 127.0.0.1:26379: int ops=5, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=2, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 22:25:05.434: 127.0.0.1:26379: Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+2=2 (0.20 ops/s; spans 10s)
 22:25:05.434: 127.0.0.1:26380: Sentinel v3.0.503, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: RedundantMaster
 22:25:05.434: 127.0.0.1:26380: int ops=5, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=2, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 22:25:05.434: 127.0.0.1:26380: Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+2=2 (0.20 ops/s; spans 10s)
 22:25:05.434: 127.0.0.1:26381: Sentinel v3.0.503, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: RedundantMaster
 22:25:05.434: 127.0.0.1:26381: int ops=5, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=2, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 22:25:05.434: 127.0.0.1:26381: Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+2=2 (0.20 ops/s; spans 10s)
 22:25:05.434: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
 22:25:05.434: Starting heartbeat...
 22:25:05.466: 127.0.0.1:7011,127.0.0.1:7010,serviceName=mymaster,allowAdmin=True
 22:25:05.466: 127.0.0.1:7011/Interactive: Connecting...
 22:25:05.466: 127.0.0.1:7011: BeginConnectAsync
 22:25:05.466: 127.0.0.1:7011/Interactive: Connected 
 22:25:05.466: 127.0.0.1:7011: Server handshake
 22:25:05.466: 127.0.0.1:7011: Setting client name: AV-5F37B11FF0E3
 22:25:05.466: 127.0.0.1:7011: Auto-configuring...
 22:25:05.466: 127.0.0.1:7011: Sending critical tracer (handshake): ECHO
 22:25:05.466: 127.0.0.1:7011/Interactive: Writing: ECHO
 22:25:05.466: 127.0.0.1:7011: Flushing outbound buffer
 22:25:05.466: 127.0.0.1:7011: OnEstablishingAsync complete
 22:25:05.466: 127.0.0.1:7011: Starting read
 22:25:05.466: 127.0.0.1:7010/Interactive: Connecting...
 22:25:05.466: 127.0.0.1:7011: Auto-configured (CONFIG) read-only replica: true
 22:25:05.466: 127.0.0.1:7011: Auto-configured (CONFIG) databases: 16
 22:25:05.467: 127.0.0.1:7011: Auto-configured (INFO) version: 3.0.503
 22:25:05.467: 127.0.0.1:7011: Auto-configured (INFO) server-type: standalone
 22:25:05.467: 127.0.0.1:7010: BeginConnectAsync
 22:25:05.467: 127.0.0.1:7011: Auto-configured (INFO) role: master
 22:25:05.467: Response from Interactive/127.0.0.1:7011 / ECHO: BulkString: 16 bytes
 22:25:05.467: 127.0.0.1:7010/Interactive: Connected 
 22:25:05.467: 127.0.0.1:7010: Server handshake
 22:25:05.467: 127.0.0.1:7010: Setting client name: AV-5F37B11FF0E3
 22:25:05.467: 127.0.0.1:7010: Auto-configuring...
 22:25:05.467: 127.0.0.1:7010: Sending critical tracer (handshake): ECHO
 22:25:05.467: 127.0.0.1:7010/Interactive: Writing: ECHO
 22:25:05.467: 127.0.0.1:7010: Flushing outbound buffer
 22:25:05.467: 127.0.0.1:7010: OnEstablishingAsync complete
 22:25:05.467: 127.0.0.1:7010: Starting read
 22:25:05.467: 2 unique nodes specified
 22:25:05.467: 127.0.0.1:7010: Auto-configured (CONFIG) read-only replica: true
 22:25:05.467: 127.0.0.1:7011: OnConnectedAsync init (State=ConnectedEstablished)
 22:25:05.467: 127.0.0.1:7010: Auto-configured (CONFIG) databases: 16
 22:25:05.467: 127.0.0.1:7011: OnConnectedAsync completed (already connected start)
 22:25:05.467: 127.0.0.1:7011/Interactive: Writing: PING
 22:25:05.467: 127.0.0.1:7010: Auto-configured (INFO) version: 3.0.503
 22:25:05.467: 127.0.0.1:7010: Auto-configured (INFO) server-type: standalone
 22:25:05.467: 127.0.0.1:7010: OnConnectedAsync init (State=ConnectedEstablishing)
 22:25:05.467: Allowing 2 endpoint(s) 00:00:05 to respond...
 22:25:05.467: Awaiting 2 available task completion(s) for 5000ms, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
 22:25:05.467: 127.0.0.1:7010: Auto-configured (INFO) role: replica
 22:25:05.467: Response from Interactive/127.0.0.1:7010 / ECHO: BulkString: 16 bytes
 22:25:05.467: Response from Interactive/127.0.0.1:7011 / PING: SimpleString: PONG
 22:25:05.467: 127.0.0.1:7010: OnConnectedAsync completed (From command: ECHO)
 22:25:05.467: 127.0.0.1:7011: OnConnectedAsync completed (already connected end)
 22:25:05.467: All 2 available tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
 22:25:05.467: 127.0.0.1:7011: Endpoint is ConnectedEstablished
 22:25:05.467: 127.0.0.1:7010: Endpoint is ConnectedEstablished
 22:25:05.467: 127.0.0.1:7011: Requesting tie-break (Key="__Booksleeve_TieBreak")...
 22:25:05.467: 127.0.0.1:7011/Interactive: Writing: GET __Booksleeve_TieBreak
 22:25:05.467: 127.0.0.1:7010: Requesting tie-break (Key="__Booksleeve_TieBreak")...
 22:25:05.467: 127.0.0.1:7010/Interactive: Writing: GET __Booksleeve_TieBreak
 22:25:05.467: 127.0.0.1:7011: Returned with success as Standalone primary (Source: Already connected)
 22:25:05.467: 127.0.0.1:7010: Returned with success as Standalone replica (Source: From command: ECHO)
 22:25:05.468: Waiting for tiebreakers...
 22:25:05.468: Response from Interactive/127.0.0.1:7011 / GET __Booksleeve_TieBreak: (null)
 22:25:05.468: Awaiting 2 tiebreaker task completion(s) for 50ms, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
 22:25:05.468: Response from Interactive/127.0.0.1:7010 / GET __Booksleeve_TieBreak: (null)
 22:25:05.468: All 2 tiebreaker tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
 22:25:05.468: Election: 127.0.0.1:7011 had no tiebreaker set
 22:25:05.468: Election: 127.0.0.1:7010 had no tiebreaker set
 22:25:05.468: Election: Single master detected: 127.0.0.1:7011
 22:25:05.468: 127.0.0.1:7011: Clearing as RedundantMaster
 22:25:05.468: 127.0.0.1:7011: Standalone v3.0.503, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
 22:25:05.468: 127.0.0.1:7011: int ops=11, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 22:25:05.468: 127.0.0.1:7011: Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
 22:25:05.468: 127.0.0.1:7010: Standalone v3.0.503, replica; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
 22:25:05.468: 127.0.0.1:7010: int ops=10, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
 22:25:05.468: 127.0.0.1:7010: Circular op-count snapshot; int: 0+10=10 (1.00 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
 22:25:05.468: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
 22:25:05.468: Starting heartbeat...
 22:25:05.468: Master is 127.0.0.1:7011
 22:25:05.469: Waiting for server (127.0.0.1:7011) role to be "master"...
 22:25:05.469: Done waiting for server (127.0.0.1:7011) role to be "master"
 22:25:05.469: Waiting for server (127.0.0.1:7010) role to be "slave"...
 22:25:05.469: Done waiting for server (127.0.0.1:7010) role to be "slave"
 22:25:05.475: Tick Key: 637601703054759246
 22:25:05.476: Waiting for master/replica replication to be in sync...
 22:25:05.476: Waiting for master (21724) / replica (21382) replication to be in sync...
 22:25:05.737: Done waiting for master (21724) / replica (21724) replication to be in sync
 22:25:05.737: Endpoints:
 22:25:05.737:   127.0.0.1:7011:
 22:25:05.737:      Server: (Connected=True, Type=Standalone, IsReplica=False, Unselectable=None)
 22:25:05.737:   127.0.0.1:7010:
 22:25:05.737:      Server: (Connected=True, Type=Standalone, IsReplica=True, Unselectable=None)
 22:25:05.739: Master is 127.0.0.1:7011
 22:25:05.739: Waiting for server (127.0.0.1:7011) role to be "master"...
 22:25:05.739: Done waiting for server (127.0.0.1:7011) role to be "master"
 22:25:05.739: Waiting for server (127.0.0.1:7010) role to be "slave"...
 22:25:05.739: Done waiting for server (127.0.0.1:7010) role to be "slave"
 22:25:05.740: Starting failover...
 22:25:06.832: Configuration changed: 127.0.0.1:7010
 22:25:06.833: Master is 127.0.0.1:7010
 22:25:06.833: Waiting for server (127.0.0.1:7010) role to be "master"...
 22:25:06.834: Done waiting for server (127.0.0.1:7010) role to be "master"
 22:25:06.834: Waiting for server (127.0.0.1:7010) role to be "slave"...
 22:25:16.956: Configuration changed: 127.0.0.1:7011
 22:25:36.027: Service Counts: (Scheduler) Queue: 53826, Pool: 0
```

**Comment by NickCraver** [comment]
Fixed in #1784 - this is a Redis-side poll latency issue described in comments there.
