### ISSUE TITLE
Connect to Redis Sentinel in Kubernetes - connection log show successful connetion to master node, but StackExchange.Redis throws error

### ISSUE THREAD

**Issue by jiyoon-koo** [StackExchange/StackExchange.Redis#1829]
Hi,

I am trying to connect to a redis sentinel in kubernetes, by using StackExchange.Redis.

Here's how I have mine set up, drawn from [this comment](https://github.com/StackExchange/StackExchange.Redis/issues/1580#issuecomment-883695770)

```csharp
// Program.cs
services.AddScoped<IDatabase>(cfg =>
                {
                    var sentinelConfig = new ConfigurationOptions()
                    {
                        EndPoints = { configsOptions.RedisUrl }, // "redis-headless.redis.svc.cluster.local" is the value
                        Password = secretsOptions.RedisPassword,
                        CommandMap = CommandMap.Sentinel                        
                    };

                    var masterConfig = new ConfigurationOptions
                    {
                        CommandMap = CommandMap.Default,
                        ServiceName = "redis-headless", // I'm just guessing this is the service name...
                    };

                    var sentinel = ConnectionMultiplexer.SentinelConnect(sentinelConfig, Console.Out);
                    var connection = sentinel.GetSentinelMasterConnection(masterConfig, Console.Out);
                    return connection.GetDatabase();
                });

```

I've also tried injecting Singleton of IConnectionMultiplexer like this, but get the same error.
```csharp
services.AddSingleton<IConnectionMultiplexer>(cfg =>
                {
                    return ConnectionMultiplexer.Connect($"{configsOptions.RedisUrl},password={secretsOptions.RedisPassword},serviceName=redis-headless", Console.Out);
                });

```

Here's what `kubectl get svc --namespace redis` gets me
```
MacBook-Pro:~ me$ kubectl get svc --namespace redis
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)              AGE
redis            ClusterIP   10.0.12.79   <none>        6379/TCP,26379/TCP   9d
redis-headless   ClusterIP   None         <none>        6379/TCP,26379/TCP   9d
```

I *believe* I needed to use `redis-headless` as my service name, in order to access the master node.

Connection logs initially looks OK, as PING is sent and PONG is received...
```
redis-headless.redis.svc.cluster.local:26379,serviceName=redis-headless,password=*****,$NONE=,$APPEND=,$ASKING=,$BGREWRITEAOF=,$BGSAVE=,$BITCOUNT=,$BITOP=,$BITPOS=,$BLPOP=,$BRPOP=,$BRPOPLPUSH=,$CLIENT=,$CLUSTER=,$CONFIG=,$DBSIZE=,$DEBUG=,$DECR=,$DECRBY=,$DEL=,$DISCARD=,$DUMP=,$ECHO=,$EVAL=,$EVALSHA=,$EXEC=,$EXISTS=,$EXPIRE=,$EXPIREAT=,$FLUSHALL=,$FLUSHDB=,$GEOADD=,$GEODIST=,$GEOHASH=,$GEOPOS=,$GEORADIUS=,$GEORADIUSBYMEMBER=,$GET=,$GETBIT=,$GETRANGE=,$GETSET=,$HDEL=,$HEXISTS=,$HGET=,$HGETALL=,$HINCRBY=,$HINCRBYFLOAT=,$HKEYS=,$HLEN=,$HMGET=,$HMSET=,$HSCAN=,$HSET=,$HSETNX=,$HSTRLEN=,$HVALS=,$INCR=,$INCRBY=,$INCRBYFLOAT=,$KEYS=,$LASTSAVE=,$LATENCY=,$LINDEX=,$LINSERT=,$LLEN=,$LPOP=,$LPUSH=,$LPUSHX=,$LRANGE=,$LREM=,$LSET=,$LTRIM=,$MEMORY=,$MGET=,$MIGRATE=,$MONITOR=,$MOVE=,$MSET=,$MSETNX=,$MULTI=,$OBJECT=,$PERSIST=,$PEXPIRE=,$PEXPIREAT=,$PFADD=,$PFCOUNT=,$PFMERGE=,$PSETEX=,$PTTL=,$PUBLISH=,$PUBSUB=,$QUIT=,$RANDOMKEY=,$READONLY=,$READWRITE=,$RENAME=,$RENAMENX=,$REPLICAOF=,$RESTORE=,$RPOP=,$RPOPLPUSH=,$RPUSH=,$RPUSHX=,$SADD=,$SAVE=,$SCAN=,$SCARD=,$SCRIPT=,$SDIFF=,$SDIFFSTORE=,$SELECT=,$SET=,$SETBIT=,$SETEX=,$SETNX=,$SETRANGE=,$SINTER=,$SINTERSTORE=,$SISMEMBER=,$SLAVEOF=,$SLOWLOG=,$SMEMBERS=,$SMOVE=,$SORT=,$SPOP=,$SRANDMEMBER=,$SREM=,$STRLEN=,$SUNION=,$SUNIONSTORE=,$SSCAN=,$SWAPDB=,$SYNC=,$TIME=,$TOUCH=,$TTL=,$TYPE=,$UNLINK=,$UNWATCH=,$WATCH=,$XACK=,$XADD=,$XCLAIM=,$XDEL=,$XGROUP=,$XINFO=,$XLEN=,$XPENDING=,$XRANGE=,$XREAD=,$XREADGROUP=,$XREVRANGE=,$XTRIM=,$ZADD=,$ZCARD=,$ZCOUNT=,$ZINCRBY=,$ZINTERSTORE=,$ZLEXCOUNT=,$ZPOPMAX=,$ZPOPMIN=,$ZRANGE=,$ZRANGEBYLEX=,$ZRANGEBYSCORE=,$ZRANK=,$ZREM=,$ZREMRANGEBYLEX=,$ZREMRANGEBYRANK=,$ZREMRANGEBYSCORE=,$ZREVRANGE=,$ZREVRANGEBYLEX=,$ZREVRANGEBYSCORE=,$ZREVRANK=,$ZSCAN=,$ZSCORE=,$ZUNIONSTORE=,$UNKNOWN=

redis-headless.redis.svc.cluster.local:26379/Interactive: Connecting...
redis-headless.redis.svc.cluster.local:26379: BeginConnectAsync
1 unique nodes specified
redis-headless.redis.svc.cluster.local:26379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:05 to respond...
Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767)
redis-headless.redis.svc.cluster.local:26379/Interactive: Connected 
redis-headless.redis.svc.cluster.local:26379: Server handshake
redis-headless.redis.svc.cluster.local:26379: Authenticating (password)
redis-headless.redis.svc.cluster.local:26379: Auto-configuring...
redis-headless.redis.svc.cluster.local:26379: Sending critical tracer (handshake): PING
redis-headless.redis.svc.cluster.local:26379/Interactive: Writing: PING
redis-headless.redis.svc.cluster.local:26379: Flushing outbound buffer
redis-headless.redis.svc.cluster.local:26379: OnEstablishingAsync complete
redis-headless.redis.svc.cluster.local:26379: Starting read
redis-headless.redis.svc.cluster.local:26379: Auto-configured (SENTINEL) server-type: sentinel
redis-headless.redis.svc.cluster.local:26379: Auto-configured (INFO) version: 6.2.5
redis-headless.redis.svc.cluster.local:26379: Auto-configured (INFO) server-type: sentinel
Response from redis-headless.redis.svc.cluster.local:26379/Interactive / PING: SimpleString: PONG
redis-headless.redis.svc.cluster.local:26379: OnConnectedAsync completed (From command: PING)
All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767)
redis-headless.redis.svc.cluster.local:26379: Endpoint is ConnectedEstablished
redis-headless.redis.svc.cluster.local:26379: Returned with success as Sentinel primary (Source: From command: PING)
Election: Single master detected: redis-headless.redis.svc.cluster.local:26379
redis-headless.redis.svc.cluster.local:26379: Clearing as RedundantMaster
redis-headless.redis.svc.cluster.local:26379: Sentinel v6.2.5, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
redis-headless.redis.svc.cluster.local:26379: int ops=5, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
redis-headless.redis.svc.cluster.local:26379: Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
```

But then, I run into this error.
```
[22:00:31 ERR] R-FAULT sb://my-servicebus.windows.net/my-topic 245aba27-9ded-4b2c-bd6f-3a19572ace63 
...
StackExchange.Redis.RedisConnectionException: Sentinel: Failed connecting to configured master for service: redis-headless
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2414
   at E470.DeployBot.Worker.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__6(IServiceProvider cfg) in /src/Program.cs:line 129
```

Any ideas? I've also tried `ConnectionMultiplexer.Connect()` and passing in `serviceName` value, but no luck. 

I am also curious what the difference is between `ConnectionMultiplexer.Connect()` and `ConnectionMultiplexer.SentinelConnect()`.

I am using StackExchange.Redis version `2.2.62`.

Thank you!

**Comment by jiyoon-koo** [comment]
Oh, wow. I set up redis in the kubernetes cluster using terraform, and completely missed this...

The default master name is `mymaster`... so I had to pass in `serviceName=mymaster` for it to work.

See [this section](https://github.com/bitnami/charts/tree/master/bitnami/redis#redis-sentinel-configuration-parameters) for more details
![image](https://user-images.githubusercontent.com/12419157/129602680-dcec5894-07d3-462e-afad-e3ecd352f8ae.png)

**Comment by mohammed-essa** [comment]
> Oh, wow. I set up redis in the kubernetes cluster using terraform, and completely missed this...
> 
> The default master name is `mymaster`... so I had to pass in `serviceName=mymaster` for it to work.
> 
> See [this section](https://github.com/bitnami/charts/tree/master/bitnami/redis#redis-sentinel-configuration-parameters) for more details ![image](https://user-images.githubusercontent.com/12419157/129602680-dcec5894-07d3-462e-afad-e3ecd352f8ae.png)

Hi,

Sorry @jiyoon-koo,

Can you please share the final configuration and dependency injection code snippet after this change?

Thank you

**Comment by jiyoon-koo** [comment]
@mohammed-essa  sure. my redis-related config in appsettings.json is

``` 
"RedisUrl": "redis.redis.svc.cluster.local", // the "local" redis URL inside the cluster
 "RedisServiceName": "mymaster",
```

i have a separate secrets file where i keep my `RedisPassword` :) 

and my startup.cs (well, program.cs, since it's a worker)

```csharp
services.AddSingleton<IConnectionMultiplexer>(sp =>
                {
                    ConnectionMultiplexer conn;

                    if (hostContext.HostingEnvironment.IsDevelopment())
                    {
                        conn = ConnectionMultiplexer.Connect($"{configsOptions.RedisUrl},password={secretsOptions.RedisPassword}", Console.Out);
                    }
                    else
                    {
                        conn = ConnectionMultiplexer.Connect($"{configsOptions.RedisUrl},password={secretsOptions.RedisPassword},serviceName={configsOptions.RedisServiceName}", Console.Out);
                    }
                    return conn;
                });
```

hope that helps!
