### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: Sentinel: Failed connecting to configured master for service

### ISSUE THREAD

**Issue by jiyoon-koo** [StackExchange/StackExchange.Redis#1853]
Using connection like this in Program.cs

```csharp
 ConnectionMultiplexer conn = 
ConnectionMultiplexer.Connect(
        $"{configsOptions.RedisUrl},
        password={secretsOptions.RedisPassword},
        serviceName={configsOptions.RedisServiceName}", 
        Console.Out);
```

Deployed using Terraform with [this helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis), using with sentinel enabled, and `sentinel.masterSet` value being `redis-master`. 3 nodes in the stateful set

Redis itself seems to start up OK...

```
redis.redis.svc.cluster.local:26379,serviceName=redis-master,password=*****,$NONE=,$APPEND=,$ASKING=,$BGREWRITEAOF=,$BGSAVE=,$BITCOUNT=,$BITOP=,$BITPOS=,$BLPOP=,$BRPOP=,$BRPOPLPUSH=,$CLIENT=,$CLUSTER=,$CONFIG=,$DBSIZE=,$DEBUG=,$DECR=,$DECRBY=,$DEL=,$DISCARD=,$DUMP=,$ECHO=,$EVAL=,$EVALSHA=,$EXEC=,$EXISTS=,$EXPIRE=,$EXPIREAT=,$FLUSHALL=,$FLUSHDB=,$GEOADD=,$GEODIST=,$GEOHASH=,$GEOPOS=,$GEORADIUS=,$GEORADIUSBYMEMBER=,$GET=,$GETBIT=,$GETRANGE=,$GETSET=,$HDEL=,$HEXISTS=,$HGET=,$HGETALL=,$HINCRBY=,$HINCRBYFLOAT=,$HKEYS=,$HLEN=,$HMGET=,$HMSET=,$HSCAN=,$HSET=,$HSETNX=,$HSTRLEN=,$HVALS=,$INCR=,$INCRBY=,$INCRBYFLOAT=,$KEYS=,$LASTSAVE=,$LATENCY=,$LINDEX=,$LINSERT=,$LLEN=,$LPOP=,$LPUSH=,$LPUSHX=,$LRANGE=,$LREM=,$LSET=,$LTRIM=,$MEMORY=,$MGET=,$MIGRATE=,$MONITOR=,$MOVE=,$MSET=,$MSETNX=,$MULTI=,$OBJECT=,$PERSIST=,$PEXPIRE=,$PEXPIREAT=,$PFADD=,$PFCOUNT=,$PFMERGE=,$PSETEX=,$PTTL=,$PUBLISH=,$PUBSUB=,$QUIT=,$RANDOMKEY=,$READONLY=,$READWRITE=,$RENAME=,$RENAMENX=,$REPLICAOF=,$RESTORE=,$RPOP=,$RPOPLPUSH=,$RPUSH=,$RPUSHX=,$SADD=,$SAVE=,$SCAN=,$SCARD=,$SCRIPT=,$SDIFF=,$SDIFFSTORE=,$SELECT=,$SET=,$SETBIT=,$SETEX=,$SETNX=,$SETRANGE=,$SINTER=,$SINTERSTORE=,$SISMEMBER=,$SLAVEOF=,$SLOWLOG=,$SMEMBERS=,$SMOVE=,$SORT=,$SPOP=,$SRANDMEMBER=,$SREM=,$STRLEN=,$SUNION=,$SUNIONSTORE=,$SSCAN=,$SWAPDB=,$SYNC=,$TIME=,$TOUCH=,$TTL=,$TYPE=,$UNLINK=,$UNWATCH=,$WATCH=,$XACK=,$XADD=,$XCLAIM=,$XDEL=,$XGROUP=,$XINFO=,$XLEN=,$XPENDING=,$XRANGE=,$XREAD=,$XREADGROUP=,$XREVRANGE=,$XTRIM=,$ZADD=,$ZCARD=,$ZCOUNT=,$ZINCRBY=,$ZINTERSTORE=,$ZLEXCOUNT=,$ZPOPMAX=,$ZPOPMIN=,$ZRANGE=,$ZRANGEBYLEX=,$ZRANGEBYSCORE=,$ZRANK=,$ZREM=,$ZREMRANGEBYLEX=,$ZREMRANGEBYRANK=,$ZREMRANGEBYSCORE=,$ZREVRANGE=,$ZREVRANGEBYLEX=,$ZREVRANGEBYSCORE=,$ZREVRANK=,$ZSCAN=,$ZSCORE=,$ZUNIONSTORE=,$UNKNOWN=

redis.redis.svc.cluster.local:26379/Interactive: Connecting...
redis.redis.svc.cluster.local:26379: BeginConnectAsync
1 unique nodes specified
redis.redis.svc.cluster.local:26379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:05 to respond...
Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=4,Free=32763,Min=1,Max=32767)
redis.redis.svc.cluster.local:26379/Interactive: Connected 
redis.redis.svc.cluster.local:26379: Server handshake
redis.redis.svc.cluster.local:26379: Authenticating (password)
redis.redis.svc.cluster.local:26379: Auto-configuring...
redis.redis.svc.cluster.local:26379: Sending critical tracer (handshake): PING
redis.redis.svc.cluster.local:26379/Interactive: Writing: PING
redis.redis.svc.cluster.local:26379: Flushing outbound buffer
redis.redis.svc.cluster.local:26379: OnEstablishingAsync complete
redis.redis.svc.cluster.local:26379: Starting read
redis.redis.svc.cluster.local:26379: Auto-configured (SENTINEL) server-type: sentinel
redis.redis.svc.cluster.local:26379: Auto-configured (INFO) version: 6.2.5
redis.redis.svc.cluster.local:26379: Auto-configured (INFO) server-type: sentinel
Response from redis.redis.svc.cluster.local:26379/Interactive / PING: SimpleString: PONG
redis.redis.svc.cluster.local:26379: OnConnectedAsync completed (From command: PING)
All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=4,Free=32763,Min=1,Max=32767)
redis.redis.svc.cluster.local:26379: Endpoint is ConnectedEstablished
redis.redis.svc.cluster.local:26379: Returned with success as Sentinel primary (Source: From command: PING)
Election: Single master detected: redis.redis.svc.cluster.local:26379
redis.redis.svc.cluster.local:26379: Clearing as RedundantMaster
redis.redis.svc.cluster.local:26379: Sentinel v6.2.5, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
redis.redis.svc.cluster.local:26379: int ops=5, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
redis.redis.svc.cluster.local:26379: Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
```

But StackExchange.Redis.RedisConnectionException is thrown when redis is actually accessed by the application:

```
[16:53:09 DBG] Create send transport: sb://my-sb.servicebus.windows.net/MassTransit/Fault--DeployBot.Contracts/DeployApplication--
[16:53:10 DBG] Topic: MassTransit/Fault ()
[16:53:10 DBG] Topic: MassTransit/Fault--DeployBot.Contracts/DeployApplication-- ()
[16:53:10 DBG] Subscription Fault-MassTransit (MassTransit/Fault--DeployBot.Contracts/DeployApplication-- -> sb://mysb.servicebus.windows.net/MassTransit/Fault)
[16:53:11 DBG] SEND sb://mysb.servicebus.windows.net/MassTransit/Fault--DeployBot.Contracts/DeployApplication-- dc4c0000-67c5-f60c-e3b0-08d96c9fd05a MassTransit.Fault<DeployBot.Contracts.DeployApplication>
[16:53:11 ERR] R-FAULT sb://mysb.servicebus.windows.net/DeployBot.Contracts.DeployApplication 2e87a502-a5aa-4d03-a054-0dee86f5585c DeployBot.Contracts.DeployApplication DeployBot.Worker.Consumers.DeployApplicationConsumer(00:00:06.5986513)
StackExchange.Redis.RedisConnectionException: Sentinel: Failed connecting to configured master for service: redis-master
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2414
   at StackExchange.Redis.ConnectionMultiplexer.SentinelMasterConnect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1100
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1029
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1015
   at DeployBot.Worker.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__7(IServiceProvider cfg) in /src/Program.cs:line 142
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at MassTransit.ExtensionsDependencyInjectionIntegration.Registration.DependencyInjectionScopeServiceProvider.GetService[T]()
   at MassTransit.ExtensionsDependencyInjectionIntegration.ScopeProviders.DependencyInjectionConsumerScopeProvider.MassTransit.Scoping.IConsumerScopeProvider.GetScope[TConsumer,T](ConsumeContext`1 context)
   at MassTransit.Scoping.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next)
   at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.GreenPipes.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next)
[16:53:11 DBG] Queue: DeployBot.Contracts.DeployApplication_error (dead letter)
[16:53:11 INF] MOVE sb://mysb.servicebus.windows.net/DeployBot.Contracts.DeployApplication 997b0a92-647b-4e97-8ed4-99dae396af8d DeployBot.Contracts.DeployApplication_error Fault: Sentinel: Failed connecting to configured master for service: redis-master
```

Seems similar to [this issue](https://github.com/StackExchange/StackExchange.Redis/issues/1518) but there was no resolution on that issue / workaround that I could find.

**Comment by omegazeng** [comment]
helm install redis 
https://artifacthub.io/packages/helm/bitnami/redis  version 6.2.6
replication with sentinel enabled
3 replicas
ProtocalFailed

**Comment by jiyoon-koo** [comment]
i was able to find a fix for this - when redis gets spun up with terraform, it registers with the default service name `mymaster` and not the name i overrode it with in the terraform config, `redis-master`. 

once i changed my .NET app config to say `mymaster`, this error went away.
