### ISSUE TITLE
Connecting to Google-hosted Redis with StackExchange not working with AuthString

### ISSUE THREAD

**Issue by thzois** [StackExchange/StackExchange.Redis#1895]
Hello! 

We are using `StackExchange.Redis` version `2.2.79` in a .NET Core 5.0 project, to connect to a Google Cloud Platform Redis instance (a.k.a Memorystore).

We are not using `SSL` for the connections, we just use what Google calls `AuthString` which is practically the password. We face issues when we are trying to connect to our instance using the library, while with `redis-cli -a <password>` the connection succeeds and we are able to see the contents. 

The exception that we get in the code is:
```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1194
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1061
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1036
```

For the connection through the library, we are using the following settings:
```
  ConfigurationOptions options = ConfigurationOptions.Parse("127.0.0.1:6379");
  options.Password = "auth-string-provided-from-gcp";
  options.AbortOnConnectFail = false;
  options.Ssl = false;
  _redisConnection = ConnectionMultiplexer.Connect(options);
```

**P.S:** If we disable authentication in GCP for our Redis instance, the connection through the library succeeds.

**Comment by th-zois** [comment]
Hello @mgravell, are there any updates on this?
