### ISSUE TITLE
System.AggregateException while using ConnectionTimeOut

### ISSUE THREAD

**Issue by m-breedveld** [StackExchange/StackExchange.Redis#190]
Hello I get the System.AggregateException while using **ConnectionTimeOut** lower then 1000ms in combination with unreachable host.
# Exception

```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at StackExchange.Redis.ConnectionMultiplexer.<>c__DisplayClass2c.<ConnectImpl>b__29() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 765
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: System.ObjectDisposedException
       HResult=-2146232798
       Message=Cannot access a disposed object.
Object name: 'NLRO02-PC0113'.
       Source=StackExchange.Redis
       ObjectName=NLRO02-PC0113
       StackTrace:
            at StackExchange.Redis.ConnectionMultiplexer.GetServerEndPoint(EndPoint endpoint) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 802
            at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__30.MoveNext() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1356
       InnerException:
```
# Example code

Note: The typo in **RemoteAddress** is on purpose to fake an unreachable host.

``` C#
using System;
using StackExchange.Redis;

namespace StackExchangeTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var RemoteAddress = "localeehost";
            var RemotePort = 6379;
            var ConnectRetry = 2;
            var ConnectTimeOut = 20;

            ConfigurationOptions configurationOptions = new ConfigurationOptions
            {
                EndPoints =
                {
                     { RemoteAddress, RemotePort }
                },
                ConnectTimeout = ConnectTimeOut,
                ConnectRetry = ConnectRetry
            };

            while(true)
            {
                try
                {

                    ConnectionMultiplexer.Connect(configurationOptions);
                }
                catch(Exception exception)
                {
                    Console.WriteLine("Exception " + exception);
                }
            }

            Console.ReadKey();
        }

    }
}

```

**Comment by NickCraver** [comment]
I can't repro this locally, it's all RedisConnectionException:

> It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout

Can you still repro this on the current version?
