### ISSUE TITLE
Give chance of reconnecting to another server on failures like LOADING

### ISSUE THREAD

**Issue by eduardobr** [StackExchange/StackExchange.Redis#1913]
In scenarios where we have a connection with multiple redis server addresses, or even one address that round-robin between Redis instances (some proxy or load balancer), we should have the chance to switch to a different instance immediately in case we get an exception with `LOADING` state.
We can safely retry on `LOADING` status, but not force reconnecting will likely keep returning same error for some time until replication is done.

An example of use case is when we have multiple masters and some of them may restart, causing replicas to return `LOADING` during the full resync, or while replica is starting.

This change doesn't need to be implicit, especially because it doesn't bring benefit in some setups (let's say you have a single master or replica). If we had a way to easily flag our intent to force reconnect, that can be solved by user code handling exceptions, which IMHO is very acceptable and explicit.
Otherwise, some simple flag "ReconnectOnLoadingResponse" where default is false.

**Comment by NickCraver** [comment]
What exception are you getting today when this happens? I'm certainly open to improving it - what we're working on in 2.5x is "buffer and retry" (up until the timeout) on _a_ connection (per server). An evolution of that we're looking at beyond that is buffer _and be willing to flush to another viable connection_, which would be this case potentially but I want to ensure the error we're throwing today is actually what happens here. More info would help us get this right!

**Comment by eduardobr** [comment]
@NickCraver we get a StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
Thank you

**Comment by Tagarito** [comment]
To add a little bit to this issue

Setup:
6 Redis instances version 7.0.5 compiled running in local WSL Ubuntu 20.04
StackExchange.Redis 2.6.70
Cluster mode with 3 masters and 3 replicas
Each shard with about 1Gb

Expected behavior:
- Shutdown slave instance
- Bring back slave instance
- First request made to cache fails with `LOADING Redis is loading the dataset in memory`
- Subsequent requests succeed

Actual behavior:
- When slave instance is brought back continuos requests are made to instance in LOADING state (as can be seen in stacktrace)

Expected handling scenario:
- Request is made to redis instance that fails with a loading error
- Redis instance is "blacklisted" from being sent redis requests
- On next `ConfigCheckSeconds` logic an health check is made to verify if it's still loading (Ping)
- When instance responds to health check with a non LOADING error it is added back to the redis instances pool

In our case we have seen this error pop up in production in 15-20Gb shards on VM maintenance.
I wouldn't mind your second solution `buffer and be willing to flush to another viable connection`.
I also understand that there might be requests queued up for said instance but we would be happy with just failing those requests but making sure that subsequent requests would not fail.
Also since this is mostly a startup issue (atleast for use) I was wondering why is the node added to cluster instance pool in the first place if it's not ready to receive requests?


Configuration file:
```
port 6000
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly no
save ""
repl-diskless-sync yes
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-allow-reads-when-down yes

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 4096mb 2048mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
```

Cluster nodes:
```
ec116239feff661bb17011ba9e87c49153e3f88f 127.0.0.1:6000@16000 myself,master - 0 1668090643000 1 connected 0-5460
8fde47357db78f6f2daa8a06d0f2a95dbc7fc574 127.0.0.1:6001@16001 master - 0 1668090645587 2 connected 5461-10922
cf6214bbcca94a606c4c17799528c35dd508db23 127.0.0.1:6002@16002 master - 0 1668090644000 8 connected 10923-16383
1108b0c235a0541d141934212309ee047679f484 127.0.0.1:6004@16004 slave ec116239feff661bb17011ba9e87c49153e3f88f 0 1668090644000 1 connected
87d3560f70efc1caa816bcc65beca799dd0301b6 127.0.0.1:6005@16005 slave 8fde47357db78f6f2daa8a06d0f2a95dbc7fc574 0 1668090644985 2 connected
71530f79e01d0570f0d5bfaa92d74a1139186580 127.0.0.1:6003@16003 slave cf6214bbcca94a606c4c17799528c35dd508db23 0 1668090644583 8 connected
```

Code:
```
using StackExchange.Redis;

var options = new ConfigurationOptions
{
    EndPoints = { "localhost:6000", "localhost:6001", "localhost:6002", "localhost:6003", "localhost:6004", "localhost:6005" },
    // ConfigCheckSeconds = 60,
    ConnectTimeout = 50,
    AbortOnConnectFail = false
};

ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(options);
Console.WriteLine(redis.Configuration);
Random rand = new Random();
IDatabase db = redis.GetDatabase();
string value = "abcdefg";

for (int i = 0; i < 500000000; i++)
{
    if (i % 1000 == 0)
    {
        Console.WriteLine(i);
    }
    try
    {
         var a = await redis.GetDatabase().StringSetAsync(i.ToString(), value);
         var key = rand.Next(i);
         var b = await redis.GetDatabase().StringGetAsync(key.ToString(), CommandFlags.PreferReplica);
    }
    catch (Exception e)
    {
        Console.WriteLine(i);
        Console.WriteLine($"Exception, {e}");
    }
}
```

Stacktrace:
```
17676
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17683
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17693
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17695
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17696
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17701
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17704
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17706
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17707
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17708
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17710
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17721
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17723
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17726
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17727
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17733
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17741
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17742
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17743
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17747
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17749
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17751
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17753
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17757
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17758
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17764
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17768
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17769
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17772
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17773
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17776
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17782
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17785
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17788
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17789
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17793
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17795
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17796
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17797
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17802
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17803
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17804
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17808
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17813
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17818
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17823
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17824
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17828
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17830
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17832
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17835
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17836
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17839
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17843
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
17849
Exception, StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
   at Program.<Main>$(String[] args) in C:\Users\Tiago\source\repos\RedisPopulate\RedisPopulate\Program.cs:line 32
```

**Comment by Dunge** [comment]
Encountered this today (using StackExchange.Redis Version 2.6.111)

> 2024-05-19 21:45:20.237	Exception: LOADING Redis is loading the dataset in memory
> 2024-05-19 21:45:20.237	 ---> StackExchange.Redis.RedisServerException: LOADING Redis is loading the dataset in memory
> 2024-05-19 21:45:20.237	   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2099
> 2024-05-19 21:45:20.237	   at StackExchange.Redis.RedisDatabase.SortedSetRangeByRank(RedisKey key, Int64 start, Int64 stop, Order order, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2086

Since this doesn't seem to be handled in the lib, what is the recommendation here? Wrap all our Redis request in a try/catch block handling this error and using a lib like Polly to do retries?
