### ISSUE TITLE
Client connection issue randomly

### ISSUE THREAD

**Issue by gurc4n** [StackExchange/StackExchange.Redis#1986]
I have a redis server and client applications are using StackExchange.Redis nuget package.
Randomly I am losing connection to Redis server with the exception below:

Exception in the client : 
[13:11:19.895] [ERR] { ThreadId: 60 }  No connection is active/available to service this operation: GET CH:coreGetCNCDeviceByMachine-1947848840; An established connection was aborted by the software in your host machine, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXXXXXXXXXXXX, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=32765,Min=16,Max=32767), v: 2.2.88.56325
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET CH:coreGetCNCDeviceByMachine-1947848840; An established connection was aborted by the software in your host machine, mc: 1/1/0, mgr: 10 of 10 available, clientName: EPDI-WEB01b71cfb44-36bf-4694-8a03-23c35315ff4c, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=32765,Min=16,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: SocketFailure (ReadEndOfStream, 0-read, last-recv: 0) on XXXXXXXXXXX/Subscription, Flushing/NotStarted, last: SUBSCRIBE, origin: OnEstablishingAsyncAwaited, outstanding: 3, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.88.56325 ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 74
   at Pipelines.Sockets.Unofficial.SocketConnection.<DoSendAsync>d__81.MoveNext() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Send.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at Pipelines.Sockets.Unofficial.SocketConnection.WrappedWriter.FlushAsync(CancellationToken cancellationToken) in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.cs:line 432
   at StackExchange.Redis.PhysicalConnection.FlushAsync() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 286
   at StackExchange.Redis.ServerEndPoint.<HandshakeAsync>d__120.MoveNext() in /_/src/StackExchange.Redis/ServerEndPoint.cs:line 885
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StackExchange.Redis.ServerEndPoint.<OnEstablishingAsyncAwaited>d__97.MoveNext() in /_/src/StackExchange.Redis/ServerEndPoint.cs:line 566
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2863
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2433
   at CommonUtils.RedisWrapper.StringGet(String key, String prefix) in

**Comment by gurc4n** [comment]
This is the exceptions in the server:

[51188] 10 Feb 14:23:48.685 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:49.063 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:49.693 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:50.695 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:51.707 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:52.722 # Error registering fd event for the new client: No error (conn: fd=15163)
[51188] 10 Feb 14:23:53.723 # Error registering fd event for the new client: No error (conn: fd=15163)

**Comment by gurc4n** [comment]
I will give it a try, thank you very much.

By the way, is this normal?
I have 19 clients but 3263 connections. I don't do any connection recovery kind of action.
ConnectionMultiplexer and IDatabase are shared objects in my code. 

![image](https://user-images.githubusercontent.com/4612775/153490763-f51390a3-a35d-4bfa-aa83-63b89ed0e27c.png)

**Comment by NickCraver** [comment]
@gurc4n what am I looking at? Assume I know nothing about these counters (because I don't!) - is this from the server's point of view? A total counter of connections ever? If so, across what time period? Everything you can tell me about them helps me say if it's normal...without context: no idea :)

**Comment by gurc4n** [comment]
The period is about 2-3 hours :) I forgot to mention it. I am wondering if I do so many calls or something wrong in the calls and getting the server to a freeze or something like that?

**Comment by NickCraver** [comment]
@gurc4n Those state are _since the instance was restarted_. Do those numbers look reasonable? Yeah sure, I guess - it's _highly_ contextual. How many builds have happened, how many instances, how many multiplexers, etc. 

For what it's worth, what you may want is `info clients` which shows _current_ connections.

**Comment by gurc4n** [comment]
Thanks Nick, it looks like I had an unstable port of Redis. The library is good, connection count is good. Sorry for the interruption.

**Comment by NickCraver** [comment]
@gurc4n Glad you got it figured! I appreciate the update :)
