### ISSUE TITLE
Microsoft.AspNetCore.Session.DistributedSession not working in .NET 6

### ISSUE THREAD

**Issue by navtek** [StackExchange/StackExchange.Redis#2006]
Hi, I've been experiencing an issue with the DistributedSession middleware in .NET 6. I'm using sessions `services.AddSession()`, which I had in place since .NET Core 2.1 all the way to .NET 5, but with .NET 6 it's just not working for me.

To test if it was my application or something else, I created a test ASP .NET Core application from a project template, with all the required minimum items to work. After running a few tests I found that the issue is present in this new test application as well.

I have to point out that if I use `services.AddDistributedMemoryCache()` it works as expected, the sessions are stored and I'm able to retrieve them, but when I switch back to try and use Redis it doesn't work.

Here is the error that I am getting:
`Microsoft.AspNetCore.Session.DistributedSession: Error: Session cache read exception, Key:abcde-12345.......

System.Threading.ThreadAbortException: System error.
   at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2801
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.HashGet(RedisKey key, RedisValue[] hashFields, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 324
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefresh(String key, Boolean getData)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.Get(String key)
   at Microsoft.AspNetCore.Session.DistributedSession.Load()`

The middleware DOES work, as I have additional data caching in place and all of that makes it to Redis and back, it's only sessions I'm having issues with, hence I ask here first to see if it's something that the library handles or if it's something coming from the .NET Session API.

Here are the versions I'm using on my current test:

.NET 6 version: 6.0.200
StackExchangeRedis version: 6.0.2
Redis version: 6.2.6

Test connection string: `localhost:6379,abortConnect=false`

Please let me know if there are any additional details and/or some testing you need from my end.

Thank you.

**Comment by NickCraver** [comment]
I'm not sure what's causing a `ThreadAbortException`, but it wouldn't be expected that we handle it. That's going to cause anything, anywhere to go boom when it happens - in this case it's a redis command in flight. In short: what you're seeing is the victim here - I'm not sure what's killing threads inside your app or the best way to diagnose...I honestly thought you _couldn't_ throw one in .NET 6+.

**Comment by synapsechain** [comment]
I have the same issue

**Comment by NickCraver** [comment]
@synapsechain You'll want to see what's causing the upstream thread abort...that's bad, and it's going to result in downstream bad like this :)

**Comment by synapsechain** [comment]
@NickCraver @navtek It seems that it reproduces only after clearing the session and don't delete session cookie
It tries to load cleared session and gets exception

**Comment by NickCraver** [comment]
I'm going to close this out as it's not a client issue - for anyone hitting this: find what's causing thread aborts - that's going to cause all sorts of collateral damage and largely why they are removed in newer .NET versions.
