### ISSUE TITLE
RedisConnectionException when trying to connect to AWS Redis cluster with multiple shards

### ISSUE THREAD

**Issue by mario-pina-cko** [StackExchange/StackExchange.Redis#2038]
Hello,

We are using an AWS ElastiCache Redis cluster as a cache mechanism, and we are using the `ConnectionMultiplexer` to create the connection as a singleton at the start of our application. This means that the number of open connections is low at any given time (way below the limit of AWS Redis).

Recently we started getting intermittent errors when connecting to the Redis cluster (during startup):
```
Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on clustercfg._redis-cluster-name_.3itdzk.euw1.cache.amazonaws.com:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433
```

We don't get this exception all the time, and eventually, when we retry for a few minutes, we end up connecting and the application would behave normally (read and write operation would succeed without issue). 

After some investigation, we noticed that this error only happens when we have more than 1 shard on our cluster, and we were able to reproduce this on our test environment by having a Redis cluster with 7 shards (each with 3 nodes (1 master and 2 replicas)). 

We are connecting to the AWS ElastiCache Configuration Endpoint URL as per the AWS documentation. 

After a few more tests, we also noticed that by setting the Redis client's ConfigurationOptions.Endpoints with just one of the shard's URLs (instead of using the ElastiCache Configuration URL), the error would no longer happen and the client would successfully connect all the time. Strangely enough, reads and writes would happen on all shards, not just the shard used on the endpoints configuration. 

A few questions I would like to ask:

- Is Redis cluster mode supported by StackExchange.Redis client?

- Any idea why ConnectionMultiplexer would intermittently fail to connect when the cluster's configuration URL is used and multiple shards exist on the cluster?

- How does the StackExchange.Redis behave when configured with an ElastiCache Configuration URL? Does it become aware of all the shards and subsequently try to connect to each of them? Or does this routing happen at the server-side?

- What's the expected behavior of ConnectionMultiplexer when only the URLs of a specific shard are used to connect to? Is it expected that the client is still able to read/write from all other shards?

Thank you in advance,
Mário Pina

**Comment by NickCraver** [comment]
Hey Mario - before debugging further, please upgrade to the latest version of the client which has a lot of enhancements and fixes to connections specifically. In general, I'd advise this when filing any issue :)

**Comment by mario-pina-cko** [comment]
Hi Nick,

I've just tried with the newest version 3.5.43, and while the error messages have changed, the error is still there. The new error is:

```
Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
```

Using the AbortOnConnectFail=false, as suggested in the error message, is not a solution for us, because this will change the error from the startup of the application to the actual Redis call. In any case, the error still ocurrs.

**Comment by NickCraver** [comment]
@mario-pina-cko awesome - now we can get _much_ better connection logging - can you pass a TextWriter into the connect method and show me the output here? That'll give a much better idea of what's going on.

**Comment by mario-pina-cko** [comment]
Hey Nick,

I've just added the TextWritter into the connect method. Here is the output:

```
2022-03-17 10:30:27 Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
2022-03-17 10:30:27 at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1163
2022-03-17 10:30:27 at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1028
2022-03-17 10:30:27 at OurNamespace.Api.Infrastructure.Extensions.DependencyInjection.ServiceCollectionExtensions.AddIdempotencyServices(IServiceCollection services, IConfiguration configuration, IConnectionMultiplexer& redisConnection) in /app/src/OurNamespace.Api.Infrastructure/Extensions/DependencyInjection/ServiceCollectionExtensions.cs:line 49
2022-03-17 10:30:27 at OurNamespace.Api.Startup.ConfigureServices(IServiceCollection services) in /app/src/OurNamespace.Api/Startup.cs:line 141
2022-03-17 10:30:27 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2022-03-17 10:30:27 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
2022-03-17 10:30:27 at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
2022-03-17 10:30:27 at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
2022-03-17 10:30:27 at Microsoft.Extensions.Hosting.HostBuilder.Build()
2022-03-17 10:30:27 at OurNamespace.Api.Program.Main(String[] args) in /app/src/OurNamespace.Api/Program.cs:line 20
2022-03-17 10:30:27 10:30:27.1438: Connection failed: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379 (Subscription, UnableToConnect): UnableToConnect on clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.5.43.42402
2022-03-17 10:30:27 10:30:27.1439: Connection failed: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379 (Subscription, UnableToConnect): UnableToConnect on clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.5.43.42402
2022-03-17 10:30:27 10:30:27.1439: Connection failed: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379 (Interactive, UnableToConnect): UnableToConnect on clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.5.43.42402
2022-03-17 10:30:27 10:30:27.1397: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
2022-03-17 10:30:27 10:30:27.1397: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
2022-03-17 10:30:27 10:30:27.1381: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
2022-03-17 10:30:27 10:30:27.1367: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: Standalone v3.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Disconnected; not in use: DidNotRespond
2022-03-17 10:30:27 10:30:27.1359: Endpoint Summary:
2022-03-17 10:30:27 10:30:27.1346: Election summary:
2022-03-17 10:30:27 10:30:27.1346: Election: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379 had no tiebreaker set
2022-03-17 10:30:27 10:30:27.1346: Election: No masters detected
2022-03-17 10:30:27 10:30:27.1295: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767), POOL: (Threads=4,QueuedItems=1,CompletedItems=18)
2022-03-17 10:30:27 10:30:27.1298: Endpoint summary:
2022-03-17 10:30:27 10:30:27.1299: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: Endpoint is Connecting
2022-03-17 10:30:27 10:30:27.1299: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: Returned, but incorrectly
2022-03-17 10:30:27 10:30:27.1283: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: OnConnectedAsync completed (Disconnected)
2022-03-17 10:30:27 10:30:27.1183: Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), POOL: (Threads=3,QueuedItems=0,CompletedItems=16)
2022-03-17 10:30:27 10:30:27.1134: Allowing 1 endpoint(s) 00:00:05 to respond...
2022-03-17 10:30:27 10:30:27.1119: 1 unique nodes specified (with tiebreaker)
2022-03-17 10:30:27 10:30:27.1127: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: OnConnectedAsync init (State=Connecting)
2022-03-17 10:30:27 10:30:27.1078: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379: BeginConnectAsync
2022-03-17 10:30:27 10:30:27.0937: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379/Interactive: Connecting...
2022-03-17 10:30:27 10:30:27.0875: clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379,ssl=True,connectRetry=0
2022-03-17 10:30:27 10:30:27.0497: Connecting (sync) on .NET Core 3.1.23 (StackExchange.Redis: v2.5.43.42402)
```

Thank you for your assistance.

**Comment by mario-pina-cko** [comment]
Hi @NickCraver,

Have you had the chance to look into this issue since my last comment?

Thank you for your assistance, once again.

**Comment by NickCraver** [comment]
Just getting caught up tonight amongst other stuff - from your logs it looks like indeed we can't reach `clustercfg.redis-cluster-name.xifxko.euw1.cache.amazonaws.com:6379` - I'd be looking at firewall issues here as a best guess. To validate, you can try `redis-cli` from the same system and see it it can connect to the same points. If it can, that's super interesting.

**Comment by mario-pina-cko** [comment]
Hi Nick,

Testing via redis-cli it was something we have already done in the past and we were always able to connect.

We also discarded firewall issues, because we only see this error happening when we increase the number of shards in the Redis cluster. With only 1 shard we don't see the error, and if this was a firewall issue it should still happen in that scenario.

**Comment by AnthonyGarriga** [comment]
@mario-pina-cko Have you found any workaround by any chance? We're experiencing the same type of issue but with a MemoryDB Redis cluster in AWS. The connection fails when we have more than 1 node in the cluster, but if we wait a few minutes and restart the application several times it suddenly starts working. If we try with one shard and one node it works just fine. We're using the cluster URL endpoint when connecting to the cluster.

**Comment by mario-pina-cko** [comment]
@AnthonyGarriga The workaround is the one described in the main post. I would pick one of the shards (usually the first one), and then I would use all the node URLs of that shard on the ConfigurationOptions.Endpoints property of the Multiplexer. This would still make it so that the StackExchange would write to all shards, not just the shards that was picked to get the URL's from.
We've contacted AWS and its intended that this workaround works that way. Their message was:

> 1) Is it expected that when using the nodes URLs of a specific shard we are still able to read/write from all other shards?
> 
> It is the expected behaviour.
> In fact, if you resolve the configuration endpoint, you will see that the IP addresses of all your nodes are returned.
> Example, my own test cluster from my account:
> $ dig +short test.fpieng.clustercfg.euw1.cache.amazonaws.com
> 172.31.2.13
> 172.31.2.110
> 172.31.2.160
> 172.31.2.177
> 172.31.2.195
> 172.31.1.29
> 172.31.1.77
> 172.31.1.105
> 172.31.1.242
> 
> The reason behind this is that clients (libraries, redis-cli) will select one address and connect to that node.
> Which one is selected depends on the library, they usually either use the first returned IP or a random one.
> 
> Once the client is connected, it will query the cluster's topology (usually with the 'CLUSTER NODES' command).
> This way they will know of all the nodes in the cluster, their roles (master, replica) and the shards' locations.
> Based on this information, the client can send the read/write commands to the appropriate nodes.
> 
> By initiating the connection with a node endpoint, you are not changing the process fundamentally, just forcing the cluster discovery to be performed via that specific node.
> 
> 
> 2) What are the advantages of using the configuration URL instead of using the nodes URLs?
> 
> Node endpoints can change, cluster configuration endpoints cannot.
> The node endpoints are bound to the nodes themselves and there are cases when a node is replaced (upgrade, scaling, health issues).
> The configuration endpoint however is bound to the lifetime of the cluster. If a node replacement happens, the endpoint is updated, so it will always return the IPs of the active nodes.
> This is how the service ensures that such activities can be performed without necessitating any changes to be made on the application end.

**Comment by anilvkumar** [comment]
we have crated ElastiCache ( redis cluster ) and we would like to integrate ElastiCache ( redis cluster ) through secrets manager in our code (.net ), can any one help on this.

we have integrated RDS in our code through secrets manager and we are trying to achieve the same using ElastiCache ( redis cluster ) , please advise if its possible.

**Comment by aksrxl** [comment]
Do we know the solution yet ?
@mario-pina-cko i still have the same issue intermittently even when using the node endpoints from one of the shards.  Have you found a fix yet  or still going around with the workaround from aws? 

Is anyone aware of any other library where we don not have this issue ?

**Comment by Lacutas82** [comment]
Was having this issue, and the resolution for us was the DHCP Option Set which was attached to the VPC.  It was unable to resolve the ElastiCache DNS name.
