### ISSUE TITLE
System.ArgumentException: A null value is not valid in this context

### ISSUE THREAD

**Issue by danbudworthmead** [StackExchange/StackExchange.Redis#2058]
When calling to HashSetAsync I get this error:
```
System.ArgumentException: A null value is not valid in this context
   at StackExchange.Redis.RedisValue.AssertNotNull()
   at StackExchange.Redis.Message.Create(Int32 db, CommandFlags flags, RedisCommand command, RedisKey& key, RedisValue[] values)
   at StackExchange.Redis.RedisDatabase.GetHashSetMessage(RedisKey key, HashEntry[] hashFields, CommandFlags flags)
   at StackExchange.Redis.RedisDatabase.HashSetAsync(RedisKey key, HashEntry[] hashFields, CommandFlags flags)
```

This is the relevant code
```
await _database0.HashSetAsync(new RedisKey($"ImpostorRedis{code}"), new HashEntry[]
{
    new("map", map),
    new("impostors", impostors),
    new("language", language),
    new("in_progress", inProgress),
    new("player_count", playerCount),
    new("player_max", playerMax),
    new("public", isPublic),
    new("host_name", hostName),
    new("list_name",  listName),
    new("node", node),
    new("data", data),
    new("game_version", gameVersion), 
    new("last_updated", lastUpdated)
}, CommandFlags.FireAndForget);
```

I am not sure what it thinks is null

**Comment by mgravell** [comment]
I do agree we could do a better job of telling you the key (if one) of the value that is `null`, but ultimately: you should be able to investigate this by simply finding which of `map`, `imposters`, ..., `lastUpdated` is `null`

**Comment by danbudworthmead** [comment]
> but ultimately: you should be able to investigate this by simply finding which of map, imposters, ..., lastUpdated is null

Ah I was thinking it means the new RedisKey($"ImpostorRedis{code}") was null!
Thank you, I'll add some code in and push it up to my server.
