### ISSUE TITLE
Transient error connecting to Redis Sentinel

### ISSUE THREAD

**Issue by bjsmiley** [StackExchange/StackExchange.Redis#2142]
### Issue
I have a .net process in a k8s pod that fires every minute. Roughly half the time it fails to connect to the Redis Sentinel in the k8s cluster. The weird part is that this is **transient and only inconsistently fails**. Know of any reason the ConnectionMultiplexer may fail to connect to Sentinel sometimes but succeed other times? Any help is greatly appreciated.

I've attached the StackExchange.Redis logs down below, but nothing seems unusual, just that it continuously connects in a loop then stops. 

### Exception
```
Unhandled exception. StackExchange.Redis.RedisConnectionException: Sentinel: Failed connecting to configured primary for service: masterset
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs:line 229
   at StackExchange.Redis.ConnectionMultiplexer.SentinelPrimaryConnect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs:line 130
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 675
   at App.Core.Cache.Redis.RedisInstance.<>c__DisplayClass7_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at App.Core.Cache.Redis.RedisInstance.get_Connection()
   at Program.<Main>$(String[] args)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

### Configuration Information
StackExchange.Redis: `2.5.61`

Connection String: `redis-ha:26379,serviceName=masterset,ssl=True,abortConnect=False,connectTimeout=15000`

Redis/Sentinel version `6.2.7` (Using bitnami/redis helm chart)

<details>
  <summary>redis-ha-values.yaml (helm values file if helpful)</summary>
  
  ```yaml
architecture: replication
commonAnnotations:
  linkerd.io/inject: enabled

auth:
  enabled: true
  sentinel: true
  password: ""

master:
  podAnnotations:
    linkerd.io/inject: enabled
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  resources:
    limits:
      memory: "500Mi"
      cpu: "0.4"
    requests:
      memory: "200Mi"
      cpu: "0.2"
  podAntiAffinityPreset: soft

replica:
  podAnnotations:
    linkerd.io/inject: enabled
  replicaCount: 3
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  resources:
    limits:
      memory: "350Mi"
      cpu: "0.04"
    requests:
      memory: "200Mi"
      cpu: "0.02"

sentinel:
  enabled: true
  masterSet: masterset
  downAfterMilliseconds: 30000
  failoverTimeout: 180000
  podAnnotations:
    linkerd.io/inject: enabled
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
  resources:
    limits:
      memory: "350Mi"
      cpu: "0.04"
    requests:
      memory: "200Mi"
      cpu: "0.02"

pdb:
  create: true
  minAvailable: 1

tls:
  enabled: true
  existingSecret: redis-ha-tls
  certFilename: tls.crt
  certKeyFilename: tls.key
  certCAFilename: ca.crt
  authClients: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  ```
</details>

### StackExchange.Redis Logs
[redis-sentinel-connection-failure.log](https://github.com/StackExchange/StackExchange.Redis/files/8690698/redis-sentinel-connection-failure.log)

**Comment by bjsmiley** [comment]
Looks like this is a server side error. completely reinstalling bitnami/redis fixes the issue.
