### ISSUE TITLE
Local only: ObjectDisposedExceptions and occasional timeouts

### ISSUE THREAD

**Issue by taylorjp** [StackExchange/StackExchange.Redis#2227]
Hello!  Hoping for some help with an issue we're seeing only on one local dev machine.  Maybe someone here has an idea?

Everything works fine when deployed to a test/staging environment, and even seems to work fine on other local machines, AND was working fine just a couple of days ago.  We have been unable to identify any changes that might've started this behavior.

The setup is pretty simple:
- Local redis running in docker container on MacOS Monterey (12.5.1) via simple docker run script with no special params
- .NET 6 console application running in Rider, writing and reading from Redis using a singleton ConnectionMultiplexer to share the connection
- StackExchange.Redis v2.5.61 (although upgrading to 2.6.48 has no effect on these results)

The behavior:
- It appears that the multiplexer is getting disposed at seemingly random times throughout the process, even though as far as I can tell we are not disposing it.  Ignoring the errors allows the program to continue because we're performing retries, but that can cause other issues like timeouts eventually.

Here are some of the exceptions we're seeing, with stack traces:
`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at StackExchange.Redis.PhysicalConnection.Shutdown() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 251`
   
   `System.Net.Sockets.SocketException (89): Operation canceled
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 86
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 74
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.Receive.cs:line 64`

`System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Pipelines.Sockets.Unofficial.SocketConnection.WrappedReader.AdvanceTo(SequencePosition consumed, SequencePosition examined) in /_/src/Pipelines.Sockets.Unofficial/SocketConnection.cs:line 398
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1607`

Sometimes, we also get some timeouts.  Again, this behavior does not occur in other environments.  That's not to say it's not a code issue that is just not manifesting elsewhere, but I'm just not sure what to check at this point.

Any help would be greatly appreciated!

**Comment by NickCraver** [comment]
I'm very curious about this exception:
```
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'. at System.Net.Sockets.Socket.ThrowObjectDisposedException() at System.Net.Sockets.Socket.Shutdown(SocketShutdown how) at StackExchange.Redis.PhysicalConnection.Shutdown() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 251
```
...because we explicitly capture that in Shutdown just in case via:
```
try { socket.Shutdown(SocketShutdown.Both); } catch { }
```
...so are you seeing first chance exceptions in your IDE perhaps?

**Comment by taylorjp** [comment]
Thanks so much for the quick response!

Yes, it does look like I had CLR exceptions enabled.  Other dev machines appear to not have those enabled.  I'm not sure how this setting changed, but it looks like that allows it to run now.  Are these exceptions safe to ignore, or are they indicative of a potential issue in our code?

Example of setup causing these exceptions:
![Screen Shot 2022-08-23 at 11 22 17 AM](https://user-images.githubusercontent.com/36546925/186197680-9bb24d09-0b79-4831-aa5c-bd176bfd0311.png)

**Comment by NickCraver** [comment]
Basically, it'll stop on anything (even if it's captured). That's neither wrong or right, just need to understand what you're observing so you can sanity check accordingly :) I don't see anything wrong here, you're just observing some inside-the-bits noise.

**Comment by taylorjp** [comment]
Yea, that makes sense.  Now I know what to check for next time!  Thanks again for such a quick response on this.
