### ISSUE TITLE
RedisTimeoutException on SUBSCRIBE

### ISSUE THREAD

**Issue by xsoheilalizadeh** [StackExchange/StackExchange.Redis#2303]
I'm getting following timeouts while one of the libraries trying to subscribe to redis, I'm using the default configuration.

This is my thread pool metric while these time out occurred and it's coming from dotnet runtime event counter.
![image](https://user-images.githubusercontent.com/22220356/202234726-f9ba3796-a440-418f-be40-6530389c0646.png)

```
StackExchange.Redis.RedisTimeoutException: Timeout performing SUBSCRIBE (5000ms), inst: 0, qu: 1, qs: 3, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 84, in-pipe: 0, out-pipe: 0, serverEndpoint: buzzinga-redis-master.svc.cluster.local.:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: operation-9674dd458-9jg9j(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=77,Free=32690,Min=4,Max=32767), POOL: (Threads=77,QueuedItems=38,CompletedItems=673), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1865
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisSubscriber.EnsureSubscribedToServer(Subscription sub, RedisChannel channel, CommandFlags flags, Boolean internalCall) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 381
   at StackExchange.Redis.RedisSubscriber.Subscribe(RedisChannel channel, Action`2 handler, ChannelMessageQueue queue, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 369
   at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 353
   at EasyCaching.Bus.Redis.DefaultRedisBus.BaseSubscribe(String topic, Action`1 action)
   at EasyCaching.Core.EasyCachingAbstractBus.Subscribe(String topic, Action`1 action)


StackExchange.Redis.RedisTimeoutException: Timeout performing SUBSCRIBE (5000ms), inst: 0, qu: 1, qs: 3, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 84, in-pipe: 0, out-pipe: 0, serverEndpoint: buzzinga-redis-master.svc.cluster.local.:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: operation-9674dd458-9jg9j(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=72,Free=32695,Min=4,Max=32767), POOL: (Threads=72,QueuedItems=46,CompletedItems=663), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1865
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisSubscriber.EnsureSubscribedToServer(Subscription sub, RedisChannel channel, CommandFlags flags, Boolean internalCall) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 381
   at StackExchange.Redis.RedisSubscriber.Subscribe(RedisChannel channel, Action`2 handler, ChannelMessageQueue queue, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 369
   at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 353
   at EasyCaching.Bus.Redis.DefaultRedisBus.BaseSubscribe(String topic, Action`1 action)
   at EasyCaching.Core.EasyCachingAbstractBus.Subscribe(String topic, Action`1 action)


StackExchange.Redis.RedisTimeoutException: Timeout performing SUBSCRIBE (5000ms), inst: 0, qu: 1, qs: 3, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 84, in-pipe: 0, out-pipe: 0, serverEndpoint: buzzinga-redis-master.svc.cluster.local.:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: operation-9674dd458-9jg9j(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=67,Free=32700,Min=4,Max=32767), POOL: (Threads=67,QueuedItems=53,CompletedItems=653), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1865
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisSubscriber.EnsureSubscribedToServer(Subscription sub, RedisChannel channel, CommandFlags flags, Boolean internalCall) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 381
   at StackExchange.Redis.RedisSubscriber.Subscribe(RedisChannel channel, Action`2 handler, ChannelMessageQueue queue, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 369
   at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 353
   at EasyCaching.Bus.Redis.DefaultRedisBus.BaseSubscribe(String topic, Action`1 action)
   at EasyCaching.Core.EasyCachingAbstractBus.Subscribe(String topic, Action`1 action)
```

Update:

The app and Redis instance is running on a Kubernetes cluster.

It could be that the library is using the sync Subscribe but I don't want to make sure that is the issue and I was wondering if I need to set SocketManager to ThreadPool or not.
```
app
cpu.limit: 0.250 
cput.request: 0.150
```

**Comment by NickCraver** [comment]
With the thread count you're at, it looks like you're hitting thread pool exhaustion from a lot of sync (vs. async) concurrent usage. For this we, recommend going async to handle a lot more load without thread pool contention.

**Comment by xsoheilalizadeh** [comment]
Thanks @NickCraver, would you recommend changing the SocketManager to ThreadPool? Since I was reading the timeout doc it was recommended to use it when there is no usage of sync APIs.

**Comment by NickCraver** [comment]
@xsoheilalizadeh you have a lot of sync something happening, indicated by `WORKER: (Busy=72,Free=32695,Min=4,Max=32767)` - if you're unsure what, I'd take a memory dump and see what all those threads are doing.

Remember: the thread pool is a global shared resource, so anything in your app may be doing this. Switching the socket manager to thread pool would almost certainly make your situation worse - you're seeing a symptom, not the problem.
