### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by pccai** [StackExchange/StackExchange.Redis#2325]
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Reflection.RuntimeAssembly.GetSimpleName(System.Runtime.CompilerServices.QCallAssembly, System.Runtime.CompilerServices.StringHandleOnStack)
--------------------------------
   at System.Reflection.RuntimeAssembly.GetSimpleName()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   **at StackExchange.Redis.Configuration.DefaultOptionsProvider.TryGetAzureRoleInstanceIdNoThrow()**
   at StackExchange.Redis.Configuration.DefaultOptionsProvider.GetDefaultClientName()
   at StackExchange.Redis.Configuration.DefaultOptionsProvider.get_ClientName()
   at StackExchange.Redis.ConnectionMultiplexer.get_ClientName()
   at StackExchange.Redis.ServerEndPoint+<HandshakeAsync>d__133.MoveNext()

**Comment by NickCraver** [comment]
What issue is being reported here? This is in a try/catch to intentionally best effort, runs very rarely, and would only be seen with first chance exceptions enabled in a debugger…which would show tons of other errors that are also normal and handled.

**Comment by mgravell** [comment]
Also, it would be great to know if there's some environmental context we need to know here - like running on an obscure platform or with AOT enabled. This doesn't happen routinely, so: we'd need to know what is different about your environment that you're seeing a problem that we aren't.

**Comment by NickCraver** [comment]
Closing this out to tidy up - my only guess is first chance exceptions are enabled stopping on everything (even if handled) - there's no change to make for that case.
