### ISSUE TITLE
Unable to connect using .NET 7 StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s)

### ISSUE THREAD

**Issue by MussaratAziz** [StackExchange/StackExchange.Redis#2334]
@NickCraver thanks for the replies earlier here is the log.
01:41:25.4211: Connecting (sync) on .NET 7.0.1 (StackExchange.Redis: v2.6.86.49666)
01:41:25.4720: localhost:6379

01:41:25.4782: localhost:6379/Interactive: Connecting...
01:41:25.4922: localhost:6379: BeginConnectAsync
01:41:25.5250: 1 unique nodes specified (with tiebreaker)
01:41:25.5267: localhost:6379: OnConnectedAsync init (State=Connecting)
01:41:25.5285: Allowing 1 endpoint(s) 00:00:05 to respond...
01:41:25.5300: Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=4,QueuedItems=0,CompletedItems=6)
01:41:25.5403: localhost:6379: OnConnectedAsync completed (Disconnected)
01:41:25.5485: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=5,Free=32762,Min=12,Max=32767), POOL: (Threads=7,QueuedItems=0,CompletedItems=11)
01:41:25.5491: Endpoint summary:
01:41:25.5492:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
01:41:25.5492: Task summary:
01:41:25.5506:   localhost:6379: Returned, but incorrectly
01:41:25.5558: Election summary:
01:41:25.5570:   Election: localhost:6379 had no tiebreaker set
01:41:25.5570:   Election: No primaries detected
01:41:25.5592: Endpoint Summary:
01:41:25.5686:   localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
01:41:25.5699: Connection failed: localhost:6379 (Interactive, UnableToConnect): UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
01:41:25.5700: Connection failed: localhost:6379 (Subscription, UnableToConnect): UnableToConnect on localhost:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
01:41:25.5701: Connection failed: localhost:6379 (Interactive, UnableToConnect): UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
01:41:25.5701: Connection failed: localhost:6379 (Subscription, UnableToConnect): UnableToConnect on localhost:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
01:41:25.5702:   localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
01:41:25.5730:   localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
01:41:25.5731: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
01:41:25.5731: Resetting failing connections to retry...
01:41:25.5749:   Retrying - attempts left: 2...
01:41:25.5749: 1 unique nodes specified (with tiebreaker)
01:41:25.5749: localhost:6379: OnConnectedAsync init (State=Connecting)
01:41:25.5750: Allowing 1 endpoint(s) 00:00:05 to respond...
01:41:25.5750: All tasks are already complete
01:41:25.5750: localhost:6379: OnConnectedAsync completed (Disconnected)
01:41:25.5753: Endpoint summary:
01:41:25.5753:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
01:41:25.5753: Task summary:
01:41:25.5753:   localhost:6379: Returned, but incorrectly
01:41:25.5753: Election summary:
01:41:25.5753:   Election: localhost:6379 had no tiebreaker set
01:41:25.5753:   Election: No primaries detected
01:41:25.5753: Endpoint Summary:
01:41:25.5753:   localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
01:41:25.5753:   localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
01:41:25.5754:   localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
01:41:25.5754: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
01:41:25.5754: Resetting failing connections to retry...
01:41:25.5769:   Retrying - attempts left: 1...
01:41:25.5770: 1 unique nodes specified (with tiebreaker)
01:41:25.5770: localhost:6379: OnConnectedAsync init (State=Disconnected)
01:41:25.5770: Allowing 1 endpoint(s) 00:00:05 to respond...
01:41:25.5770: Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=1,CompletedItems=32)
01:41:30.5783: Not all available tasks completed cleanly (from ReconfigureAsync#1309, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=55)
01:41:30.5795:   Server[0] (localhost:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: -1, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NA. ws: NA)
01:41:30.5795: Endpoint summary:
01:41:30.5795:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
01:41:30.5795: Task summary:
01:41:30.5795:   localhost:6379: Did not respond (Task.Status: WaitingForActivation)
01:41:30.5795: Election summary:
01:41:30.5796:   Election: localhost:6379 had no tiebreaker set
01:41:30.5796:   Election: No primaries detected
01:41:30.5796: Endpoint Summary:
01:41:30.5796:   localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
01:41:30.5796:   localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=4
Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.dll
An unhandled exception of type 'StackExchange.Redis.RedisConnectionException' occurred in StackExchange.Redis.dll: 'It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.'
Stack trace:
 >   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log, Nullable`1 serverType, EndPointCollection endpoints)
 >   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log)
 >   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)

**Comment by MussaratAziz** [comment]
@NickCraver  after changing connection string to this localhost:6379,allowAdmin=true,connectTimeout=1000,syncTimeout=1000,abortConnect=false,ssl=false 
I am getting this exception
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 1000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 1, serverEndpoint: localhost:6379, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: 30c620ce0c3f(SE.Redis-v2.6.86.49666), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=12,Max=32767), POOL: (Threads=13,QueuedItems=0,CompletedItems=1107)

**Comment by MussaratAziz** [comment]
02:58:24.8165: Connecting (sync) on .NET 7.0.1 (StackExchange.Redis: v2.6.86.49666)
02:58:24.8481: localhost:6379,syncTimeout=1000,allowAdmin=True,connectTimeout=1000,ssl=False,abortConnect=False

02:58:24.8541: localhost:6379/Interactive: Connecting...
02:58:24.8693: localhost:6379: BeginConnectAsync
02:58:24.8832: 1 unique nodes specified (with tiebreaker)
02:58:24.8839: localhost:6379: OnConnectedAsync init (State=Connecting)
02:58:24.8868: Allowing 1 endpoint(s) 00:00:01 to respond...
02:58:24.8886: Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=4,QueuedItems=0,CompletedItems=6)
02:58:24.8993: localhost:6379: OnConnectedAsync completed (Disconnected)
02:58:24.9259: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=8,Free=32759,Min=12,Max=32767), POOL: (Threads=8,QueuedItems=0,CompletedItems=10)
02:58:24.9290: Endpoint summary:
02:58:24.9292:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:58:24.9294: Task summary:
02:58:24.9295:   localhost:6379: Returned, but incorrectly
02:58:24.9307: Election summary:
02:58:24.9308:   Election: localhost:6379 had no tiebreaker set
02:58:24.9308:   Election: No primaries detected
02:58:24.9311: Endpoint Summary:
02:58:24.9356:   localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:58:24.9477:   localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
02:58:24.9490: Connection failed: localhost:6379 (Interactive, UnableToConnect): UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
02:58:24.9491: Connection failed: localhost:6379 (Subscription, UnableToConnect): UnableToConnect on localhost:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
02:58:24.9491: Connection failed: localhost:6379 (Interactive, UnableToConnect): UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
02:58:24.9492: Connection failed: localhost:6379 (Subscription, UnableToConnect): UnableToConnect on localhost:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.86.49666
02:58:24.9511:   localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:58:24.9511: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:58:24.9512: Resetting failing connections to retry...
02:58:24.9529:   Retrying - attempts left: 2...
02:58:24.9530: 1 unique nodes specified (with tiebreaker)
02:58:24.9530: localhost:6379: OnConnectedAsync init (State=Connecting)
02:58:24.9530: Allowing 1 endpoint(s) 00:00:01 to respond...
02:58:24.9530: Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=23)
02:58:24.9538: localhost:6379: OnConnectedAsync completed (Disconnected)
02:58:24.9541: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=29)
02:58:24.9541: Endpoint summary:
02:58:24.9541:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:58:24.9541: Task summary:
02:58:24.9541:   localhost:6379: Returned, but incorrectly
02:58:24.9541: Election summary:
02:58:24.9541:   Election: localhost:6379 had no tiebreaker set
02:58:24.9541:   Election: No primaries detected
02:58:24.9541: Endpoint Summary:
02:58:24.9541:   localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:58:24.9541:   localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
02:58:24.9541:   localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:58:24.9541: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:58:24.9541: Resetting failing connections to retry...
02:58:24.9556:   Retrying - attempts left: 1...
02:58:24.9556: 1 unique nodes specified (with tiebreaker)
02:58:24.9560: localhost:6379: OnConnectedAsync init (State=Disconnected)
02:58:24.9560: Allowing 1 endpoint(s) 00:00:01 to respond...
02:58:24.9561: Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=36)
02:58:25.9561: Not all available tasks completed cleanly (from ReconfigureAsync#1309, timeout 1000ms), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=54)
02:58:25.9570:   Server[0] (localhost:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: -1, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NA. ws: NA)
02:58:25.9570: Endpoint summary:
02:58:25.9571:   localhost:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:58:25.9571: Task summary:
02:58:25.9571:   localhost:6379: Did not respond (Task.Status: WaitingForActivation)
02:58:25.9571: E

**Comment by MussaratAziz** [comment]
Deleted all the images and containers associated with redis restarted the computer, recreated new containers by pulling latest redis images, rebuild the solution and It worked.
