### ISSUE TITLE
EVAL timeout every few months

### ISSUE THREAD

**Issue by JLRishe** [StackExchange/StackExchange.Redis#2357]
I have an Azure web app that uses the RedisSessionStateProvider. Aside from using this provider, and having it configured in the app's web.config, the app doesn't have any direct interaction with Redis.

Once every few months, the app seems to encounter Redis EVAL timeouts, which makes the entire app unusable until it is restarted, because any attempt to use the session state results in an error. After restarting, it continues to work normally for a few months until the issue occurs again.

We have a very similar deployment of the same app in a different Azure region, using a Redis cache in that region, but that instance hasn't had this issue occur in years. To the best of my knowledge, this latter app has much heavier user traffic, and yet the issue only happens in the one with lighter traffic.

What can I do to troubleshoot this? I have read the page about troubleshooting this, but given that I'm not interacting with the cache directly, I'm not sure what I can change. I have tried tweaking the settings in the session provider configuration a little, which seems to have helped a bit, but not completely.

Are there ways to mitigate the fallout from this kind of issue or recover from it, such that it doesn't bring the whole app down?

Stack trace:

```
StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 0, mgr: Inactive, err: never, queue: 4060, qu: 4060, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: RD0003FF1DC537, serverEndpoint: Unspecified/********.redis.cache.windows.net:6380, keyHashSlot: 5984, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=4,Free=8187,Min=1,Max=8191) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
	Stack Trace:    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags)
   at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass7_0.<Eval>b__0() in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\Shared\StackExchangeClientConnection.cs:line 68
   at Microsoft.Web.Redis.StackExchangeClientConnection.OperationExecutor(Func`1 redisOperation) in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\Shared\StackExchangeClientConnection.cs:line 95
   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\Shared\StackExchangeClientConnection.cs:line 118
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\Shared\StackExchangeClientConnection.cs:line 68
   at Microsoft.Web.Redis.RedisConnectionWrapper.UpdateExpiryTime(Int32 timeToExpireInSeconds) in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 89
   at Microsoft.Web.Redis.RedisSessionStateProvider.ResetItemTimeout(HttpContext context, String id) in D:\BuildAgent\work\7ed95ebd4aa4fca7\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 371
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Session provider configuration:

```xml
    <sessionState mode="Custom" customProvider="RedisCacheStore">
      <providers>
        <add name="RedisCacheStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="**********.redis.cache.windows.net" port="6380"
          accessKey="*******************=" ssl="True" connectionTimeoutInMilliseconds="15000" operationTimeoutInMilliseconds="1000"
          retryTimeoutInMilliseconds="3000"/>
      </providers>
    </sessionState>
```

**Comment by mgravell** [comment]
I don't think the problem here is the `eval` specifically - simply *because* you're using `Microsoft.Web.Redis.RedisSessionStateProvider` and the main operation that `Microsoft.Web.Redis.RedisSessionStateProvider` uses is `eval`, it is *manifesting* as an `eval` timeout, but the real problem here is that the connection has jammed. The high `qu` and zero `qs` suggests this, as that means nothing is being written - we don't have a valid transport. It is *possible* that updating the SE.Redis version could help with this, especially if the issue is due to azure redis cache maintenance (more recent versions of the library communicate with azure redis cache to get maintenance window notifications, etc, and react accordingly). In net8 (not currently available), `Microsoft.Web.Redis.RedisSessionStateProvider` has also been enhanced to include "force reconnect" support, although this is strictly opt-in and based on app flags.

**Comment by JLRishe** [comment]
@mgravell Thank you for your quick help!

One thing that's a little puzzling to me about what you said - I've observed that when this issue occurs, the issue is reproducible right until I restart the app, and goes away as soon as the app restarts. This suggests that if maintenance or some other transport issue is the cause, that underlying issue is probably gone before I restart the app.

So what I'm wondering is - is it possible that maintenance or some other transport problem could have caused the connection to go bad, and for the connection to remain bad even after the underlying cause of the transport issue has gone away? And is that something that might have been improved in more recent versions of the relevant packages?

I'm going to upgrade my app to the latest release versions of RedisSessionStateProvider and SE.Redis and see if that helps:

RedisSessionStateProvider: 3.0.2 -> 4.0.1
SE.Redis: 2.0.505 -> 2.6.90

Thank you again!

**Comment by NickCraver** [comment]
Definitely upgrade! In the base library we have better metrics in those timeouts, but importantly we have proactive handling of Azure maintenance events that automatically reconnect and proactively do so - we work with the Azure Redis Cache team on always improving that area. A few different "forever hung" issues have come up the last 2 years and to our knowledge, they are all solved in latest. The upgrade of StackExchange.Redis should put you on much better footing :)
