### ISSUE TITLE
TryGetAzureRoleInstanceIdNoThrow() Always throw CLR when F5

### ISSUE THREAD

**Issue by pccai** [StackExchange/StackExchange.Redis#2385]
protected virtual string GetDefaultClientName() =>
            (TryGetAzureRoleInstanceIdNoThrow()
             ?? ComputerName
             ?? "StackExchange.Redis") + "(SE.Redis-v" + LibraryVersion + ")";

### asmb.GetName()

  /// </remarks>
        internal static string? TryGetAzureRoleInstanceIdNoThrow()
        {
            string? roleInstanceId;
            try
            {
                Assembly? asm = null;
                foreach (var asmb in AppDomain.CurrentDomain.GetAssemblies())
                {
                    **if (asmb.GetName()?.**Name?.Equals("Microsoft.WindowsAzure.ServiceRuntime") == true)
                    {
                        asm = asmb;
                        break;
                    }

>Windows 10/Net6.0.12/VS2022

**Comment by pccai** [comment]
How can I disabled Azure auto detection?

**Comment by mgravell** [comment]
also, you haven't told us *what was thrown*; *sometimes* it is possible to avoid a particular exception with some minor additional checks; however, sometimes the exception is entirely unavoidable and all we can do is catch it and recover. So: what *exactly* is getting thrown in your case?

**Comment by pccai** [comment]
asmb.GetName() throw CLR errors

**Comment by NickCraver** [comment]
@pccai Yes, inside a `try` (by design) - which means to see that you have first chance exceptions enabled in your debugger, that's going to be noisy including this one :)

**Comment by pccai** [comment]
![image](https://user-images.githubusercontent.com/2232794/222050942-c905f053-edc5-428d-a105-f245e1b693b3.png)

Fatal error. Internal CLR error. (0x80131506)
   at System.Reflection.RuntimeAssembly.GetSimpleName()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at StackExchange.Redis.Configuration.DefaultOptionsProvider.TryGetAzureRoleInstanceIdNoThrow()
   at StackExchange.Redis.Configuration.DefaultOptionsProvider.GetDefaultClientName()
   at StackExchange.Redis.ConnectionMultiplexer.get_ClientName()
   at StackExchange.Redis.ServerEndPoint+<HandshakeAsync>d__133.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[StackExchange.Redis.ServerEndPoint+<HandshakeAsync>d__133, StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46]](<HandshakeAsync>d__133 ByRef)
   at StackExchange.Redis.ServerEndPoint.HandshakeAsync(StackExchange.Redis.PhysicalConnection, StackExchange.Redis.LogProxy)
   at StackExchange.Redis.ServerEndPoint.OnEstablishingAsync(StackExchange.Redis.PhysicalConnection, StackExchange.Redis.LogProxy)
   at StackExchange.Redis.PhysicalBridge+<OnConnectedAsync>d__78.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[StackExchange.Redis.PhysicalBridge+<OnConnectedAsync>d__78, StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46]](<OnConnectedAsync>d__78 ByRef)
   at StackExchange.Redis.PhysicalBridge.OnConnectedAsync(StackExchange.Redis.PhysicalConnection, StackExchange.Redis.LogProxy)
   at StackExchange.Redis.PhysicalConnection+<ConnectedAsync>d__108.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[StackExchange.Redis.PhysicalConnection+<ConnectedAsync>d__108, StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46]](<ConnectedAsync>d__108 ByRef)
   at StackExchange.Redis.PhysicalConnection.ConnectedAsync(System.Net.Sockets.Socket, StackExchange.Redis.LogProxy, StackExchange.Redis.SocketManager)
   at StackExchange.Redis.PhysicalConnection+<BeginConnectAsync>d__27.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[StackExchange.Redis.PhysicalConnection+<BeginConnectAsync>d__27, StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46]].MoveNext(System.Threading.Thread)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs+<>c.<.cctor>b__179_0(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

tks.

**Comment by pccai** [comment]
Always interrupting my train of thought and having to try again several times...

**Comment by NickCraver** [comment]
@pccai You have this enabled, it's not by default:
![image](https://user-images.githubusercontent.com/454813/222051685-8f962ffb-ed45-42eb-92ca-2f77c12c3343.png)
![image](https://user-images.githubusercontent.com/454813/222051726-7b7d6e36-ca42-4a58-897f-12cfb12f2c62.png)

You've either intentionally or inadvertently opted into a very noisy debugging experience, but what's happening is not a bug. If this wasn't intentional, I hope those screenshots help in disabling it.

**Comment by pccai** [comment]
Not select for default.

**Comment by NickCraver** [comment]
I'm pretty sure we just have a language barrier here, but I can't understand what issue you are trying to report. This is a first chance exception. .NET has many of them. It's working as intended. If you don't want it to interrupt you, don't opt into them in your debugger. I'm not sure what other way to say that - this isn't a StackExchange.Redis issue.
