### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException: Timeout performing UNKNOWN (50000ms)

### ISSUE THREAD

**Issue by liranyeh** [StackExchange/StackExchange.Redis#2399]
what can be the root cause for this issue:
1. check all metrics from redis side, not issue at all. nothing. cpu/mem/network all fatastic.
2. check slowlogs - nothing. all under 20 ms that is very good for us.

looks like it try to replace with NRedisSearch some key document and failed there? maybe it to big but how should I know which key cause it from this exception? maybe the pool size? since the I have queue items?

who can really help with it? thanks in advance!

just to note Im using K8S and this exception come from the docker that communicate with redis. all on cloud. our applications and redis under same vpc.

StackExchange.Redis.RedisTimeoutException: Timeout performing UNKNOWN (50000ms), next: INFO, inst: 0, qu: 0, qs: 7, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 270, out-pipe: 0, serverEndpoint: redis-16776.c11293.eu-west-2-mz.ec2.cloud.rlrcp.com:16776, mc: 1/1/0, mgr: 10 of 10 available, clientName: debug2, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=117,Free=32650,Min=1,Max=32767), POOL: (Threads=117,**QueuedItems=315,**CompletedItems=16743990), Local-CPU: unavailable, v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1873
   at NRediSearch.Client.AddDocument(String docId, Dictionary`2 fields, Double score, Boolean noSave, Boolean replace, Byte[] payload) in /_/src/NRediSearch/Client.cs:line 461
   at IDoBet.Common.Redis.RedisSearch.IDoBetRedisSearchWrapper.Replace(String key, Int64 eventId, String eventJson, Boolean isLive, Boolean isOpen, Boolean isWatchdogChanged, Int32 isAllResulted, Int64 eventDate) in /src/IDoBet.Common.Redis/RedisSearch/IDoBetRedisSearchWrapper.cs:line 102
   at IDoBet.Common.Redis.IDoBetRedisWrapper.SetEvent[T](String key, T data, String keyRawData, TimeSpan expiry, Boolean isUpdate) in /src/IDoBet.Common.Redis/IDoBetRedisWrapper.cs:line 165
   at IDoBet.Feed.BetRadar.Feeder.Processors.AbstractProcessor.SetSportGame(SportGame sportGame, Boolean isUpdate, LogTrace logTraceConfig) in /src/BetRadar/IDoBet.Feed.BetRadar.Feeder/Processors/AbstractProcessor.cs:line 136
   at IDoBet.Feed.BetRadar.Feeder.Processors.AbstractProcessor.Process(Object data) in /src/BetRadar/IDoBet.Feed.BetRadar.Feeder/Processors/AbstractProcessor.cs:line 270

**Comment by NickCraver** [comment]
Looking at your exception, you're likely hitting thread pool/CPU exhaustion, indicated by `WORKER: (Busy=117,Free=32650,Min=1,Max=32767)`, advice is to get a memory dump when this is happening or when running hot in general to see where all those threads are. Newer versions of the library give a few more stats tat help further, but most of the time you're talking about lots of synchronous calls instead of async, which is in the exception path you're hitting here.

**Comment by NickCraver** [comment]
Since advice is above, closing out to clean up.
