### ISSUE TITLE
Executing Multi Slot commands through Envoy Proxy

### ISSUE THREAD

**Issue by dceravigupta** [StackExchange/StackExchange.Redis#2426]
I have a cache which consists of multiple standalone Redis instances all behind an Envoy Proxy. As per the Envoy documentation, it is capable of fanning out a multi slot command like MGET to the right Redis instances based on its hash slot. It works as expected when I run such commands through redis-cli.
![image](https://user-images.githubusercontent.com/32182026/229309015-d3986733-4000-45cb-a798-0b0b9848352e.png)

But in my .NET application, when I issue such command through StackExchange.Redis, it throws an exception saying `Multi-key operations must involve a single slot;` Wondering is there any way to execute such operations in my step?

![image](https://user-images.githubusercontent.com/32182026/229308895-23313ee4-32b8-4f00-a9fa-5e415bdf1522.png)

![image](https://user-images.githubusercontent.com/32182026/229308933-c9de75e0-67d4-4b1e-9581-cbe84519b6fd.png)
`StackExchange.Redis.RedisCommandException
  HResult=0x80131500
  Message=Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ServerSelectionStrategy.Select(Message message, Boolean allowDisconnected) in /_/src/StackExchange.Redis/ServerSelectionStrategy.cs:line 148
   at StackExchange.Redis.ConnectionMultiplexer.SelectServer(Message message) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1828
   at StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1843
   at StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridgeSync[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1905
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1966
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey[] keys, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 3028
   at Program.<Main>$(String[] args) in C:\Users\ravgup\source\repos\ConsoleApp14\ConsoleApp14\Program.cs:line 10
`

**Comment by mgravell** [comment]
Is there a documented list of which operations support this? We *could* simply let these through and let the server worry about it - it would be a simple case of changing the [envoy handling here](https://github.com/StackExchange/StackExchange.Redis/blob/88725539175424f8d5054211378c3a702bff9ed0/src/StackExchange.Redis/ServerSelectionStrategy.cs#L143) to simply do `break;` - I guess it depends on how universal this feature is. I'm guessing it doesn't apply to `rpoplpush` for example.

**Comment by dceravigupta** [comment]
@mgravell  their documentation have not mentioned any such list. This is what their document mentioned on this topic.

![image](https://user-images.githubusercontent.com/32182026/229359937-d23be032-5352-4336-9b79-4d54a0f8d336.png)
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis

Also, they don't support all the Redis commands at this moment and `rpoplpush` is one of them. They do that list of supported commands listed on the page above.

**Comment by mgravell** [comment]
Thoughts @NickCraver ? I'm thinking "disable the check" (i.e. just `break;` for envoy) - disagree at all?

**Comment by NickCraver** [comment]
+1 - this is only optimizing an error path to throw faster, if that's not 100% correct let's rip it out!

**Comment by mgravell** [comment]
PR: #2428

**Comment by dceravigupta** [comment]
Thanks @mgravell and @NickCraver!
