### ISSUE TITLE
Tls cert validation fails but seems to work when using the redis CLI

### ISSUE THREAD

**Issue by rolfwessels** [StackExchange/StackExchange.Redis#2429]
**Problem:** 
I have set up a little docker server using TLS basically following this TLS post (https://tienbm90.medium.com/running-redis-tls-with-docker-compose-b89811fb01d3). (No cluster just a single node)
```bash
wget https://raw.githubusercontent.com/redis/redis/unstable/utils/gen-test-certs.sh
./gen-test-certs.sh
docker build -t redis-tls-test:6.2.0 . ; docker run -it -p "7379:7379" --rm redis-tls-test:6.2.0
```
I then run the redis cli command and connect to the server with no issues.
```bash
redis-cli  --tls --cacertdir ./tests/tls -h localhost  -p 7379 --cert redis.crt --key redis.key --cacert ca.crt
# Output
# localhost:7379> set test sdfasd
# OK
# localhost:7379> get test
# "sdfasd"
```
I then convert those cert files into a pfx file using the following command.

```bash
openssl pkcs12 -export -out redis-self.pfx -inkey ./tests/tls/redis.key -in ./tests/tls/redis.crt -certfile ./tests/tls/ca.crt
# password set to  `sample`

# now I run the program.cs with the pfx and it fails
dotnet run -- "localhost:7379" redis-self.pfx sample "" "redisTLSTest2021@@"
#Trying to connect....
#Verified redis-self.pfx = False
#!Certificate error: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
#Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). #There was an authentication failure; check that passwords (or client certificates) are configured correctly. AuthenticationFailure #on localhost:7379/Interactive, Initializing/NotStarted, last: NONE, origin: ConnectedAsync, outstanding: 0, last-read: 0s ago, #last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: #2.2.4.27433
#  at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in #/_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1163
#  at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in #/_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1032
# at Program.<Main>$(String[] args) in D:\Work\temp\RedisConnection\Program.cs:line 56


# now I run the program.cs bypassing validation and it works
dotnet run -- "localhost:7379" redis-self.pfx sample "hack" "redisTLSTest2021@@"
#Trying to connect....
#Verified redis-self.pfx = False
#!Certificate error: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
#test_string:Working
```
**Expectation:** 

I was expecting the pfx to work because it seems to be working when using the CLI. 

**Appendix:** 

Program.cs
```cs
using System.Net.Security;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using StackExchange.Redis;

Console.WriteLine("Trying to connect....");

var endPoint = GetArgOrDefault(args, 0, "localhost:7379");
var redisPfx = GetArgOrDefault(args, 1, "redis-self.pfx");
var password = GetArgOrDefault(args, 2, "sample");
var hackIt = GetArgOrDefault(args, 3, @"nope");
var redisPassword = GetArgOrDefault(args, 4, ""); 

string GetArgOrDefault(string[] strings, int index, string defaultValue)
{
    return strings.Length > index? strings[index] : defaultValue;
}

var configurationOptions = new ConfigurationOptions
{
    EndPoints =  {{ endPoint }},
    AbortOnConnectFail = true,
    Ssl = true,
    SslHost = endPoint,
    SslProtocols = SslProtocols.Tls12,
    Password = redisPassword
};

configurationOptions.CertificateSelection += delegate
{
    try
    {
        var cert = new X509Certificate2(redisPfx, password);
        Console.WriteLine("Verified {0} = {1}",redisPfx,cert.Verify());
        return cert;
    }
    catch (Exception e)
    {
        Console.WriteLine("Error when verifying {1}:{0}",e, redisPfx);
        throw;
    }
    
};
configurationOptions.CertificateValidation += (_, _, chain, errors) =>
{
    if (errors != SslPolicyErrors.None)
    {
        Console.WriteLine("!Certificate error: {0}", errors);
        if (hackIt != "hack") return false;
    }
    return true;
};


var multiplexer = ConnectionMultiplexer.Connect(configurationOptions); ;
var db = multiplexer.GetDatabase();
db.StringSet("test_string", "Working",TimeSpan.FromSeconds(100));
string value = db.StringGet("test_string");
Console.WriteLine("test_string:"+value);

```

**Comment by NickCraver** [comment]
The error here is coming from .NET, the certificate your remote server is returning isn't considered valid by .NET:

> #!Certificate error: RemoteCertificateNameMismatch, RemoteCertificateChainErrors

This indicates the certificate coming back doesn't have a name that matched the endpoint (localhost, so I'd expect this), and that it doesn't have a valid chain (self-signed probably?). In short: redis-cli isn't caring about the validity but .NET, by default, does. You can plug in and adjust things are desired on validation but it looks to me to be functioning correctly, rejecting an invalid certificate.

I get that you're probably testing local in prep for prod, so this is frustrating, just relaying what the situation is. You could for example install that certificate as trusted locally and then .NET should treat it as valid...a few options there, honestly not sure what the best practice is per platform.
