### ISSUE TITLE
Redis Stack Exchange  Timeout performing SCAN (5000ms) issue

### ISSUE THREAD

**Issue by sanjaysingharcadix** [StackExchange/StackExchange.Redis#2447]
Hi,

could you please explain what can be the root cause of the timeout issue in the Redis stack exchange(2.6.86)?
I am using ConnectionMultiplexer to create to connection for Redis.

StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN (5000ms), next: SCAN, inst: 24, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 0, sync-ops: 233, async-ops: 243, serverEndpoint: 10.247.143.110:6379, conn-sec: 56.39, mc: 1/1/0, mgr: 10 of 10 available, clientName: AX-BLR-2(SE.Redis-v2.6.86.49666), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=1589), v: 2.6.86.49666 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.ThrowTimeout(Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 247
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.SlowNextSync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 193
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)

**Comment by NickCraver** [comment]
This looks like it's actually a slow SCAN - I recommend checking out the [SLOWLOG](https://redis.io/commands/slowlog-get/) server-side to see if anything's apparent there.

**Comment by NickCraver** [comment]
@sanjaysingharcadix I noticed here that you've only been connected 60 sec - is this happening right after connect a lot? Or is it possible you're re-creating multiplexers often? (they're meant to be very long-lived)

**Comment by robert94p** [comment]
I have also encountered this issue periodically:
`StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN (5000ms), next: INFO, inst: 1, qu: 0, qs: 1, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 465299, serverEndpoint: redis:6379, conn-sec: 6267,32, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: d1cc29206174(SE.Redis-v2.8.22.13109), IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=15,Free=32752,Min=16,Max=32767), POOL: (Threads=16,QueuedItems=0,CompletedItems=1612900,Timers=18), v: 2.8.22.13109 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)    at StackExchange.Redis.CursorEnumerable1.Enumerator.ThrowTimeout(Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 249    at StackExchange.Redis.CursorEnumerable1.Enumerator.SlowNextSync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 195    at System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection) `

Is there a known solution or any recommendations to resolve this error?
