### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by timomta** [StackExchange/StackExchange.Redis#2465]
I'm getting a null reference exception from the Redis ASP.Net session state provider via the StackExchangeClient. It is not coming directly from the application code, so I'm not sure exactly what is going on. 
Is it possible that the value of a given session state key/value pair was set to null and that caused an exception in the client?
For example, if Session("myKey") = null (a particular value was set to null) somehow happened, would that break the StackExchangeClient?

```
</Data>
            <Data>removed</Data>
            <Data>/default.aspx</Data>
            <Data>10.18.1.133</Data>
            <Data></Data>
            <Data>False</Data>
            <Data></Data>
            <Data>IIS APPPOOL\removed</Data>
            <Data>63</Data>
            <Data>IIS APPPOOL\removed</Data>
            <Data>False</Data>
            <Data>   at System.Object.GetType()
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs)
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLock(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout)
   at Microsoft.Web.Redis.RedisSessionStateProvider.&lt;SetAndReleaseItemExclusiveAsync&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.&lt;ReleaseStateAsyncImpl&gt;d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
</Data>

The exception is a null reference:
            <Data>NullReferenceException</Data>
            <Data>Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs)
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLock(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout)
   at Microsoft.Web.Redis.RedisSessionStateProvider.&lt;SetAndReleaseItemExclusiveAsync&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.&lt;ReleaseStateAsyncImpl&gt;d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
```

Since it is thrown from session state client worker threads, it is difficult to determine the exact place in the application causing the issue.

**Comment by timomta** [comment]
I noticed from the namespace "Microsoft.Web.Redis" the exception is not from the StackExchange client, it is still in the session state provider. Sorry I didn't see that earlier. This is an issue for their forum.
