### ISSUE TITLE
Strange RedisTimeoutException for FT.CREATE while it's immediate and ok from redis_cli

### ISSUE THREAD

**Issue by giuliohome** [StackExchange/StackExchange.Redis#2470]
I have the following timeout error ... In my case it's FT.CREATE from F#

```fsharp
let cx = ConnectionMultiplexer.Connect "localhost:6379,SyncTimeout=30000,AsyncTimeout=30000"
let db = cx.GetDatabase ()
db.Execute("FT.CREATE",[|"openai-langchain-redis-aks", "SCHEMA", "content_vector", "VECTOR", "FLAT", 6, "TYPE", "FLOAT32", "DIM", 1536,"DISTANCE_METRIC", "COSINE", "metadata","TEXT", "content", "TEXT" |])
```
(edited and deleted this part `"PREFIX",1, "doc:openai-langchain-redis-aks:", `)

the exact same index creation takes less than a second in **redis_cli** so there must be something else going wrong....

```
127.0.0.1:6379> FT.CREATE openai-langchain-redis-aks SCHEMA content_vector VECTOR FLAT 6 TYPE FLOAT32 DIM 1536 DISTANCE_METRIC COSINE metadata TEXT content TEXT
OK
```

Let me know if I have to open another issue or there is something already in the backlog..

The full log of the .NET exception

```
dotnet run
Unhandled exception. StackExchange.Redis.RedisTimeoutException: Timeout performing UNKNOWN (30000ms), next: FT.CREATE, inst: 0, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 349, cur-in: 0, sync-ops: 1, async-ops: 0, serverEndpoint: localhost:6379, conn-sec: 30,17, aoc: 1, mc: 1/1/0, mgr: 10 of 10 available, clientName: WPWS13316812(SE.Redis-v2.6.111.64013), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), POOL: (Threads=3,QueuedItems=0,CompletedItems=43), v: 2.6.111.64013 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2093
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1502
   at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1497
   at MyRedis.createIndex() in C:\dev-2023\openai\chatbot-index-init\VectorStore\Redis.fs:line 100
   at <StartupCode$VectorStore>.$Main.main@() in C:\dev-2023\openai\chatbot-index-init\VectorStore\main.fs:line 38
```

 (I will try also from C#, I guess will be no difference, but I still have to try...)

**Comment by giuliohome** [comment]
fair enough
ok I've deleted that part same error, let me edit the description of the issue and the command thanks

**Comment by giuliohome** [comment]
ehm 👀 

> PR to complete split of NRediSearch library into a sibling repo, now located at StackExchange/NRediSearch

why? 🙄 ... ok, I try that one...

**Comment by NickCraver** [comment]
@giuliohome You're probably going to be a lot better off with the much more up to date https://github.com/redis/redis-om-dotnet - NRedisSearch in general was only an experiment for modules, much better libraries have superseded since them (several using us for connections under the covers).

**Comment by giuliohome** [comment]
Found the solution (my fault, my byg, I'm going to close after a doube check)

```
    let pars = 
        [|
            "openai-langchain-redis-aks" ; 
            "SCHEMA";
            "content_vector"; "VECTOR";  "FLAT"; "6"; "TYPE"; "FLOAT32"; "DIM"; "1536"; "DISTANCE_METRIC"; "COSINE"; 
            "metadata"; "TEXT"; "content"; "TEXT" 
        |] |> Array.map(fun k -> k :> Object)
    let res = db.Execute("FT.CREATE", pars)
```
