### ISSUE TITLE
Error: StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl

### ISSUE THREAD

**Issue by kalyan89** [StackExchange/StackExchange.Redis#268]
There are lots of logs created in my application throwing the below error:

```
Message : No connection is available to service this operation: LLEN cp-ReprocessUserMessages:Queue
 Source : StackExchange.Redis
at Stack Trace :    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
    at StackExchange.Redis.RedisDatabase.ListLength(RedisKey key, CommandFlags flags)
    at DCI.LiveGuide.ClientPortal.DataStore.Queues.RedisQueue`1.HasValue()
```

I used to get this error lot of times, after researching I found that using snapshotting would resolve this so I addded "save 60 1000" in my config file at that moment it worked and I didn't see any logs for a while. Now again it started showing this message very frequent. Any suggestion would be appreciated.

Thanks in Advance.

**Comment by NickCraver** [comment]
This was fixed in later releases but we're behind on issues - closing out to cleanup :)

For anyone hitting this - please update to the latest version of the library. You'll get a much more informative message when any errors arise.
