### ISSUE TITLE
IndexOutOfRangeException while trying to consume a message from Redis

### ISSUE THREAD

**Issue by ohadab29** [StackExchange/StackExchange.Redis#2688]
Hi all,

we are using Redis 6.2.6 with 1 shard and 2 nodes.
we use stack exchange version 2.7.20
in the last few days we see that we can not consume the messages and fail on : 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Pipelines.Sockets.Unofficial.Internal.Throw.IndexOutOfRange() in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 65
   at Pipelines.Sockets.Unofficial.Arenas.Sequence`1.GetReference(Int64 index) in /_/src/Pipelines.Sockets.Unofficial/Arenas/Sequence.cs:line 327
   at StackExchange.Redis.ResultProcessor.SingleStreamProcessor.SetResultCore(PhysicalConnection connection, Message message, RawResult& result) in /_/src/StackExchange.Redis/ResultProcessor.cs:line 1854
   at StackExchange.Redis.ResultProcessor.SetResult(PhysicalConnection connection, Message message, RawResult& result) in /_/src/StackExchange.Redis/ResultProcessor.cs:line 219
   at StackExchange.Redis.Message.ComputeResult(PhysicalConnection connection, RawResult& result) in /_/src/StackExchange.Redis/Message.cs:line 533

after service restart it looks ok...any idea why ?

**Comment by ohadab29** [comment]
someone?

**Comment by mgravell** [comment]
Thanks for the report. StackExchange.Redis **3.0** ships a substantial rewrite of the low-level IO core — a new RESPite-based stack that replaces `Pipelines.Sockets.Unofficial` and the old backlog/write loop — and we're confident this issue is addressed by that work.

Closing as resolved in 3.0. If you can still reproduce on 3.0.x, please comment and we'll reopen and investigate with fresh diagnostics.
