### ISSUE TITLE
Protocol error: invalid bulk length

### ISSUE THREAD

**Issue by axelgenus** [StackExchange/StackExchange.Redis#2713]
I implemented a little helper function which (should) search a RedisSearch index, given a query:

```csharp
    public static IEnumerable<T> Search<T>(this SearchCommands commands, string indexName, Query query)
    {
        SearchResult result = commands.Search(indexName, query);

        foreach (Document document in result.Documents)
        {
            string? json = document["json"];
            if (json is null)
            {
                continue;
            }

            var obj = JsonSerializer.Deserialize<T>(json);
            if (obj is not null)
            {
                yield return obj;
            }
        }
    }
```

An exception on the multiplexed is thrown:

```
StackExchange.Redis.RedisServerException: ERR Protocol error: invalid bulk length
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2109
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1501
   at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1496
   at NRedisStack.Auxiliary.Execute(IDatabase db, SerializedCommand command)
   at NRedisStack.SearchCommands.Search(String indexName, Query q)
```

I tried changing between the sync and async versions of the commands to no avail. The sync command give better stack trace. Any clue?

EDIT: I am using NRedisStack v 0.12.0 which, in turn, depends on StackExchange.Redis ≥ 2.6.122. The actual resolved version used is 2.7.33 (I use in other part of the solution).

**Comment by mgravell** [comment]
This looks like an error that is coming from the server, not the client. I'm *guessing* that means that NRedisStack is sending a null string (length -1), which is not valid for client-to-server commands. I think this needs to be logged and investigated by the NRedisStack folks, though.

**Comment by axelgenus** [comment]
Yep, I debugged a bit and it's a bug on my program.

Sorry to waste your time: for future reference, this happens when you provide null as search terms.

**Comment by axelgenus** [comment]
Yep, I debugged a bit and it's a bug on my program.

Sorry to waste your time: for future reference, this happens when you provide null as search terms.
