### ISSUE TITLE
ArgumentException while OutputCache is cached

### ISSUE THREAD

**Issue by abratv** [StackExchange/StackExchange.Redis#2732]
Hi,

I got error message in log while i swear my endpoint output is cached
Any how I can find what the cause of this exception?

```
System.ArgumentException: A null value is not valid in this context
   at StackExchange.Redis.RedisValue.AssertNotNull() in /_/src/StackExchange.Redis/RedisValue.cs:line 308
   at StackExchange.Redis.RedisDatabase.ScriptEvalMessage..ctor(Int32 db, CommandFlags flags, RedisCommand command, String script, Byte[] hexHash, RedisKey[] keys, RedisValue[] values) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 4814
   at StackExchange.Redis.RedisDatabase.ScriptEvalMessage..ctor(Int32 db, CommandFlags flags, RedisCommand command, String script, RedisKey[] keys, RedisValue[] values) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 4790
   at StackExchange.Redis.RedisDatabase.ScriptEvaluateAsync(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1547
   at Microsoft.AspNetCore.OutputCaching.StackExchangeRedis.RedisOutputCacheStore.Microsoft.AspNetCore.OutputCaching.IOutputCacheBufferStore.SetAsync(String key, ReadOnlySequence`1 value, ReadOnlyMemory`1 tags, TimeSpan validFor, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OutputCaching.OutputCacheEntryFormatter.StoreAsync(String key, OutputCacheEntry value, HashSet`1 tags, TimeSpan duration, IOutputCacheStore store, ILogger logger, CancellationToken cancellationToken)
  ```

**Comment by mgravell** [comment]
This is probably a question for https://github.com/dotnet/aspnetcore/, but it is still "me", just "me with a different hat on"; very curious - I'd need to investigate and try to repro

**Comment by abratv** [comment]
When I google the same exception, it refer to this repo... but the other issue do it manually, not using aspnet middleware.
I don't notice if there is issue until i see the log....

Moved the issue to aspnetcore repo (added some more information over there too)
