### ISSUE TITLE
Issues setting key using Microsoft.Extensions.Caching.StackExchangeRedis

### ISSUE THREAD

**Issue by chaadfh** [StackExchange/StackExchange.Redis#2737]
Hi,

I'm aware that this issue is concerning `Microsoft.Extensions.Caching.StackExchangeRedis`, and that this issue may be in the wrong repo, but I'm going to ask anyways, as I suspect this may be an issue in regards to ACL and not specifically `Microsoft.Extensions.Caching.StackExchangeRedis` (_if I'm wrong, your more than welcome to discard this issue_).

I'm trying to setup distributed caching in a .NET 8 application, using Redis as the storage.
I have 3 Redis instances running in a primary/replica setup, with 3 Sentinel instances. For now, I'm simply trying to get a clean connection directly to the primary Redis instance, circumventing the Sentinel setup for a start. I'm simply trying to validate the connection and my ACL setup.

### Setup
I've made a user with the following command: 
```
ACL SETUSER test on >some-password ~test:* &* -@all +@read +@pubsub +set +echo +info +ping
```
I've set up `Microsoft.Extensions.Caching.StackExchangeRedis` in the following manner:
```csharp
builder.Services.AddStackExchangeRedisCache(options =>
{
    options.InstanceName = "test";
    options.ConfigurationOptions = new ConfigurationOptions()
    {
        EndPoints = { "<server>:6379" },
	User = "test",
	Password = "some-password"
    };
});
```

### Usage
Issues begin to arise whenever I try to set a key. Temporarily, I'm trying to set a key on `app.Lifetime.ApplicationStarted`, like so:
```csharp
app.Lifetime.ApplicationStarted.Register(() =>
{
    var currentTime = DateTime.Now.ToString();
    var encoded = System.Text.Encoding.UTF8.GetBytes(currentTime);
    var options = new DistributedCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromSeconds(20));
    app.Services.GetService<IDistributedCache>().Set("test", encoded, options);
});
```

### Error
Whenever `app.Services.GetService<IDistributedCache>().Set("test", encoded, options);` gets called, I'm receiving the following error: `ERR The user executing the script can't run this command or subcommand script: 3915ee22fda531a1d5661f2523d0443fd35ff0a4, on @user_script:2`. Hence why I'm suspecting this may be an ACL issue. I cannot seem to find any documentation from Microsofts side, explaining the minimum ACL requirements on a limited user, so I was hoping that you may be able to guide me in some direction.

Here's the stack trace following the error:
```
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)
at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags)
at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
at Program.<>c__DisplayClass0_0.<<Main>$>b__10() in C:\DevOps Workspace\docunote-api\src\Application\DocuNote.Api\Program.cs:line 261
at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by chaadfh** [comment]
As a bonus info, this is a look at the MONITOR result of Redis during `app.Services.GetService<IDistributedCache>().Set("test", encoded, options);`:

```
1718094459.556826 [0 10.0.200.129:54173] "AUTH" "(redacted)" "(redacted)"
1718094459.556886 [0 10.0.200.129:54172] "AUTH" "(redacted)" "(redacted)"
1718094459.559293 [0 10.0.200.129:54173] "ECHO" "\xde\xda\xe5\xcf9\xad\x19H\xbe\x942\x8by\xe4'\x93"
1718094459.560241 [0 10.0.200.129:54173] "SUBSCRIBE" "__Booksleeve_MasterChanged"
1718094459.560459 [0 10.0.200.129:54172] "INFO" "replication"
1718094459.560474 [0 10.0.200.129:54172] "INFO" "server"
1718094459.561010 [0 10.0.200.129:54172] "GET" "__Booksleeve_TieBreak"
1718094459.561014 [0 10.0.200.129:54172] "ECHO" "\xde\xda\xe5\xcf9\xad\x19H\xbe\x942\x8by\xe4'\x93"
1718094459.573774 [0 10.0.200.129:54172] "INFO" "replication"
1718094459.583559 [0 10.0.200.129:54172] "SCRIPT" "LOAD" "\r\n                redis.call('HSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], 'data', ARGV[4])\r\n                if ARGV[3] ~= '-1' then\r\n                  redis.call('EXPIRE', KEYS[1], ARGV[3])\r\n                end\r\n                return 1"
1718094459.583585 [0 10.0.200.129:54172] "EVAL" "\r\n                redis.call('HSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], 'data', ARGV[4])\r\n                if ARGV[3] ~= '-1' then\r\n                  redis.call('EXPIRE', KEYS[1], ARGV[3])\r\n                end\r\n                return 1" "1" "test" "-1" "200000000" "20" "11-06-2024 10:27:39"
```

It "dies" right after the last `EVAL` command.

**Comment by chaadfh** [comment]
Managed to find the issue.

Apparently, my user needs `+@write` added to the ACL for this to work.

Is this intended?

If I look at the @write category `ACL CAT write`, I see a lot of commands. I'm not sure if this is potentially dangerous for the user to have access to.

**Comment by chaadfh** [comment]
Nevermind. Of course is required as the `@write` category should be used when writing to keys.

Playing around with the ACL setup, I ended on the following:
```
~test:* &~test:* -@all +@read +@write +echo +info +role +eval +ping
```

Everything seems to work just fine.

Sorry for the inconvenience.
