### ISSUE TITLE
Redis Timeout Exception - .NET Framework 4.8, everything async

### ISSUE THREAD

**Issue by TimSalisbury** [StackExchange/StackExchange.Redis#2803]
Hi,

Every now and again we are receiving the following exception from StackExchange.Redis:

`Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5703ms elapsed, timeout is 5000ms), command=SETEX, next: SET xxxxx, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 34, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 440495, serverEndpoint: xxxxx, conn-sec: 76835.98, aoc: 1, mc: 1/1/0, mgr: 10 of 10 available, clientName: xxxx(SE.Redis-v2.8.16.12844), PerfCounterHelperkeyHashSlot: 141, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=6,Free=32761,Min=2,Max=32767), v: 2.8.16.12844 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

This is while running on a .NET Framework 4.8 application, with every call being async.

Any ideas? I appreciate any help with this.

**Comment by philon-msft** [comment]
It's normal to receive occasional timeouts due to things like Redis server maintenance. We recommend implementing a command retry strategy using something like [Polly](https://www.pollydocs.org/)

**Comment by TimSalisbury** [comment]
Thank you for the response!

I can add some more context:

This is running against an AWS ElastiCache Redis cluster with two nodes. From what I can tell, there was no maintenance during this period when we received this error. Along with that, there were several servers going to our Redis cluster during this time, and only one of the servers ended up with this error

**Comment by isacruzramos** [comment]
hi, I have also experienced a couple of random time outs even when the Redis server load is low
we are using version **2.7.33** of the C# SDK, do we know how often can we hit this? Can correlate it to an specific maintenance window of the cache?

-------Exception information------
System.TimeoutException: Task did not complete within the TimeoutMs=5000
   at Microsoft.Kailani.Common.TaskExtensions.<ExecuteWithTimeoutAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kailani.Common.RedisCacheUtil.<TryExecuteRedisActionAsync>d__10.MoveNext()

**Comment by mgravell** [comment]
Thanks for the report. We believe this is very likely addressed by the low-level IO rewrite in StackExchange.Redis **3.0** (a new RESPite-based core that replaces `Pipelines.Sockets.Unofficial` and the old backlog/write loop).

Closing on that basis — but we'd value confirmation: if you can still reproduce on 3.0.x, please comment with details and we'll reopen and dig in.
