### ISSUE TITLE
Doc Issue - API Browser Not Loading

### ISSUE THREAD

**Issue by JavaScriptDude** [StackExchange/StackExchange.Redis#2830]
I followed the link at the top of the documentation [API Browser (via fuget.org)](https://www.fuget.org/packages/StackExchange.Redis/) but fuget.org shows an error:

`Error reading package`

```
System.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at FuGetGallery.PackageData.ReadEntriesAsync(HttpClient client, String file)
   ...
```

Is this expected? How do I get to the API Docs?

**Comment by mgravell** [comment]
The fuget page seems to be working again now, although it seems to have some severe performance problems. I assume they're having a problem - possibly a cache failure (it would be amusing if they're using us for their cache layer!). Maybe try again in a few days.

**Comment by JavaScriptDude** [comment]
Still not working for me. FYI - This is the last ticket in Fuget's issue tracker: https://github.com/praeclarum/FuGetGallery/issues/189

**Comment by JavaScriptDude** [comment]
Any chance you guy's can upload the source files to configure your fuget.org API documentation to github? Just being able to read them may be helpful in a few ways.

**Comment by mgravell** [comment]
Sure, here you go: (hands over an empty bag)

Pretty sure we do literally nothing special here, and that fuget builds this itself via the XML files that we ship in the NuGet package.

**Comment by mgravell** [comment]
It seems to be loading promptly now. Is this still causing an issue?

**Comment by NickCraver** [comment]
Closing out to tidy up.
