### ISSUE TITLE
Redis Session  Error: Timeout performing EVAL, inst: 0, mgr: ExecuteSelect, err: never, queue: 49, qu: 48, qs: 1, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER:(Busy=52,Free=32715,Min=36,Max=32767), clientName: ************

### ISSUE THREAD

**Issue by maulikhdave** [StackExchange/StackExchange.Redis#320]
> Error, TagType=InfoTagModule=APPERROR$$$CRITICAL - APPERROR - Application_Error event - ErrorDetails - *\* VP 
Error Report:   
Error: Timeout performing EVAL, inst: 0, mgr: ExecuteSelect, err: never, queue: 49, qu: 48, qs: 1, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER:(Busy=52,Free=32715,Min=36,Max=32767), clientName: ************

```
Source: StackExchange.Redis.StrongName 
Stack Trace: at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl<T>
  at StackExchange.Redis.RedisBase.ExecuteSync<T>
  at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags)
  at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass4.b__3()
  at Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func1 redisOperation)
  at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func1 redisOperation)
  at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs)
  at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout)
  at Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem)
  at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
  at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
  at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) 
UserSession Items:
  User Key: 0 
  Currency Key: 3 
  Basket Key: 1454212 
  Date: 11 December 2015 
  Time: 05:30:24
  URL: /CheckoutStep1.aspx
  File: /***.aspx
```

**Comment by JonCole** [comment]
You probably need to change your threadpool settings - notice how the "busy" value is greater than "min" for WORKER.   See https://gist.github.com/JonCole/e65411214030f0d823cb#file-threadpool-md for more details...

**Comment by NickCraver** [comment]
This may be related to #450, or may just be a very long EVAL in redis causing timeouts downstream. Keeping it separate from the other timeout issues.

**Comment by NickCraver** [comment]
No updates here and likely what @JonCole pointed out above (given the 52 busy) - closing out to cleanup. For anyone finding this later, lots of Timeout diagnostic help is now available at https://stackexchange.github.io/StackExchange.Redis/Timeouts
