### ISSUE TITLE
InternalFailure on SETEX for large strings

### ISSUE THREAD

**Issue by smirzaei** [StackExchange/StackExchange.Redis#322]
I'm in the process of moving an application written in node.js to .NET and I'm trying to cache some fairly large json responses (around 15MB) because they are expensive to compute and accessed frequently but getting an error.

Using `1.1.0-alpha2` version on CoreCLR.

```
StackExchange.Redis.RedisConnectionException : InternalFailure on SETEX
      ---- System.ArgumentException : Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
      Stack Trace:
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        ----- Inner Stack Trace -----
           at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
           at StackExchange.Redis.BufferedOutputStream.Write(Byte[] buffer, Int32 offset, Int32 count)
           at StackExchange.Redis.PhysicalConnection.WriteUnified(Stream stream, Byte[] value)
           at StackExchange.Redis.PhysicalConnection.Write(RedisValue value)
           at StackExchange.Redis.Message.CommandKeyValueValueMessage.WriteImpl(PhysicalConnection physical)
           at StackExchange.Redis.PhysicalBridge.WriteMessageToServer(PhysicalConnection connection, Message message)
```

Here's a sample code to reproduce it:

``` CSHARP
var val = "";
for (int i = 0; i < 50; i++)
{
    val += "Lorem ipsum dolor sit amet, quodsi adipiscing mel cu, ius sonet mollis pertinacia no, atomorum deseruisse quo et. Mea commodo constituto cu, accusata vulputate vituperatoribus ut vel. Ex dicta singulis eos. Ei vix quot omnium.";
}

using (var redis = ConnectionMultiplexer.Connect("localhost"))
{
    var database = redis.GetDatabase();
    await database.StringSetAsync("foo", val, TimeSpan.FromMinutes(10));
}
```

With lower iterations for example 20 (around `4500` characters) it won't throw any exceptions but it takes a VERY long time to finish.

Am I doing something wrong?

**Comment by NickCraver** [comment]
This isn't you, it appears to be a bug in or limitation of the internal buffered stream implementation. That'll go away as soon as RC2 for .Net Core lands which brings back these much needed APIs.

**Comment by smirzaei** [comment]
Good to know! Thanks.

**Comment by MichaCo** [comment]
Getting the same errors and cannot really solve it by updating the references to rc2 stuff.

@NickCraver are you sure this will be fixed in RC2? Do you have a reference issue on dotnet/coreclr? Might be I'm too stupid to find it~~

**Comment by Trajanv** [comment]
Not sure, if you have found a solution or a workaround, I just faced similar issue for long strings, just tried this workaround that seem to be working fine. [...split the long string into batch of 4000 chars, and append ] https://github.com/StackExchange/StackExchange.Redis/issues/388

**Comment by NickCraver** [comment]
Closing out to cleanup, this was fixed in `netstandard1.5`.
