### ISSUE TITLE
Endpoint stucks in DidNotRespond unselectable reason

### ISSUE THREAD

**Issue by susleg** [StackExchange/StackExchange.Redis#35]
Steps to reproduce:
1. Open connection to two servers (master and slave)
2. Send get request
3. Stop master, and quickly send get request
4. Stop slave, start master
5. Send get request again

Expected result is valid data returned, because master server is up. 
But actual result is exception:

```
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET key1
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1687
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 79
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1286
```

I've debugged code a little bit, and I found out that on step 3 master endpoint sets DidNotRespond to unselectableReasons, and so this endpoint will never be used for requests. I didn't find any normal way for endpoint to remove this state.

**Comment by NickCraver** [comment]
A lot of digging and fixing has gone into connections since this was posted. Can you repro on a current SE.Redis build? We had a lot of causes with crazy scenarios, hopefully this is one of many resolved.
