### ISSUE TITLE
MGET OutOfMemory Exception on multiple keys

### ISSUE THREAD

**Issue by radu103** [StackExchange/StackExchange.Redis#358]
Version installed : 1.0.488 (StackExchange.Redis.StrongName)

When the MGET function is used on Redis to get more keys that have a significat size (+10 mb and even +50mb json texts values) the Exception of type 'System.OutOfMemoryException' was thrown.

Stacktrace:

   at System.BitConverter.ToString(Byte[] value, Int32 startIndex, Int32 length)
   at System.BitConverter.ToString(Byte[] value)
   at StackExchange.Redis.RedisValue.op_Implicit(RedisValue value) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisValue.cs:line 518
   at StackExchange.Redis.RedisValue.ToString() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisValue.cs:line 161

**Comment by radu103** [comment]
more stack trace with test function : 

   at System.Array.Resize[T](T[]& array, Int32 newSize)
   at StackExchange.Redis.PhysicalConnection.EnsureSpaceAndComputeBytesToRead() in C:\StackExchange_Redis\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 850
   at StackExchange.Redis.PhysicalConnection.StackExchange.Redis.ISocketCallback.Read() in C:\StackExchange_Redis\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 1002

**Comment by radu103** [comment]
static void TestHugeKeysMGET()
        {

            var configurationOptions = new ConfigurationOptions
                    {
                        EndPoints =
                        {
                            { "192.168.0.56", 6379 }
                        },
                        KeepAlive = 180,
                        ConnectTimeout = 10000000,
                        ResponseTimeout = 10000000,
                        SyncTimeout = 10000000,
                        Password = String.Empty,
                        AllowAdmin = true
                    };

            using (var muxer = ConnectionMultiplexer.Connect(configurationOptions))
            //using (var muxer = ConnectionMultiplexer.Connect("localhost,resolvedns=1"))
            {
                RedisKey[] keys = new RedisKey[] { "mget1_large", "mget2_large", "mget3_large", "mget4_large", "mget5_large", "mget6_large", "mget7_large", "mget8_large", "mget9_large", "mget10_large" };
                var conn = muxer.GetDatabase();

                Random _random = new Random();

                StringBuilder sb = new StringBuilder();
                for (int l = 0; l < Int32.MaxValue / 10; l++)
                {
                    int num = _random.Next(0, 26); // Zero to 25
                    char let = (char)('a' + num);
                    sb.Append(let.ToString());
                }

                String rndstr = sb.ToString();

                Console.WriteLine("SET...");

                for (int k = 0; k < keys.Length; k++)
                {
                    Console.WriteLine("SET " + keys[k] + "...");
                    conn.StringSet(keys[k], rndstr, new TimeSpan(24, 0, 0));
                }

                Console.WriteLine("MGET...");

                RedisValue[] values = conn.StringGet(keys);

                Console.WriteLine("GET...");

                for (int k = 0; k < keys.Length; k++)
                {
                    Console.WriteLine("GET " + keys[k] + "...");
                    RedisValue val = conn.StringGet(keys[k]);
                }
            }
        }

**Comment by mgravell** [comment]
K, sounds fun - will look. That should work, but huge blobs and string
always complicate things.

**Comment by radu103** [comment]
it's something that can be fixed.
outofmemory should never happen in a managed high level prog language like c#
i'm looking also at this...the code in example function crashed

Date: Wed, 17 Feb 2016 12:43:29 -0800

**Comment by mgravell** [comment]
OutOfMemoryException is *guaranteed* in a few scenarios, particularly
relating to single large objects, which means: arrays or strings (them
being the only types allocated with runtime-variable length).

It is also pretty common on x86; can I assume this is x64?

**Comment by radu103** [comment]
It's a x64 scenario

**Comment by NickCraver** [comment]
@radu103 Which version of .Net? The behavior has changed for this in .Net 4.5 and 4.6, so that information will help.

**Comment by radu103** [comment]
.NET 4.5

Date: Fri, 18 Mar 2016 03:08:34 -0700

**Comment by NickCraver** [comment]
@mgravell I did some testing locally here and I don't think this is something to address directly, but to keep in mind with the network Pipelines rewrite which I believe just makes it a non-issue. The problem happens in:
```c#
private int EnsureSpaceAndComputeBytesToRead()
{
    int space = ioBuffer.Length - ioBufferBytes;
    if (space == 0)
    {
        Array.Resize(ref ioBuffer, ioBuffer.Length * 2);
        space = ioBuffer.Length - ioBufferBytes;
    }
    return space;
}
```
Which in this case of 250MB+ strings * 10 in a single operation just bloats the ever living crap out of that buffer...past the 2GB limit. When we're async iterating off the incoming buffer instead of allocating at all this should just go away.
