### ISSUE TITLE
It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout

### ISSUE THREAD

**Issue by DaveSenn** [StackExchange/StackExchange.Redis#377]
My application is using Redis + StackExchange.Redis to cache data.
Sometimes when I make some parallel requests to my application, StackExchange.Redis throws the following exception:

```
“It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout”
```

With the following log:

**Case 1)**
```
    _Connecting localhost:6379/Interactive...
    BeginConnect: localhost:6379
    1 unique nodes specified
    Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
    Allowing endpoints 00:00:01 to respond...
    Awaiting task completion, IOCP: (Busy=4,Free=996,Min=8,Max=1000), WORKER: (Busy=11,Free=4084,Min=8,Max=4095)
    EndConnect: localhost:6379
    Connected Interactive/localhost:6379
    Server handshake
    Setting client name: FIG
    Auto-configure...
    Sending critical tracer: Interactive/localhost:6379
    Writing to Interactive/localhost:6379: ECHO
    Flushing outbound buffer
    Starting poll
    Connect complete: localhost:6379
    All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=10,Free=4085,Min=8,Max=4095)
    localhost:6379 faulted: ConnectionDisposed on PING
    Awaiting task completion, IOCP: (Busy=4,Free=996,Min=8,Max=1000), WORKER: (Busy=11,Free=4084,Min=8,Max=4095)
```

**Case 2)**
```
    _Connecting localhost:6379/Interactive...
    BeginConnect: localhost:6379
    1 unique nodes specified
    Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
    Allowing endpoints 00:00:01 to respond...
    Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=11,Free=4084,Min=8,Max=4095)
    EndConnect: localhost:6379
    Connected Interactive/localhost:6379
    Server handshake
    Setting client name: FIG
    Auto-configure...
    Sending critical tracer: Interactive/localhost:6379
    Writing to Interactive/localhost:6379: ECHO
    Flushing outbound buffer
    Starting poll
    Not all tasks completed cleanly, IOCP: (Busy=2,Free=998,Min=8,Max=1000), WORKER: (Busy=12,Free=4083,Min=8,Max=4095)
    localhost:6379 did not respond
    Awaiting task completion, IOCP: (Busy=2,Free=998,Min=8,Max=1000), WORKER: (Busy=12,Free=4083,Min=8,Max=4095)
    Connect complete: localhost:6379
    Response from Interactive/localhost:6379 / ECHO: BulkString: 16 bytes
    Writing to Interactive/localhost:6379: GET __Booksleeve_TieBreak
    Writing to Interactive/localhost:6379: PING
    Not all tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=12,Free=4083,Min=8,Max=4095)
    localhost:6379 failed to nominate (WaitingForActivation)
    No masters detected
    localhost:6379: Standalone v3.0.501, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: DidNotRespond
    localhost:6379: int ops=10, qu=0, qs=3, qc=0, wr=0, sync=7, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, sync=3, socks=1
    Circular op-count snapshot; int: 0+10=10 (1.00 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
    Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
    resetting failing connections to retry...
    retrying; attempts left: 2...
    1 unique nodes specified
    Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
    Allowing endpoints 00:00:01 to respond...
    Writing to Interactive/localhost:6379: PING
    Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=12,Free=4083,Min=8,Max=4095)
    Writing to Interactive/localhost:6379: GET __Booksleeve_TieBreak
    Response from Interactive/localhost:6379 / GET __Booksleeve_TieBreak: (null)
    Response from Interactive/localhost:6379 / PING: SimpleString: PONG
    Response from Interactive/localhost:6379 / PING: SimpleString: PONG
    Response from Interactive/localhost:6379 / GET __Booksleeve_TieBreak: (null)
    All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=12,Free=4083,Min=8,Max=4095)
    localhost:6379 returned with success
    All tasks are already complete
    localhost:6379 had no tiebreaker set
    Single master detected: localhost:6379
    localhost:6379: Standalone v3.0.501, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
    localhost:6379: int ops=12, qu=0, qs=0, qc=2, wr=0, sync=10, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, sync=3, socks=1
    Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
    Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
    Starting heartbeat...
```

Does this exception occur because Redis does not response to the request fast enough, or is there another reason for it? 

Alsow the library has thrown the following exception:

```
Cannot access a disposed object.

   bei StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:Zeile 1798.
   bei StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:Zeile 73.
   bei StackExchange.Redis.RedisDatabase.HashGetAsync(RedisKey key, RedisValue[] hashFields, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:Zeile 152.
   bei COMPANY.Common.Caching.RedisCacheService.<HashGetAsync>d__31.MoveNext() in C:\_git\COMPANY\Common\Caching\Redis\RedisCacheService.cs:Zeile 402.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei COMPANY.Common.Data.Service`1.<GetData>d__20.MoveNext() in C:\_git\COMPANY\Common\Data\IService.cs:Zeile 202.
```

(I did not dispose any object.)

My application is a ASP.Net MVC 5 (not core^^) application targeting .Net 4.6.1. 
I performed my tests on a Windows 10 machine. Redis (MSOpenTech Redis 3.0) is running on the same machine. 

Here the code my application uses to communicate with Redis (I removed the application specific “unimportant” parts to make it more readable):

```C#
public class RedisCacheService
{
    private IConnectionMultiplexer _connectionMultiplexer;

    public RedisFactory RedisFactory { get; set; }    
    private IConnectionMultiplexer ConnectionMultiplexer => _connectionMultiplexer ?? ( _connectionMultiplexer = RedisFactory.GetConnectionMultiplexer() );

    public async Task HashSetAsync( RedisKey key, HashEntry[] hashFields, CommandFlags flags = CommandFlags.None )
    {
        key.ThrowIfNull( nameof( key ) );
        hashFields.ThrowIfNull( nameof( hashFields ) );

        var db = ConnectionMultiplexer.GetDatabase();
        await db.HashSetAsync( key, hashFields, flags );
    }
}

public class RedisFactory
{
    private static readonly ConcurrentDictionary<String, ConnectionMultiplexer> ConnectionMultiplexers = new ConcurrentDictionary<String, ConnectionMultiplexer>();
    private static readonly Object SyncRoot = new Object();

    public IConnectionMultiplexer GetConnectionMultiplexer()
    {
        var connectionName = "Redis_0";
        var connectionMultiplexer = GetExistingConnectionMultiplexer( connectionName );
        if ( connectionMultiplexer != null )
            return connectionMultiplexer;

        lock ( SyncRoot )
        {
            connectionMultiplexer = GetExistingConnectionMultiplexer( connectionName );
            if ( connectionMultiplexer != null )
                return connectionMultiplexer;

            var connection = GetConnectionMultiplexer( connectionName );
            if ( ConnectionMultiplexers.ContainsKey( connectionName ) )
                ConnectionMultiplexers.TryUpdate( connectionName, connection, connection );
            else
                ConnectionMultiplexers.TryAdd( connectionName, connection );

            return connection;
        }
    }

    private ConnectionMultiplexer GetConnectionMultiplexer( String connectionName )
    {
        var sw = new StringWriter();
        try
        {
            var connectionMultiplexer = ConnectionMultiplexer.Connect( "localhost:6379,allowAdmin=True,connectTimeout=1000,defaultDatabase=0", sw );
            return connectionMultiplexer;
        }
        catch ( Exception ex )
        {
            var log = sw.ToString();
            return null;
        }
    }

    private ConnectionMultiplexer GetExistingConnectionMultiplexer( String connectionName )
    {
        ConnectionMultiplexer connectionMultiplexer;
        ConnectionMultiplexers.TryGetValue( connectionName, out connectionMultiplexer );
        if ( connectionMultiplexer == null )
            return null;

        if ( connectionMultiplexer.IsConnected )
            return connectionMultiplexer;

        ConnectionMultiplexers.TryRemove( connectionName, out connectionMultiplexer );
        return null;
    }
}
```

Am I doing something wrong? Or is it a Redis/Library problem?

I'm grateful for any help.

**Comment by kichalla** [comment]
I am seeing similar issue when trying to use the latest package of ``

**Redis server version:** Redis server v=3.0.501 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=ba05b51e58eb9205

**Error when running using dotnet CLI with a .NET core app:**
```
Project Microsoft.Extensions.Caching.Abstractions (.NETStandard,Version=v1.0) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Caching.Redis (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
Project RedisCacheSample (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Running C:\github\caching\samples\RedisCacheSample\bin\Debug\netstandardapp1.5\win7-x64\RedisCacheSample.exe
Process ID: 11740
Connecting to cache
Connected
Setting value 'Hello, World!' in cache
Unhandled Exception: System.AggregateException: One or more errors occurred. (It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING) ---> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.<ConnectAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<ConnectAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<SetAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at RedisCacheSample.Program.<RunSampleAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RedisCacheSample.Program.Main(String[] args)
```

**Server verbose outpu**
```
[10052] 21 Mar 10:40:46.679 # Server started, Redis version 3.0.501
[10052] 21 Mar 10:40:46.679 * The server is now ready to accept connections on port 6379
[10052] 21 Mar 10:40:46.695 - 0 clients connected (0 slaves), 634320 bytes in use
[10052] 21 Mar 10:40:51.730 - 0 clients connected (0 slaves), 634320 bytes in use
[10052] 21 Mar 10:40:51.739 - Accepted 127.0.0.1:12367
[10052] 21 Mar 10:40:51.739 - Accepted 127.0.0.1:12366
[10052] 21 Mar 10:40:51.779 - Accepted 127.0.0.1:12368
[10052] 21 Mar 10:40:51.783 - Client closed connection
[10052] 21 Mar 10:40:51.784 - Client closed connection
[10052] 21 Mar 10:40:51.789 - Client closed connection
[10052] 21 Mar 10:40:51.789 - Accepted 127.0.0.1:12369
[10052] 21 Mar 10:40:51.789 - Accepted 127.0.0.1:12370
[10052] 21 Mar 10:40:51.789 - Client closed connection
[10052] 21 Mar 10:40:51.789 - Client closed connection
[10052] 21 Mar 10:40:51.846 - Accepted 127.0.0.1:12371
[10052] 21 Mar 10:40:51.847 - Client closed connection
[10052] 21 Mar 10:40:56.798 - 0 clients connected (0 slaves), 634320 bytes in use
```

**Comment by deepakverma** [comment]
I am guessing here from the output log in the thread, that it could be that when SE.Redis doesn't receive the response within 1 second for a large request (or may be due to performance of the client on coreclr) it thinks it's a stale connection and tries to reconnect.
You can check this assumption by setting configurationoption.ResponseTimeout to a higher value (say 30 secs) and see if start getting timeout exceptions now.

**Comment by kichalla** [comment]
Thanks! @deepakverma ... will give it a try today

**Comment by RonaldSwaine** [comment]
Default redis-server install, and using .net core, with SE.Redis.
Immediately experienced this issue.

**I resolved it by removing the host IP from redis.conf to list on all IP's, with the specified port.**

This could be due to the connection being made from a network / external IP, rather than as a loopback connection.

**Comment by NickCraver** [comment]
Notes for @mgravell on Pipelines: Perhaps we need to separate out the DNS phase from the connect phase in terms of timeouts. Should an exceedingly slow DNS response be responsible for an initial connect timeout, or should the timeout not start until after DNS is resolved? Perhaps it could be another setting (default to ~5 or 30 sec?)

I mention this because I think we'll have to do the lookups for cross-platform *anyway*, so can we solve 2 problems here?

**Comment by NickCraver** [comment]
Going to close this out because the underlying .NET Core landscape has changed. While pipelines affects this, effectively the only reason for doing DNS lookups was .NET Core 1.x. Connecting to endpoints via hostname is not fixed in `corefx` for the `Sockets` namespace across all platformx in 2.x. Given 2.x is the minimum buy-in ans has been for a while, it makes sense to use all the platform support in the network rather than roll our own. When we roll our own, it means another DNS cache to debug, etc. There's no need for that anymore - we can be simpler, faster, and more resilient all at the same time now.
