### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING

### ISSUE THREAD

**Issue by danielkornev** [StackExchange/StackExchange.Redis#387]
This issue happens from time to time, with Redis 2.8 (32-bit); we launch multiple separate instances for a desktop (yikes!)-based 32-bit WPF 4.5 app. We run it on Windows 10 64-bit (latest release, as well as latest Redstone builds).

I've read #42, and tried the latest Alpha build, as well made the number of available threads for the managed Thread Pool twice as large as default... 

Unfortunately, issue remains when using both the latest stable, and the latest alpha versions of StackExchange.Redis from NuGet.

**Maybe it's a good idea to create own threads instead of using the Managed Thread Pool?**

```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
   at StackExchange.Redis.ConnectionMultiplexer.<ConnectAsync>d__20.MoveNext() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 765
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ZU.Storage.Redis.RedisEnvironmentManagement.<>c__DisplayClass0_0.<<CreateRedisInstance>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ZU.Storage.Redis.RedisEnvironmentManagement.CreateRedisInstance(String currentFolder, Boolean showRedisInstanceCommandPrompt)
```

**Comment by NinoFloris** [comment]
See issue #390

**Comment by danielkornev** [comment]
figured it out (about a month ago). Didn't take into account that it might take time for Redis instance to load data into memory in the first place.

To solve this issue, added sort of a monitor: redis-cli.exe launches right after redis instance, and pings it; as soon as redis responses with "PONG", redis-cli.exe shuts down, and StackExchange.Redis.RedisConnection is created to begin working with Redis.
