### ISSUE TITLE
StackExchange.Redis causing errors recycling App Pools with WMI?

### ISSUE THREAD

**Issue by bab5470** [StackExchange/StackExchange.Redis#392]
I have a website utilizing the StackExchange.Redis library. When I go to stop the IIS pool using the following WMI/powershell code, the app pool crashes.

```
$appPoolName = "my-redis-website" 
$appPool = Get-WmiObject -namespace "root\MicrosoftIISv2" -Authentication PacketPrivacy -Impersonation Impersonate -class "IIsApplicationPool" | Where-Object { $_.Name -eq "W3SVC/APPPOOLS/$appPoolName" }
$appPool.Stop()

```

This same code works without exception if I stop/start a different app pool not using the StackExchange.Redis library. 

So if I simply switch this line:
$appPoolName = "DefaultAppPool" 

The app pool stops and there are no errors. 

Furthermore I found another user reporting a similar error here: 
http://stackoverflow.com/questions/28297005/getting-regular-configurationerrorsexception

Here's the full error/stacktrace when I perform $appPool.Stop():

```
Log Name:      Application
Source:        Application Error
Date:          4/13/2016 11:11:03 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MYWEBSERVER.mydomain.local
Description:
Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7a5f8
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0xfd8
Faulting application start time: 0x01d1959581d8bf31
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: ef757a11-0189-11e6-8ddc-005056a330b1
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-13T15:11:03.000000000Z" />
    <EventRecordID>531143</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MYWEBSERVER.mydomain.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>w3wp.exe</Data>
    <Data>7.5.7601.17514</Data>
    <Data>4ce7a5f8</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.18409</Data>
    <Data>53159a86</Data>
    <Data>e0434352</Data>
    <Data>0000c42d</Data>
    <Data>fd8</Data>
    <Data>01d1959581d8bf31</Data>
    <Data>C:\Windows\SysWOW64\inetsrv\w3wp.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>ef757a11-0189-11e6-8ddc-005056a330b1</Data>
  </EventData>
</Event>

-----

Log Name:      Application
Source:        .NET Runtime
Date:          4/13/2016 11:11:02 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MYWEBSERVER.mydomain.local
Description:
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException
Stack:
   at System.Diagnostics.TraceUtils.GetRuntimeObject(System.String, System.Type, System.String)
   at System.Diagnostics.TypedElement.BaseGetRuntimeObject()
   at System.Diagnostics.ListenerElement.GetRuntimeObject()
   at System.Diagnostics.ListenerElementsCollection.GetRuntimeObject()
   at System.Diagnostics.TraceInternal.get_Listeners()
   at System.Diagnostics.TraceInternal.WriteLine(System.Object)
   at StackExchange.Redis.SocketManager.Read()
   at StackExchange.Redis.SocketManager.<.cctor>b__21(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-13T15:11:02.000000000Z" />
    <EventRecordID>531142</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MYWEBSERVER.mydomain.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException
Stack:
   at System.Diagnostics.TraceUtils.GetRuntimeObject(System.String, System.Type, System.String)
   at System.Diagnostics.TypedElement.BaseGetRuntimeObject()
   at System.Diagnostics.ListenerElement.GetRuntimeObject()
   at System.Diagnostics.ListenerElementsCollection.GetRuntimeObject()
   at System.Diagnostics.TraceInternal.get_Listeners()
   at System.Diagnostics.TraceInternal.WriteLine(System.Object)
   at StackExchange.Redis.SocketManager.Read()
   at StackExchange.Redis.SocketManager.&lt;.cctor&gt;b__21(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
</Data>
  </EventData>
</Event>

--------------------------------------

Log Name:      Application
Source:        ASP.NET 4.0.30319.0
Date:          4/13/2016 11:11:02 AM
Event ID:      1325
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MYWEBSERVER.mydomain.local
Description:
An unhandled exception occurred and the process was terminated.

Application ID: DefaultDomain

Process ID: 4056

Exception: System.AppDomainUnloadedException

Message: Attempted to access an unloaded AppDomain.

StackTrace: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ASP.NET 4.0.30319.0" />
    <EventID Qualifiers="49152">1325</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-13T15:11:02.000000000Z" />
    <EventRecordID>531141</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MYWEBSERVER.mydomain.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>An unhandled exception occurred and the process was terminated.

Application ID: DefaultDomain

Process ID: 4056

Exception: System.AppDomainUnloadedException

Message: Attempted to access an unloaded AppDomain.

StackTrace: </Data>
  </EventData>
</Event>
```

Is this a bug in the library? We're running StackExchange.Redis version 1.0.481.0

Thanks,
Brad

**Comment by bab5470** [comment]
Note to reproduce this problem you need to have the IIS 6 WMI Compatibility enabled:                 Add-WindowsFeature Web-WMI

**Comment by NickCraver** [comment]
This should no longer happen, but was actually a result of diagnostics (tracing) attached to the library. This generally isn't something you want enabled in production, as it has a performance overhead on every command.

Closing this out to cleanup :)
