### ISSUE TITLE
Redis error when attempting to set an int variable.

### ISSUE THREAD

**Issue by nathvi** [StackExchange/StackExchange.Redis#400]
**Operating System:** Windows 10 
**VS Version:** 2015
**StackExchange.Redis Nuget Version:** 1.0.488
**Code That Is Breaking:** 
[RedisCodeExample.txt](https://github.com/StackExchange/StackExchange.Redis/files/245532/RedisCodeExample.txt)

**Order of Events to Get to Error:**
1. Start Redis server on local machine.
2. Run RedisCodeExample.

When attempting to set dbIndex = 0, this error is thrown...

**Error:**
An unhandled exception of type 'System.ArgumentException' occurred in StackExchange.Redis.dll
Additional information: is empty

**Stacktrace:**
   at StackExchange.Redis.ConfigurationOptions.DoParse(String configuration, Boolean ignoreUnknown) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConfigurationOptions.cs:line 496
   at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 778
   at StackExchange.Redis.ConnectionMultiplexer.<>c__DisplayClass27.<Connect>b__26() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 795
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 811
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 795
   at RedisCodeExamples.Program.Main(String[] args) in C:\Users\NGuyette\Source\Workspaces\Key WCS\KeyGen2\Gen2Library\RedisCodeExamples\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by orck-adrouin** [comment]
Hello,
It looks like your error is caused by line 28 and has nothing to do with setting `dbIndex` to 0.  If you look at the callstack you can see the error is thrown from `ConfigurationOptions.DoParse` because you specified an empty string for the connection string on line 28.
