### ISSUE TITLE
Redis Timeout issue using StackExchange.Redis.1.0.414 dll

### ISSUE THREAD

**Issue by SachinNetweb** [StackExchange/StackExchange.Redis#411]
Getting below error : mgr: executeSelect.

```
An exception of type System.TimeoutException occurred and was caught. 
Source: StackExchange.Redis;
Message: Timeout performing EXISTS OS:3084, inst: 1, mgr: ExecuteSelect, queue: 0, qu=0, qs=0, qc=0, wr=0/0, in=0/0;
Target: T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint);

StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) 
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags)
   at ePlus.OneSource.StackExchangeRedis.StackExchangeRedisCache.RedisStringSet(String key, Byte[] byteValue)
Error in RedisStringSet(key=System.String key, byteValue=Byte[] byteValue, );

Redis Error Detail: 
10.18.32.64:6379,abortConnect=False
1 unique nodes specified
Requesting tie-break from 10.18.32.64:6379 >
```

**Comment by NickCraver** [comment]
Have you tried updating to a more recent version? There have been many fixes with connections in the past year. 1.1.603 is the current stable version on NuGet.

**Comment by SachinNetweb** [comment]
Thanks for the prompt reply. I'll update & keep you updated .

 BTW One of leading blog, I have read below code also useful to avoid such timeout errors. Can I use below code for the same?

 private static ConnectionMultiplexer redis;
redis.PreserveAsyncOrder = false

**Comment by abhit011** [comment]
I am also experiencing the time out in this Call 

 int countChecking = server.Keys(pattern: this._userTypeEnum.ToString().ToLower()  +
                                                        ":" + 
                                                        "*").Count();

Timeout performing SCAN, inst: 45, mgr: ExecuteSelect, err: never, queue: 31685, qu: 30314, qs: 1371, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, clientName: TuxMan, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), 

Stack trace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2044
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 560
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.GetNextPageSync(IScanningCursor obj, Int64 cursor) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 204
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 297
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at

**Comment by abhit011** [comment]
Time Out is 10 Second..

**Comment by Enoch-Ye** [comment]
We've also got the same timeout error with 1.0.488 recently. Could anyone please confirm whether upgrading to latest version could get rid of this timeout error?

**Comment by SachinNetweb** [comment]
@Enoch-Ye In demo project I have upgraded the .dll  to ver. 1.1.603. with it I am not facing time-out issue.

**Comment by SachinNetweb** [comment]
Hi @NickCraver ,
I am still facing timeout issue even I have updated dll 1.1.603  with .Net framework 4.6.1.

**Comment by SachinNetweb** [comment]
Hi again.. @NickCraver & @mgravell ,
Another time out issue I am facing : **mgr:ProcessReadQueue**
Please do need ful.  Shared error detail below:

Server:OSAPP01; An exception of type System.TimeoutException occurred and was caught. Source:StackExchange.Redis;Message:Timeout performing GET OS:3084, inst: 1, mgr: ProcessReadQueue, queue: 2, qu=0, qs=2, qc=0, wr=0/0, in=0/0;Target:T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint);StackTrace:   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)     at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)     at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)     at ePlus.OneSource.StackExchangeRedis.StackExchangeRedisCache.RedisStringGet(String key)  Error in RedisStringGet(key=System.String key, );Redis Error Detail: 10.1.2.20:6379,abortConnect=False    1 unique nodes specified  Requesting tie-break from 10.1.2.20:6379 > __Booksleeve_TieBreak...  Allowing endpoints 00:00:05 to respond...  10.1.2.20:6379 returned with success  10.1.2.20:6379 had no tiebreaker set  Single master detected: 10.1.2.20:6379  10.1.2.20:6379: Standalone v2.4.6, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active  10.1.2.20:6379: int ops=11, qu=0, qs=0, qc=1, wr=0, sync=7, async=2, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, sync=3, socks=1  Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)  Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago  Starting heartbeat...

**Comment by NickCraver** [comment]
Doing an issue cleanup pass (formatted all of this) - this is related to #450 (main tracking there)

**Comment by NickCraver** [comment]
Collapsing into #450, just closing this to get a clear view of work left TODO.
