### ISSUE TITLE
OutOfMemory exception when trying to do ConnectionMultiplexer.Connect

### ISSUE THREAD

**Issue by ahan1874** [StackExchange/StackExchange.Redis#422]
I do ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost") in my internal class, running on windows server 2008 r2, keep having the outofmemory issue when trying to connect. 

My standalone exe works fine, I am not sure what is wrong with the ConnectionMultiplexer.Connect. 

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.     at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
     at System.Threading.Thread.Start(StackCrawlMark& stackMark)
     at System.Threading.Thread.Start(Object parameter)
     at StackExchange.Redis.SocketManager..ctor(String name, Boolean useHighPrioritySocketThreads) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\SocketManager.cs:line 141
     at StackExchange.Redis.ConnectionMultiplexer.OnCreateReaderWriter(ConfigurationOptions configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.ReaderWriter.cs:line 12 
     at StackExchange.Redis.ConnectionMultiplexer..ctor(ConfigurationOptions configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 939
     at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 839
     at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 862
     at "MyInternalClass"
```

**Comment by NickCraver** [comment]
Can you post your code? Without seeing context this won't make much else - all I can tell is you're calling Connect at the moment. Is this in a loop, or often, or...? Usually we see this from creating many `ConnectionMultiplexer` instances, where we very much intend for you to reuse one for many or all operations.

**Comment by ahan1874** [comment]
I am using the sample code here at my DNS code initializer, it complains about OutOfMemory Exception do starting the thread in socket manager. What is the specific resource that it requires in the writeAllQueues function? I am suspecting that because it's using the high priority socket thread, which conflicts with my native DNS server code.   
[
ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");

                IDatabase db = redis.GetDatabase();

                string value = "abcdefg";
                db.StringSet("mykey", value);
                value = db.StringGet("mykey");
                Console.WriteLine(value); // writes: "abcdefg"

                value = db.StringGet("mykeydoesnotexist");
                Console.WriteLine(value); // writes: "abcdefg"
                if (value == null) Console.WriteLine("getting null value");
]

at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at StackExchange.Redis.SocketManager..ctor(String name, Boolean useHighPrioritySocketThreads) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\SocketManager.cs:line 141
   at StackExchange.Redis.ConnectionMultiplexer.OnCreateReaderWriter(ConfigurationOptions configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.ReaderWriter.cs:line 12
   at StackExchange.Redis.ConnectionMultiplexer..ctor(ConfigurationOptions configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 939
   at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 839
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 862
   at Microsoft.BDM.Pets.Dns.Plugin.PDP.InitInternal()
Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by ahan1874** [comment]
I can share the crash dumps if it's helpful.

**Comment by NickCraver** [comment]
What's the context in which this code runs? Is it creating a new `ConnectionMultiplexer` often, or just once? Also, which version of .NET are you on?

**Comment by FariddSalehi** [comment]
hi ,
i have exactly this problem and get this error and i cant handle it , if your problem solved, could you tell your solution ,
thanks

**Comment by mgravell** [comment]
@FariddSalehi  this issue is probably obsolete given the 2.0 work, which fundamentally rewrites the entire network layer to deal with a *wide range* of problems relating to sockets, and the reader/writer implementation. I'm going to defer this as a "see [2.0](https://github.com/StackExchange/StackExchange.Redis/issues/871)", because : the code in question literally doesn't exist any more there. ETA on 2.0 is "soon", so it is unlikely that we're going to do any significant investigation work into straggling 1.* network issues, when the entire point of 2.0 is to rewrite all of that.
