### ISSUE TITLE
Timeout and No connection is available

### ISSUE THREAD

**Issue by AndersTT** [StackExchange/StackExchange.Redis#431]
Hi all,

Recently we used StackExchange.Redis instead of ServiceStack.Redis in our production environment , but we got two kinds of exceptions from time to time: System.TimeoutException & No connection is available to service this operation . Can someone explain the root cause of these errors ? Below is the stack trace of two exceptions:

First:
```
No connection is available to service this operation: HGET ---> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: HGET 20140911||User
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1860
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 80
   at StackExchange.Redis.RedisDatabase.HashGet(RedisKey key, RedisValue hashField, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 118
   at NextPms.Logic.Cache.Redis.RedisCacheClient.TryGet(Type typeSpace, Type expectType, String key, Object& value) in c:\BuildAgent\work\959af5bd7eabbba9\NextPms.Logic\Cache\Redis\RedisCacheClient.cs:line 185
```
Second:
```
System.TimeoutException: Timeout performing HGET inst: 1, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), clientName: WEBSERVER1
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1927
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 80
   at StackExchange.Redis.RedisDatabase.HashGet(RedisKey key, RedisValue hashField, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 118
   at NextPms.Logic.Cache.Redis.RedisCacheClient.TryGet(Type typeSpace, Type expectType, String key, Object& value) in c:\BuildAgent\work\959af5bd7eabbba9\NextPms.Logic\Cache\Redis\RedisCacheClient.cs:line 203
```

**Comment by NickCraver** [comment]
Related to #450
