### ISSUE TITLE
[.Net Core] NullReferenceException thrown from StringIncrementAsync(...) when Redis is offline.

### ISSUE THREAD

**Issue by KennethRMason** [StackExchange/StackExchange.Redis#483]
When calling an `Async` method like this, no `Exception` should be thrown until the `Task` is `await`ed.  Kicking off the `Task` itself should never result in an `Exception`.  In this particular case, if Redis is offline, `StringIncrementAsync(...)` and likely all of the other `*Async(...)` methods throw a `NullReferenceException` from the guts of the library.

```
System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=StackExchange.Redis
  StackTrace:
       at StackExchange.Redis.ServerEndPoint.get_LastException()
       at StackExchange.Redis.ExceptionFactory.GetServerSnapshotInnerExceptions(ServerEndPoint[] serverSnapshot)
       at StackExchange.Redis.ExceptionFactory.NoConnectionAvailable(Boolean includeDetail, RedisCommand command, Message message, ServerEndPoint server, ServerEndPoint[] serverSnapshot)
       at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server)
       at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
       at ... .MoveNext() in ... .cs:line ...
  InnerException: null
```

Here's what consumption of the library looks like, that generated this `Exception` (stitching together the bit inside the DI setup with the actual call): 
```
            IDatabase _conn = ConnectionMultiplexer.Connect(...).GetDatabase();
            Task<long> incrementTask = _conn.StringIncrementAsync(... , flags: CommandFlags.DemandMaster);
```

Here's my work-around:
```
            Task<long> incrementTask;
            try
            {
                incrementTask = _conn.StringIncrementAsync(... , flags: CommandFlags.DemandMaster);
            }
            catch (NullReferenceException e)
            {
                //An async method like this should not be throwing an Exception (if anything, the Exception should be thrown within the Task), 
                //but there seems to be a bug in the Redis framework where a NullReferenceException is thrown here if Redis is offline, from deep in the guts of their lib.
                //Treat this the same as we would for a RedisConnectionException thrown from inside the Task.
                _logger.LogError(...);
                ...
            }
```

**Comment by aensidhe** [comment]
Can confirm this on .net 4.6.

**Comment by mgravell** [comment]
Will investigate, thanks.

**Comment by aensidhe** [comment]
Actually, fixed in https://github.com/StackExchange/StackExchange.Redis/commit/d6a734c5a43dfa680b74ffbad4d5833a69d33bd9

Recommend course of action is to update to https://github.com/StackExchange/StackExchange.Redis/releases/tag/1.1.605

We were on 1.1.603.

@mgravell thanks and sorry for misleading.

**Comment by KennethRMason** [comment]
Thanks for the fix!
