### ISSUE TITLE
RedisConnectionException: No connection is available to service this operation

### ISSUE THREAD

**Issue by laoshancun** [StackExchange/StackExchange.Redis#521]
hi,
i'm using `StackExchange.Redis.StrongName 1.1.604 `as dotnet core session middleware storage.
when deploy to linux server,it says the following error.

### connection string:
`192.168.0.2:6379,abortConnect=false,connectTimeout=10000`
### redis version 
3.2.5
### error stack:
```
waf_waf_1 | 2016-11-08T03:21:54.593792210Z StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL ---> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout
waf_waf_1 | 2016-11-08T03:21:54.593826092Z    --- End of inner exception stack trace ---
waf_waf_1 | 2016-11-08T03:21:54.593836780Z    at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
waf_waf_1 | 2016-11-08T03:21:54.593842793Z --- End of stack trace from previous location where exception was thrown ---
waf_waf_1 | 2016-11-08T03:21:54.593847854Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
waf_waf_1 | 2016-11-08T03:21:54.593890584Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
waf_waf_1 | 2016-11-08T03:21:54.593908477Z    at Microsoft.Extensions.Caching.Redis.RedisExtensions.<HashMemberGetAsync>d__2.MoveNext() in /root/waf/Extensions/RedisExtensions.cs:line 30
waf_waf_1 | 2016-11-08T03:21:54.593972950Z --- End of stack trace from previous location where exception was thrown ---
waf_waf_1 | 2016-11-08T03:21:54.593991846Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594001061Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594085551Z    at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAndRefreshAsync>d__19.MoveNext() in /root/waf/Extensions/RedisCache.cs:line 239
waf_waf_1 | 2016-11-08T03:21:54.594104088Z --- End of stack trace from previous location where exception was thrown ---
waf_waf_1 | 2016-11-08T03:21:54.594109762Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594116483Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594121715Z    at Microsoft.Extensions.Caching.Redis.RedisCache.<RefreshAsync>d__15.MoveNext() in /root/waf/Extensions/RedisCache.cs:line 152
waf_waf_1 | 2016-11-08T03:21:54.594178463Z --- End of stack trace from previous location where exception was thrown ---
waf_waf_1 | 2016-11-08T03:21:54.594191371Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594196800Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594254523Z    at Microsoft.AspNetCore.Session.DistributedSession.<CommitAsync>d__31.MoveNext()
waf_waf_1 | 2016-11-08T03:21:54.594273438Z --- End of stack trace from previous location where exception was thrown ---
waf_waf_1 | 2016-11-08T03:21:54.594296389Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594303749Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
waf_waf_1 | 2016-11-08T03:21:54.594310175Z    at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
waf_waf_1 | 2016-11-08T03:21:54.594416455Z [100m[32minfo[39m[0m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
waf_waf_1 | 2016-11-08T03:21:55.299233502Z [101m[30mfail[39m[0m: Microsoft.AspNetCore.Session.SessionMiddleware[1]
waf_waf_1 | 2016-11-08T03:21:55.299246197Z       Error closing the session.
```

**Comment by NickCraver** [comment]
This error was fixed in the 1.2.x line - just following up on some duplicate issues here to close out. Sorry it took us a while to figure out what was happening here and even longer to address the backlog. 

For anyone else hitting this: upgrade to the latest lib (1.2.6 as I'm writing this).
