### ISSUE TITLE
System.Net.Sockets.SocketException: "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full" to Redis Cluster

### ISSUE THREAD

**Issue by setiseeker** [StackExchange/StackExchange.Redis#534]
After running against a redis cluster with 6 masters spread over two servers (each master has two slaves),
our ASP.net application, running under IIS started throwing the following exceptions after it had been running problem free for a few hours.

**We are trying to understand what this means and how to prevent this in future**

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> 
System.Net.Sockets.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
 at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
 at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
 at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
 at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
 at StackExchange.Redis.SocketManager.<>c__DisplayClassa.b__3(AsyncCallback cb)
 at StackExchange.Redis.CompletionTypeHelper.RunWithCompletionType(Func`2 beginAsync, AsyncCallback callback, CompletionType completionType)
 at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log)
 at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log)
 at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log)
 at StackExchange.Redis.ServerEndPoint..ctor(ConnectionMultiplexer multiplexer, EndPoint endpoint, TextWriter log)
 at StackExchange.Redis.ConnectionMultiplexer.d__33.MoveNext() --- End of inner exception stack trace ---

 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at System.Threading.Tasks.Task`1.get_Result()
 at StackExchange.Redis.ConnectionMultiplexer.<>c__DisplayClass2f.b__2c()
 at System.Threading.Tasks.Task`1.InnerInvoke()
 at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace ---

 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
 at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
 at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
 at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log)
```

Research seems to suggest that we starved the system of ports to use, however I am uncertain of this. We have been running the same application to a single redis instance and have never had this exception.

**Comment by NickCraver** [comment]
This certainly looks like ephemeral port exhaustion. Can you get a `netstat` dump when it happens?

Also, are you re-creating a `ConnectionMultiplexer` often, or re-using a long-running instance?

**Comment by setiseeker** [comment]
Thank you for the rapid response.

Looking through the code, most of the time only one instance of the
ConnectionMultiplexer is created and shared. But I have found one area
where we keep re-creating this.

If ConnectionMultiplexer it is getting re-used correctly, should only one
connection be shown when using netstat?

When moving to the cluster, is it fair to say that a connection to each
redis instance would be created, and that's why we see this only when
connection to a cluster?

Regards

Ian

**Comment by setiseeker** [comment]
This was indeed a connection leak. This became more evident when using the cluster.

We confirmed this using the command `redis-cli client list`  to see the number of connection we opened to redis.

Thank you for the assistance.
