### ISSUE TITLE
SocketFailure RedisConnectionException

### ISSUE THREAD

**Issue by CesarNobre** [StackExchange/StackExchange.Redis#556]
Hi everyone

I've seen that Redis Stack Exchange releases Socket Failure through RedisConnectionException but I do not know where to start investigating this. Anyone have suggestions?

```
 Exception: StackExchange.Redis.RedisConnectionException - SocketFailure on GET
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1836
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 80
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1451
```

**Comment by muhamadahsan** [comment]
I am also having the same exception but no clue...
@NickCraver: Any suggestions or solution?

**Comment by pragmaticqa** [comment]
did anyone identify the problem here? We are seeing this against azure hosted redis

**Comment by muhamad-ahsan** [comment]
So far there is no update on this issue. I am waiting since Feb....

**Comment by niemyjski** [comment]
Any updates on this?

**Comment by Theboss83** [comment]
I have the same problem. It seems the connection is corrupted and StackExchange.Redis doesn't try to reconnect automatically. Any solution?

**Comment by mgravell** [comment]
We haven't been able to repro this on demand to nail it down. We know it is
causing intermittent problems, and it is on "the list". Hopefully should be
able to carve out some time to have another look in the new year. Parallel
with this, there is also ongoing work to overhaul the entire network core -
although this is mixed in with the "pipelines" work for asp.net, so no
current release date on that (it is still in evolution). The point being:
it is hoped that this work will stabilise this oddness.

**Comment by mgravell** [comment]
Closing: see https://github.com/StackExchange/StackExchange.Redis/issues/871
