### ISSUE TITLE
No availiable socket connection

### ISSUE THREAD

**Issue by bargitta** [StackExchange/StackExchange.Redis#586]
Hello,
I receive below errors when connecting to Redis on Azure. I want to know how many socket connection will it create? Can I control the number? I notice many connections to my Azure Redis instance.

```
:[No connection is available to service this operation: MGET {1}1:1d2743a7741f43d8b667a9703f005292; SocketFailure on 10.0.8.10:6379/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 24, last-read: 4s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), Local-CPU: unavailable],Detail:[System.AggregateException: One or more errors occurred. ---> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: MGET {1}1:1d2743a7741f43d8b667a9703f005292; SocketFailure on 10.0.8.10:6379/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 24, last-read: 4s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), Local-CPU: unavailable ---> System.AggregateException: One or more errors occurred. ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 10.0.8.10:6379/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 24, last-read: 4s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.Extensions.Core.StackExchangeRedisCacheClient.GetAll[T](IEnumerable`1 keys)
```

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
