### ISSUE TITLE
Not able to execute Object command through the nuget

### ISSUE THREAD

**Issue by Purbasha** [StackExchange/StackExchange.Redis#630]
Hi,
I am trying to execute the "DebugObject" command from the StackExchange.redis nuget, which is supposed to be the wrapper for Object command in Redis. I am connecting with allowAdmin=true. However, I always get this error:

> "An unhandled exception of type 'StackExchange.Redis.RedisServerException' occurred in StackExchange.Redis.dll

Additional information: ERR unknown command: DEBUG"
```
StackTrace:    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.DebugObject(RedisKey key, CommandFlags flags)
   at RedisPopulator.Program.Main(String[] args) in F:\Scribble\RedisPopulator\RedisPopulator\Program.cs:line 44
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by NickCraver** [comment]
Can you please provide a code sample of how you were trying to run it?

**Comment by mgravell** [comment]
What server are you connecting to? Do you own it, or is it AWS / Azure / RedisLabs / some-other-cloud?

Note that *hosted* providers *almost always* disable the `DEBUG` command. One reason of which is the presence of the [`DEBUG SEGFAULT`](https://redis.io/commands/debug-segfault) command which *literally* crashes the server. Intentionally.

If the `DEBUG` command is disabled, SE.Redis can't possibly use it.

**Comment by NickCraver** [comment]
No new information here, so closing out to clean up. If there are any more questions please comment here and I'll reopen!
