### ISSUE TITLE
Unable to connect to cluster after upgrade

### ISSUE THREAD

**Issue by kaoticfx** [StackExchange/StackExchange.Redis#672]
We are testing v4.0.1 Redis and are unable to connect to the cluster after the upgrade.  Everything works fine on v3.2.9.  Any suggestions or recommendations would be greatly appreciated.

Error message when connecting:
Trying to set: 7/27/2017 1:16:32 PM
StackExchange.Redis.RedisConnectionException: No connection is available to serv
ice this operation: SETEX Test1 ---> System.AggregateException: One or more erro
rs occurred. ---> StackExchange.Redis.RedisConnectionException: InternalFailure
on DA3MAAL001:6379/Interactive, origin: EndReading, input-buffer: 1629, outstand
ing: 1, last-read: 0s ago, last-write: 0s ago, unanswered-write: 459822s ago, ke
ep-alive: 60s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never,
last-mbeat: -1s ago, global: 0s ago ---> System.ArgumentNullException: Value can
not be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at StackExchange.Redis.ClusterConfiguration..ctor(ServerSelectionStrategy ser
verSelectionStrategy, String nodes, EndPoint origin)
   at StackExchange.Redis.ResultProcessor.ClusterNodesProcessor.Parse(PhysicalCo
nnection connection, String nodes)
   at StackExchange.Redis.ResultProcessor.ClusterNodesProcessor.SetResultCore(Ph
ysicalConnection connection, Message message, RawResult result)
   at StackExchange.Redis.ResultProcessor.SetResult(PhysicalConnection connectio
n, Message message, RawResult result)
   at StackExchange.Redis.PhysicalConnection.MatchResult(RawResult result)
   at StackExchange.Redis.PhysicalConnection.ProcessBuffer(Byte[] underlying, In
t32& offset, Int32& count)
   at StackExchange.Redis.PhysicalConnection.ProcessReadBytes(Int32 bytesRead)
   at StackExchange.Redis.PhysicalConnection.EndReading(IAsyncResult result)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message messa
ge, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProces
sor`1 processor, ServerEndPoint server)
   at ConsoleApplication1.Program.RedisLists(String serverList)
   at ConsoleApplication1.Program.Execute()
   at ConsoleApplication1.Program.Main()
Done (elapsed: 00:00:00.4305181). Press <enter> to exit.

**Comment by dotnetpro9** [comment]
Similar exception when using Redis 4.0.1

[RedisConnectionException: No connection is available to service this operation: GET xxxxx-xxxxx-xxxxx-xxxxx; Value cannot be null.
Parameter name: key; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=4,Free=4091,Min=4,Max=4095), Local-CPU: 9.96%]
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) +1801
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) +74
   StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) +148
   PageStatePersisters.RedisPageStatePersister.GetPageState(String guid) +133
   PageStatePersisters.RedisPageStatePersister.Load() +87
   System.Web.UI.Page.LoadPageStateFromPersistenceMedium() +47
   System.Web.UI.Page.LoadAllState() +36
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1743

**Comment by mgravell** [comment]
Hi; this is a breaking change in redis itself: https://github.com/antirez/redis/issues/4186

I have released a new client library build that fixes this - it should work from 1.2.6 onwards.
