### ISSUE TITLE
System.PlatformNotSupportedException occur when connect to DnsEndPoint in Unix OS

### ISSUE THREAD

**Issue by OpenSourceAries** [StackExchange/StackExchange.Redis#687]
Exception Message: 
Unhandled Exception: System.AggregateException: One or more errors occurred. (This platform does not support connecting sockets to DNS endpoints via tntial for a host name to map to multiple IP addresses and sockets becoming invalid for use after a failed connect attempt. Use the static ConnectAsyncdress desired.) ---> System.PlatformNotSupportedException: This platform does not support connecting sockets to DNS endpoints via the instance Connectme to map to multiple IP addresses and sockets becoming invalid for use after a failed connect attempt. Use the static ConnectAsync method, or provide
   at System.Net.Sockets.Socket.ThrowIfNotSupportsMultipleConnectAttempts()
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__5_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 ar
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, String host, Int32 port)
   at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log) ige\Redis\SocketManager.cs:line 193

**It seems that we should use Socket static ConnectAsync method instead of instance ConnectAsync method(or SocketTaskExtension ConnectAsync method which inner call BeginConnect method) for CORE_CLR since the static ConnectAsync method is the only *Connect* API that actually supports multiple endpoint attempts**

**Comment by NickCraver** [comment]
After getting current PRs in, I'll do a lot of cleanup (and C# 7) then move on to `netstandard2.0`, which will add this back. It's a .NET Core issue we have no control over, but brought back in 2.0.

**Comment by NickCraver** [comment]
.NET Core 2.0 has been out a while now...that's the proper solution here. It missing was a real pain in 1.x, but it's gone now. An upgrade to .NET Core 2.x will resolve this for anyone finding it later :)

**Comment by OpenSourceAries** [comment]
@NickCraver  I tried, and this fix in .net core 2.1, thank you!
