### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException 1.2.6

### ISSUE THREAD

**Issue by shaddockblack** [StackExchange/StackExchange.Redis#706]
```
StackExchange.Redis.RedisTimeoutException: Timeout performing HGETALL PriceStrategyConfig, inst: 5, queue: 5, qu: 0, qs: 5, qc: 0, wr: 0, wq: 0, in: 9, ar: 0, clientName: , serverEndpoint: Unspecified/r-bp1734ef2b8e7a24.redis.rds.aliyuncs.com:6379, keyHashSlot: 448 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.HashGetAll(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 298
   at CtPayRisk.Redis.PriceStrategyRedis.<>c__0`1.<GetPriceStrategy>b__0_0()
   at CtPayRisk.Redis.Core.RedisRetryHelper.Retry[T](Func`1 retryme, Int32 retries, Int32 timeOut)
   at CtPayRisk.Redis.PriceStrategyRedis.GetPriceStrategy[T]()
```

**Comment by tuananh** [comment]
@NickCraver hi Nick, is there any finding for this issue?

**Comment by NickCraver** [comment]
How large are the hashes in play here? If they are massive, you'll need to up the timeouts in your connection config, as they may be too large to complete in the default 5 second window (or whatever your current setting is).

**Comment by mgravell** [comment]
Closing; please see #871

**Comment by gkorland** [comment]
@shaddockblack I know it has been couple of years since you open this issue, but did you manage to overcome the issue with 1.2.6? Or was the solution upgrade to 2.x?
