### ISSUE TITLE
RedisTimeoutException

### ISSUE THREAD

**Issue by jchannon** [StackExchange/StackExchange.Redis#715]
We have been getting the above exception recently, or we have just started to notice it.  We are on release 1.2.4 on netcore1.1.  We upped the version to 1.2.6 and still see the issue.  We get it by simple getting a value out of Redis and can reproduce it in our codepath 100%.  We upgraded our whole application to netcore2.0 and we still see this. We obviously can get more details about the number of threads in use and available now we are on netcore2.0 (https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md) but we still see the issue when we have thousands of threads set to the minimum level.  We have printed out the details in our codebase which you can see at the bottom of the stack trace below.

```
StackExchange.Redis.RedisTimeoutException: Timeout performing GET Settings.DefaultTimeZoneId, inst: 1, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 149, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379, keyHashSlot: 8606 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647
   at VQCore.Cache.RedisCache.<>c__DisplayClass17_0.<GetValue>b__0() in /Users/richard/Documents/SourceCode/vq/src/VQCore/Cache/RedisCache.cs:line 143
   at Polly.Policy.<>c__DisplayClass71_0`1.<Execute>b__0(CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass27_0`1.<Execute>b__0(CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass3_0.<Retry>b__1(CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`2 action, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass3_1.<Retry>b__0(Action`1 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at VQCore.Cache.RedisCache.GetValue(String key) in /Users/richard/Documents/SourceCode/vq/src/VQCore/Cache/RedisCache.cs:line 143
   at VQCore.Cache.RedisCache.GetObject[T](String key) in /Users/richard/Documents/SourceCode/vq/src/VQCore/Cache/RedisCache.cs:line 133
   at VQCore.Settings.SettingProvider.GetSetting(Settings key) in /Users/richard/Documents/SourceCode/vq/src/VQCore/Settings/SettingProvider.cs:line 41
[IO] (Busy=0,Free=1000,Min=1000,Max=1000)
[WORKER] (Busy=13,Free=32754,Min=32767,Max=32767)
```

**Comment by sergevm** [comment]
We had time-out issues for a while too on an instance of a Redis server in Azure. Scaled the Redis service up and the issues vanished. It was probably a combination with an inefficiënt method that we also improved upon.  Still have a backlog item to get deeper into this though. My gut feeling was that  it had to do with the allowed bandwith for the instance.

**Comment by JoeStead** [comment]
This issue is happening on a local instance hosted in docker. We're using redis to store/retrieve tiny amounts of data (we're talking bytes). We've taken a look at thread usage (as @jchannon shows), cpu usage, and network usage to see if there is anything out of the ordinary. There isn't. We're completely confused by it

**Comment by NickCraver** [comment]
There was a nasty build error for a few releases, and 1.2.4 was affected. Please upgrade to 1.2.6 or higher to see this resolved :)
