### ISSUE TITLE
System.TimeoutException From ConnectionMultiplexer

### ISSUE THREAD

**Issue by anarian** [StackExchange/StackExchange.Redis#773]
We've noticed our server under heavy load sometimes receives this exception:

```
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. —> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. —> System.TypeInitializationException: The type initializer for 'NAMESPACEREDACTED.ResourceProviderFactory' threw an exception. —> System.TimeoutException: The operation has timed out.
    at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task)
    at StackExchange.Redis.RedisSubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags)
    // Other stack trace from our own code that calls Subscribe
```

The function that calls Subscribe is here:
```
public static class NotificationService {
    private static readonly ISubscriber Subscriber;
    static NotificationService()
    {
        if (!string.IsNullOrEmpty(ConfigurationManager.ConnectionStrings["Redis"]?.ConnectionString))
        {
            var connection = ConnectionMultiplexer.Connect(ConfigurationManager.ConnectionStrings["Redis"].ConnectionString);
            Subscriber = connection.GetSubscriber();
        }
    }

    public static void Subscribe(string channelId, Action<string> handler)
    {
        Subscriber?.Subscribe(channelId, (channel, msg) => // Stack trace shows function is thrown here
        {
            // Handler code
        });
    }
}
```

Connection string used: `192.168.151.51:6379,abortConnect=false` which is a Ubuntu 16.04 LTS server running Redis Server v4.0.7, with the client ASP.NET application using Nuget assembly StackExchange.Redis.StrongName version 1.2.6.0 on .NET Framework 4.6.2 on Windows Server 2012 R2.

Should this be updated to a `RedisTimeoutException` so we can get information about the current network/Redis queue state to help in diagnosing where this problem is occurring?

**Comment by NickCraver** [comment]
In this case it *was* a redis exception, but the application wrapped it, probably in a try/catch. If you look in there, you'll find the inner exception already has what you want. The library never throws any HTTP exceptions :)
