### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: No connection is available 

### ISSUE THREAD

**Issue by dayanandavt** [StackExchange/StackExchange.Redis#793]
Hello,

we are using StackExchange.Redis library to leverage the Redis caching capabilities and it has been doing good most of the time but we are constantly seeing few exceptions in our production and load testing where few cache calls are getting Timing out intermittently and affecting our performance significantly.  

Below are the set of exceptions we are have been witnessing and by looking at the stack trace exception  is happening in StackExchange ConnectionMultiplexer.cs.   So, wanted to know what is the solution for these issues and are there any workaround.

_Note: this is the configuration values we are using.
redisCacheClient allowAdmin="true" ssl="false" connectTimeout="5000" database="0" password="password"_

**************************************************
**Exception 1:**

	StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SETEX deb5c135cb2147a1941c7f3de9e84211_ClientPreferences ---> StackExchange.Redis.RedisConnectionException: SocketFailure on DNSNAME.com:10002/Interactive, origin: CheckForStaleConnection, input-buffer: 4850, outstanding: 18, last-read: 1s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2044
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.Extensions.Core.StackExchangeRedisCacheClient.Add[T](String key, T value, TimeSpan expiresIn)
   at App.Caching.RedisCacheProvider.PutObjectInCache[T](String containerID, String cacheObjectKey, T cacheObjectValue, Boolean suppressErrors) in 
   
   ******************************************************************************************************************

**Exception 2:**
   
   System.TimeoutException: Timeout performing GET 9adfbfd66e8a4ae1878660af389cc923_ClientPreferences, inst: 14, mgr: RecordConnectionFailed_FailOutstanding, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: NC006VTesE57, IOCP: (Busy=12,Free=988,Min=12,Max=1000), WORKER: (Busy=9,Free=32758,Min=12,Max=32767), Local-CPU: 40.43% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2044
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1449
   at StackExchange.Redis.Extensions.Core.StackExchangeRedisCacheClient.Get[T](String key)
   at App.Caching.RedisCacheProvider.GetObjectFromCache[T](String containerID, String cacheObjectKey, Boolean suppressErrors) in 
   
   ******************************************************************************************************************
   
**Exception 3:**
   
   System.TimeoutException: Timeout performing SETEX 1b711b9ca59b4b8e947201b5a2e3165c_ClientPreferences, inst: 8, mgr: RecordConnectionFailed_FailOutstanding, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: NC006VTesE5B, IOCP: (Busy=4,Free=996,Min=12,Max=1000), WORKER: (Busy=10,Free=32757,Min=12,Max=32767), Local-CPU: 0% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2044
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.Extensions.Core.StackExchangeRedisCacheClient.Add[T](String key, T value, TimeSpan expiresIn)
   at App.Caching.RedisCacheProvider.PutObjectInCache[T](String containerID, String cacheObjectKey, T cacheObjectValue, Boolean suppressErrors) in

**Comment by NickCraver** [comment]
Are you still seeing this on the 1.2.6 (or higher) release? We fixed some nasty connection bugs in that one, which line up with what you saw.

**Comment by endeffects** [comment]
We have the same problems with the latest version (1.2.6)

**Comment by ByronAP** [comment]
Same here I was getting a disconnected multiplexer error so I added the recommended workaround options and now I get "No connection is available to service this operation"

**Comment by mgravell** [comment]
@dayanandavt  can you clarify what your version numbers refer to? This lib only goes to 1.2.7 right now.

Important: the work I'm doing for 2.0 is actively targeting connection stability - I'm essentially completely rewriting the network core.

**Comment by dayanandavt** [comment]
I am referring the NuGet package manager version. Please refer the image attached
![stackexchgversion](https://user-images.githubusercontent.com/33039842/42011969-fdc7e19a-7a63-11e8-8547-6464451269ea.PNG)

**Comment by mgravell** [comment]
@dayanandavt That package is nothing to do with us and we cannot comment on anything to do with it. That's a 3rd party (4th party?) lib that appears to add serialization APIs.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
