### ISSUE TITLE
Timeout performing GET 292

### ISSUE THREAD

**Issue by EminemJK** [StackExchange/StackExchange.Redis#815]
```
StackExchange.Redis   
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81   
at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647   
at ZhujiaService.Core.Redis.RedisUtils.StringGet[T](Int32 dbIndex, String key)   
at ZhujiaService.Core.Redis.RedisHelper.GetObject_KV[T](Int32 dbIndex, String key, Func`1 func, Nullable`1 timeout)   
at Zhujia100.Client.ApiCode.V1.Product.Controllers.ElectricalController.ListForAttributes(CategoryInfo info) in C:\Program Files (x86)\Jenkins\workspace\Backend-Zhujia-C\Zhujia100.Client\ApiCode\V1\Product\Controllers\ElectricalController.cs:line 458   
at Zhujia100.Client.ApiCode.V1.Product.Controllers.ElectricalController.GetAttrs(String c, String filter) in C:\Program Files (x86)\Jenkins\workspace\Backend-Zhujia-C\Zhujia100.Client\ApiCode\V1\Product\Controllers\ElectricalController.cs:line 421   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)   
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
Timeout performing GET 292, inst: 1, queue: 16, qu: 0, qs: 16, qc: 0, wr: 0, wq: 0, in: 21833, ar: 0, clientName: WIN-PCUJ6SI166A, serverEndpoint: 172.16.3.81:6379, keyHashSlot: 729 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

**Comment by NickCraver** [comment]
This error indicates that bytes were on the inbound buffer and unable to be read. Was the application under high load at this time?

**Comment by EminemJK** [comment]
@NickCraver

**Comment by EminemJK** [comment]
@NickCraver   No, it's normal environment

**Comment by NickCraver** [comment]
@EminemJK which version of the library are you currently on?

**Comment by EminemJK** [comment]
@NickCraver  1.2.6

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
