### ISSUE TITLE
Nested transactions are not supported

### ISSUE THREAD

**Issue by tvd12** [StackExchange/StackExchange.Redis#823]
```csharp
public IBatch CreateBatch(object asyncState)
        {
            if (this is IBatch) throw new NotSupportedException("Nested batches are not supported");
            return new RedisBatch(this, asyncState);
        }

        public ITransaction CreateTransaction(object asyncState)
        {
            if (this is IBatch) throw new NotSupportedException("Nested transactions are not supported");
            return new RedisTransaction(this, asyncState);
        }
```

I think It must be:

```csharp
public IBatch CreateBatch(object asyncState)
        {
            if (this is IBatch) throw new NotSupportedException("Nested batches are not supported");
            return new RedisBatch(this, asyncState);
        }

        public ITransaction CreateTransaction(object asyncState)
        {
            if (this is ITransaction) throw new NotSupportedException("Nested transactions are not supported");
            return new RedisTransaction(this, asyncState);
        }
```

**Comment by NickCraver** [comment]
This is behaving as designed, because `ITransaction` implements `IBatch`, so you'd have to cast to get into this state, but the exception check is the correct one (it's not supported in batches or transactions). Still, I've added a test in f916a5bd935adf7a40f159e8c033ced85669a87e to ensure this gets checked :)

**Comment by tvd12** [comment]
So, why when I run this code:

```csharp
var configuration = ConfigurationOptions.Parse("127.0.0.1:6379", true);
            configuration.ResolveDns = true;
            var redis = ConnectionMultiplexer.Connect(configuration);
            var db = redis.GetDatabase();

            db.HashSet("map", 1L, 0L);
            db.HashSet("map", 2L, 0L);
            db.HashSet("map", 3L, 0L);
            IBatch batch1 = db.CreateBatch();
            batch1.LockTakeAsync("map", 1L, TimeSpan.FromSeconds(15));
            batch1.LockTakeAsync("map", 2L, TimeSpan.FromSeconds(15));
            batch1.LockTakeAsync("map", 3L, TimeSpan.FromSeconds(15));
            batch1.Execute();

            Thread.Sleep(3000);

            IBatch batch2 = db.CreateBatch();
            batch2.LockReleaseAsync("map", 1L);
            batch2.LockReleaseAsync("map", 2L);
            batch2.LockReleaseAsync("map", 3L);
            batch2.Execute();
```
I've gotten:

```csharp
Unhandled Exception: System.NotSupportedException: Nested transactions are not supported
   at StackExchange.Redis.RedisDatabase.CreateTransaction(Object asyncState) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 30
   at StackExchange.Redis.RedisDatabase.CreateTransactionIfAvailable(Object asyncState) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 41
   at StackExchange.Redis.RedisDatabase.GetLockReleaseTransaction(RedisKey key, RedisValue value) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1901
   at StackExchange.Redis.RedisDatabase.LockReleaseAsync(RedisKey key, RedisValue value, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1014
   at RedLotoCommonTest.RedisTest.Test() in /Users/tavandung12/Documents/ecorau/redlotto/RedLotoCommon/RedLotoCommonTest/RedisTest.cs:line 28
   at RedLotoRedis.Program.Main(String[] args) in /Users/tavandung12/Documents/ecorau/redlotto/RedLotoCommon/RedLotoCommonTest/Program.cs:line 41
bash: line 1:  6151 Abort trap: 6           "/usr/local/share/dotnet/dotnet" "/Users/tavandung12/Documents/ecorau/redlotto/RedLotoCommon/RedLotoCommonTest/bin/Debug/netcoreapp2.0/RedLotoCommonTest.dll"
```
