### ISSUE TITLE
Crash when disconnect after many publish 2.0.0 alpha463

### ISSUE THREAD

**Issue by imtrobin** [StackExchange/StackExchange.Redis#923]
Hi, I'm facing a crash when I close redis (my app quit) after I do many publish. I was flooding publish (in another app) in a loop (only 99 times). After I receive all the messages, quit app, crash.

This is on 4.6.1, debug mode,

```
 public void                                                         DisconnectRedis ()
 {
       if (null != redisConnection_)
           redisConnection_.Close ();
       redisConnection_ = null;
 }

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Redis.CompletionManager.PerInstanceCompleteSyncOrAsync(ICompletable operation)
   at StackExchange.Redis.PhysicalConnection.RecordConnectionFailed(ConnectionFailureType failureType, Exception innerException, String origin, Boolean isInitialConnect, IDuplexPipe connectingPipe, String path, Int32 line)
   at StackExchange.Redis.PhysicalConnection.Dispose()
   at StackExchange.Redis.PhysicalBridge.Dispose()
   at StackExchange.Redis.ServerEndPoint.Dispose()
   at StackExchange.Redis.ConnectionMultiplexer.DisposeAndClearServers()
   at StackExchange.Redis.ConnectionMultiplexer.Close(Boolean allowCommandsToComplete)
   at XXXX.DisconnectRedis()
   at XXXX.Finalize()
```

The exception is

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {"Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'."} | System.ObjectDisposedException
in
>	StackExchange.Redis.dll!StackExchange.Redis.PhysicalConnection.Shutdown() Line 244	C#

**Comment by mgravell** [comment]
Hi; sorry for delay - vacations, etc.

I've been unable to reproduce anything specific here, but: I notice that the entry-point here appears to be "finalize". If this is a `~Foo()` finalizer, then I suspect that we're in "undefined behaviour" territory - you shouldn't really be touching *any* other managed objects (except `this`) in a finalizer, as you have no guarantees whatsoever about GC status / order. If you move this to an `IDisposable` implementation, do you still get the error? If so, do you have any minimal code that I can use to repro the fail?

**Comment by imtrobin** [comment]
Can't reproduce this on 2.0.495, so consider it fixed!
