### ISSUE TITLE
An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=399,Min=200,Max=400), WORKER: (Busy=1,Free=399,Min=200,Max=400), Local-CPU: n/a

### ISSUE THREAD

**Issue by edevasimjaved** [StackExchange/StackExchange.Redis#929]
Hi,

I am facing the following error:

No connection is available to service this operation: EXISTS lic-pch-tremblays||FEATURESCOUNT; An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=399,Min=200,Max=400), WORKER: (Busy=1,Free=399,Min=200,Max=400), Local-CPU: n/a
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags)
   at inteGREAT.Web.Common.RedisHelper.KeyExist(String key)

SocketFailure on NCRTFSDEV:6379/Subscription, origin: Read, input-buffer: 0, outstanding: 0, last-read: 48s ago, last-write: 48s ago, unanswered-write: 14701s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 1, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: ProcessReadQueue, err: never

Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at StackExchange.Redis.PhysicalConnection.StackExchange.Redis.ISocketCallback.Read()

An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

kindly investigate and identify the root cause of this issue.

**Comment by mgravell** [comment]
I assume you're using v1.*? If so, the first step will be "try 2.*" (Which
should be released RTM probably tomorrow). We have completely overhauled
the network layer to deal with a wide range of network stability problems.

**Comment by mgravell** [comment]
Rolling into #871, since 2.0 is shipping this week

**Comment by edevasimjaved** [comment]
Hi,
As per your suggestion we have upgraded StackExchange.Redis to 2.* and after update not able to get the error  in most of the cases.

However, even in StackExchange.Redis 2.* we have encounter this issue few times. 
can you suggest what should we can look in order to handle.?

the error stack trace is as following.

No connection is available to service this operation: EXISTS 7efb5327-0ba9-4b3c-b9ca-32a78ba7e713 : WorkSpaceSession; An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), Local-CPU: n/a
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2194
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 649
   at inteGREAT.Web.Common.RedisHelper.KeyExist(String key)

SocketFailure (ReadSocketError/ConnectionReset, last-recv: 49) on localhost:6379/Subscription, Idle, last: UNSUBSCRIBE, origin: ReadFromPipe, outstanding: 1, last-read: 2715s ago, last-write: 0s ago, unanswered-write: 2715s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 8 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.519.65453


An existing connection was forcibly closed by the remote host
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at StackExchange.Redis.PhysicalConnection.<ReadFromPipe>d__104.MoveNext()

An existing connection was forcibly closed by the remote host
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 85
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 73
   at Pipelines.Sockets.Unofficial.SocketConnection.<DoReceiveAsync>d__65.MoveNext() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 59

**Comment by edevasimjaved** [comment]
Any Update
