### ISSUE TITLE
error when connecting to the server

### ISSUE THREAD

**Issue by lol1pop** [StackExchange/StackExchange.Redis#931]
Hello!
Need help, I looked all the Issue and could not find an answer to my case.

```
var options = new ConfigurationOptions  
            {  
                EndPoints = { { "192.168.0.23",6379} },  
                SyncTimeout = int.MaxValue,  
            };  
var connect = ConnectionMultiplexer.Connect(options);  
connect.GetDatabase().Ping();  
return connect;
```

crashes out  Exception:

```
System.MissingMethodException: Method not found: 'System.Buffers.MemoryPool`1<Byte> System.IO.Pipelines.PipeOptions.get_Pool()'.
   at StackExchange.Redis.SocketManager..ctor(String name, Boolean useHighPrioritySocketThreads, Int32 workerCount)
   at StackExchange.Redis.SocketManager.get_Shared() in C:\code\StackExchange.Redis\src\StackExchange.Redis\SocketManager.cs:line 44
   at StackExchange.Redis.ConnectionMultiplexer..ctor(ConfigurationOptions configuration) in C:\code\StackExchange.Redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 1018
   at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in C:\code\StackExchange.Redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 837
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 865
```

(edit by admin: changed stacktrace from quote to code format)

**Comment by mgravell** [comment]
K, this looks like a 2.* issue; can you please indicate exactly what library version and framework version you are targeting here? for example, "2.0.0-alpha.436 targeting net462 on Windows 10", or "2.0.0-alpha.436 targeting netcoreapp2.0 on linux using SDK 2.1.300" ? thanks

**Comment by mgravell** [comment]
This is very odd because `PipeOptions.Pool {get;}` has existed [since pipelines was first merged in to corefx](https://github.com/dotnet/corefx/blame/master/src/System.IO.Pipelines/src/System/IO/Pipelines/PipeOptions.cs) and is not per-environment. I wonder if @davidfowl has any thoughts/insight on this?

**Comment by mgravell** [comment]
Note: if you're target .NET Framework **before net472**, then there are known inherent problems with our hope to target *just* netstandard2.0; so - if you're targeting (for example) net462, then please retry with a more recent build - I've uploaded .465 this morning. This includes an explicit .NET Framework target, to avoid the problems with .NET Framework (prior to net472) targeting .NET Standard 2.0 assets.

**Comment by NickCraver** [comment]
@lol1pop A few fixes went in on builds and bindings to hopefully help out - can you try the 2.0 RTM release [now on NuGet](https://www.nuget.org/packages/StackExchange.Redis) please? It's 2.0.495.

**Comment by NickCraver** [comment]
Closing due to inactivity - see above advice for workarounds but tl;dr: a newer client should be much improved here.
