### ISSUE TITLE
Dotnet core. Redis Timeout Error.

### ISSUE THREAD

**Issue by shootan** [StackExchange/StackExchange.Redis#974]
Hi.
I am using the .NET core and are currently under stress testing.
In a 2-core 8GB RAM environment, there are only about 600 people on the net core server.
Currently, the .NET core server thread has seen the other issues and has set the min and max to 600.
If you set min and max to about 200, 400, you will not have 500 people, which causes timeout problem.
I've tried to get more threads than I am, but with 100% CPU usage, I have new problems.
If you connect about 1000 users in 600 threads, the following message will be displayed.

2018-10-15 17:10:59.5108 [425] [Error] Route fail StackExchange.Redis.RedisTimeoutException: Timeout performing GET common:maintenance_notice, inst: 1, queue: 336, qu: 0, qs: 336, qc: 0, wr: 0, wq: 0, in: 1689, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379, keyHashSlot: 12553 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647

**Comment by LindaLawton** [comment]
> StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 12, queue: 5, qu: 0, qs: 5, qc: 0, wr: 0, wq: 0, in: 38, ar: 0, clientName: , serverEndpoint: Unspecified/redis:6379, keyHashSlot: 9800 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
>    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120

Have you been able to add?  

> <processModel autoConfig="false" minIoThreads="250" />

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
