### ISSUE TITLE
Timeout performing EVAL, inst: 5, queue: 5, qu: 0, qs: 5, qc: 0, wr: 0, wq: 0, in: 8192, ar: 0

### ISSUE THREAD

**Issue by gokhanabatay** [StackExchange/StackExchange.Redis#995]
Hi,
I am trying load test .net core web api with soap ui, When I did with thread strategy simultaneously more than 5 thread it goes slow and slow till timeout. At tcp view I just 5 connection opened to Redis why?
When I looked at below Redis config I see maxclient 10K.

I try 50 thread, 100thread but tcp view shows just 5 connection established to Redis Server.

redis-cli -benchmark command line shows good results but with library I got timeout with simultaneous thread more than 5.

Redis is running on local machine as windows service.

configuraton
```
      "configuration": "localhost,syncTimeout=1000,connectTimeout=5000,connectRetry=3"
 ```
Redis Server config files
[redis.windows.txt](https://github.com/StackExchange/StackExchange.Redis/files/2538641/redis.windows.txt)
[redis.windows-service.txt](https://github.com/StackExchange/StackExchange.Redis/files/2538642/redis.windows-service.txt)

StackTrace:
```
2018-11-01 16:01:50,858 [28  ] WARN  [653600911462458f850951adc795858c] ADOExceptionReporter - Timeout performing EVAL, inst: 5, queue: 5, qu: 0, qs: 5, qc: 0, wr: 0, wq: 0, in: 8192, ar: 0, clientName: CARDTEK0044, serverEndpoint: Unspecified/localhost:6379, keyHashSlot: 10634 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 5, queue: 5, qu: 0, qs: 5, qc: 0, wr: 0, wq: 0, in: 8192, ar: 0, clientName: CARDTEK0044, serverEndpoint: Unspecified/localhost:6379, keyHashSlot: 10634 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1052
   at Microsoft.Extensions.Caching.Redis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(String key, Boolean getData)
   at NHibernate.Caches.CoreDistributedCache.CoreDistributedCache.Get(Object key)
   at NHibernate.Cache.StandardQueryCache.Get(QueryKey key, ICacheAssembler[] returnTypes, Boolean isNaturalKeyLookup, ISet`1 spaces, ISessionImplementor session) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Cache\StandardQueryCache.cs:line 128
   at NHibernate.Cache.StandardQueryCache.Get(QueryKey key, QueryParameters queryParameters, ICacheAssembler[] returnTypes, ISet`1 spaces, ISessionImplementor session) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Cache\StandardQueryCache.cs:line 112
   at NHibernate.Cache.QueryCacheExtensions.Get(IQueryCache queryCache, QueryKey key, QueryParameters queryParameters, ICacheAssembler[] returnTypes, ISet`1 spaces, ISessionImplementor session) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Cache\IQueryCache.cs:line 141
   at NHibernate.Loader.Loader.GetResultFromQueryCache(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IQueryCache queryCache, QueryKey key) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Loader\Loader.cs:line 1733
   at NHibernate.Loader.Loader.ListUsingQueryCache(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Loader\Loader.cs:line 1683
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Loader\Loader.cs:line 1662
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Loader\Hql\QueryLoader.cs:line 287
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Hql\Ast\ANTLR\QueryTranslatorImpl.cs:line 110
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Engine\Query\HQLQueryPlan.cs:line 115
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection) in C:\Users\gokhan.abatay\Desktop\nhibernate-core-SerializedHashcode\src\NHibernate\Impl\SessionImpl.cs:line 541
```

C:\windows\system32>redis-benchmark
====== PING_INLINE ======
100000 requests completed in 1.56 seconds
50 parallel clients
3 bytes payload
keep alive: 1

88.24% <= 1 milliseconds
99.06% <= 2 milliseconds
99.80% <= 3 milliseconds
99.90% <= 4 milliseconds
99.96% <= 5 milliseconds
99.99% <= 6 milliseconds
100.00% <= 6 milliseconds
64061.50 requests per second

====== PING_BULK ======
100000 requests completed in 1.41 seconds
50 parallel clients
3 bytes payload
keep alive: 1

91.91% <= 1 milliseconds
99.25% <= 2 milliseconds
99.82% <= 3 milliseconds
99.97% <= 4 milliseconds
100.00% <= 5 milliseconds
70671.38 requests per second

====== SET ======
100000 requests completed in 1.67 seconds
50 parallel clients
3 bytes payload
keep alive: 1

83.78% <= 1 milliseconds
98.08% <= 2 milliseconds
99.66% <= 3 milliseconds
99.84% <= 4 milliseconds
99.88% <= 5 milliseconds
99.92% <= 6 milliseconds
99.95% <= 8 milliseconds
99.97% <= 9 milliseconds
100.00% <= 9 milliseconds
59844.41 requests per second

====== GET ======
100000 requests completed in 1.47 seconds
50 parallel clients
3 bytes payload
keep alive: 1

89.96% <= 1 milliseconds
99.11% <= 2 milliseconds
99.89% <= 3 milliseconds
99.96% <= 4 milliseconds
100.00% <= 4 milliseconds
68212.83 requests per second

====== INCR ======
100000 requests completed in 1.55 seconds
50 parallel clients
3 bytes payload
keep alive: 1

88.22% <= 1 milliseconds
99.13% <= 2 milliseconds
99.92% <= 3 milliseconds
99.99% <= 4 milliseconds
100.00% <= 4 milliseconds
64308.68 requests per second

====== LPUSH ======
100000 requests completed in 1.64 seconds
50 parallel clients
3 bytes payload
keep alive: 1

84.37% <= 1 milliseconds
98.91% <= 2 milliseconds
99.86% <= 3 milliseconds
99.93% <= 4 milliseconds
99.95% <= 5 milliseconds
99.98% <= 6 milliseconds
100.00% <= 6 milliseconds
61012.81 requests per second

====== RPUSH ======
100000 requests completed in 1.86 seconds
50 parallel clients
3 bytes payload
keep alive: 1

78.14% <= 1 milliseconds
96.81% <= 2 milliseconds
99.30% <= 3 milliseconds
99.80% <= 4 milliseconds
99.99% <= 5 milliseconds
100.00% <= 5 milliseconds
53648.07 requests per second

====== LPOP ======
100000 requests completed in 1.66 seconds
50 parallel clients
3 bytes payload
keep alive: 1

84.33% <= 1 milliseconds
98.68% <= 2 milliseconds
99.81% <= 3 milliseconds
99.94% <= 4 milliseconds
100.00% <= 4 milliseconds
60168.47 requests per second

====== RPOP ======
100000 requests completed in 1.63 seconds
50 parallel clients
3 bytes payload
keep alive: 1

85.95% <= 1 milliseconds
98.67% <= 2 milliseconds
99.94% <= 3 milliseconds
100.00% <= 4 milliseconds
100.00% <= 4 milliseconds
61312.08 requests per second

====== SADD ======
100000 requests completed in 1.51 seconds
50 parallel clients
3 bytes payload
keep alive: 1

89.27% <= 1 milliseconds
99.38% <= 2 milliseconds
99.96% <= 3 milliseconds
100.00% <= 3 milliseconds
66269.05 requests per second

====== SPOP ======
100000 requests completed in 1.51 seconds
50 parallel clients
3 bytes payload
keep alive: 1

88.74% <= 1 milliseconds
98.88% <= 2 milliseconds
99.94% <= 3 milliseconds
99.99% <= 4 milliseconds
100.00% <= 4 milliseconds
66181.34 requests per second

====== LPUSH (needed to benchmark LRANGE) ======
100000 requests completed in 1.73 seconds
50 parallel clients
3 bytes payload
keep alive: 1

82.01% <= 1 milliseconds
98.85% <= 2 milliseconds
99.86% <= 3 milliseconds
99.99% <= 4 milliseconds
100.00% <= 4 milliseconds
57670.13 requests per second

====== LRANGE_100 (first 100 elements) ======
100000 requests completed in 7.29 seconds
50 parallel clients
3 bytes payload
keep alive: 1

0.22% <= 1 milliseconds
77.24% <= 2 milliseconds
95.23% <= 3 milliseconds
98.68% <= 4 milliseconds
99.44% <= 5 milliseconds
99.78% <= 6 milliseconds
99.89% <= 7 milliseconds
99.96% <= 8 milliseconds
99.97% <= 12 milliseconds
99.98% <= 13 milliseconds
100.00% <= 14 milliseconds
100.00% <= 14 milliseconds
13717.42 requests per second

====== LRANGE_300 (first 300 elements) ======
100000 requests completed in 16.18 seconds
50 parallel clients
3 bytes payload
keep alive: 1

0.02% <= 1 milliseconds
0.42% <= 2 milliseconds
13.05% <= 3 milliseconds
57.46% <= 4 milliseconds
86.03% <= 5 milliseconds
94.10% <= 6 milliseconds
97.45% <= 7 milliseconds
98.60% <= 8 milliseconds
99.10% <= 9 milliseconds
99.38% <= 10 milliseconds
99.55% <= 11 milliseconds
99.65% <= 12 milliseconds
99.73% <= 13 milliseconds
99.81% <= 14 milliseconds
99.86% <= 15 milliseconds
99.88% <= 16 milliseconds
99.91% <= 17 milliseconds
99.93% <= 18 milliseconds
99.93% <= 19 milliseconds
99.95% <= 20 milliseconds
99.97% <= 21 milliseconds
99.97% <= 22 milliseconds
99.98% <= 23 milliseconds
99.98% <= 24 milliseconds
99.98% <= 27 milliseconds
99.99% <= 28 milliseconds
99.99% <= 29 milliseconds
100.00% <= 30 milliseconds
100.00% <= 31 milliseconds
100.00% <= 33 milliseconds
6180.47 requests per second

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
